name: Validate Sheet Requirements

inputs:
  file-list:
    required: true
  separator:
    default: '::'
  credentials:
    required: true
  user:
    required: true
  github-token:
    required: true
  repository:
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
