name: Ci/CD

on:
  push:
    branches: "**"

jobs:
  compile:
    name: "Compile sheet"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup npm
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install npm packages
        run: npm install

      - name: Build test sheet
        run: npm run build

