/* global getAttrs, setAttrs, getSectionIDs, generateRowID, on, removeRepeatingRow, _, getTranslationByKey */

/* Data constants */
const sheetName = "Stars Without Number (revised)";
const sheetVersion = "2.6.5";
const translate = getTranslationByKey;
const attributes = ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"];
const effortAttributes = ["wisdom_mod", "constitution_mod", "psionics_extra_effort",
    "skill_biopsionics", "skill_precognition", "skill_telepathy", "skill_teleportation",
    "skill_telekinesis", "skill_metapsionics", "psionics_committed_effort_current",
    "psionics_committed_effort_scene", "psionics_committed_effort_day"
];
const shipStatEvent = [
    ...["hardpoints", "power", "mass"].map(x => `change:repeating_ship-weapons:weapon_${x}`),
    ...["power", "mass"].map(x => `change:repeating_ship-defenses:defense_${x}`),
    ...["power", "mass"].map(x => `change:repeating_ship-fittings:fitting_${x}`),
    "change:ship_power", "change:ship_mass", "change:ship_hardpoints",
    "remove:repeating_ship-weapons", "remove:repeating_ship-defenses",
    "remove:repeating_ship-fittings"
].join(" ");
const weaponSkills = [
    "skill_exert", "skill_punch", "skill_shoot", "skill_stab", "skill_combat_energy",
    "skill_combat_gunnery", "skill_combat_primitive", "skill_combat_projectile",
    "skill_combat_psitech", "skill_combat_unarmed", "skill_telekinesis", "skill_sunblade"
];
const weaponDisplayEvent = [
    ...["attack", "name", "skill_bonus", "attribute_mod", "damage", "shock", "shock_damage",
        "shock_ac", "skill_to_damage"
    ].map(x => `change:repeating_weapons:weapon_${x}`),
    "remove:repeating_weapons", "change:attack_bonus",
    ...weaponSkills.map(name => `change:${name}`),
].join(" ");
const skills: {[key: string]: string[]} = {
    revised: ["administer", "connect", "exert", "fix", "heal", "know", "lead",
        "notice", "perform", "pilot", "program", "punch", "shoot", "sneak", "stab",
        "survive", "talk", "trade", "work"
    ],
    first: ["artist", "athletics", "bureaucracy", "business", "combat_energy", "combat_gunnery",
        "combat_primitive", "combat_projectile", "combat_psitech", "combat_unarmed", "computer",
        "culture_alien", "culture_criminal", "culture_spacer", "culture_traveller", "culture_one",
        "culture_two", "culture_three", "exosuit", "gambling", "history", "instructor", "language",
        "leadership", "navigation", "perception", "persuade", "profession", "religion", "science",
        "security", "stealth", "steward", "survival", "tactics", "tech_astronautic", "tech_maltech",
        "tech_medical", "tech_postech", "tech_pretech", "tech_psitech", "vehicle_air", "vehicle_grav",
        "vehicle_land", "vehicle_space", "vehicle_water"
    ],
    psionic: ["biopsionics", "metapsionics", "precognition", "telekinesis", "telepathy", "teleportation"],
    magic: ["know_magic", "use_magic", "sunblade"],
    wwn: ["administer", "connect", "convince", "craft", "exert", "heal", "know", "lead", "magic", "notice", "perform", "pray", "punch", "ride", "sail", "shoot", "sneak", "stab", "survive", "trade", "work"],
};
const shipStats = ["ship_ac", "ship_armor", "ship_class", "ship_crew_max", "ship_crew_min",
    "ship_hardpoints_max", "ship_hp", "ship_hp_max", "ship_mass_max", "ship_power_max", "ship_speed", "ship_hull_price",
];

type ReverseHullTypes = 'battleship' | 'bulk_freighter' | 'carrier' | 'corvette' | 'fleet_cruiser' | 'free_merchant' | 'heavy_frigate' | 'large_station' | 'patrol_boat' | 'small_station' | 'strike_fighter' | 'shuttle'

const reverseHullTypes = {
    [translate("BATTLESHIP").toString().toLowerCase()]: "battleship",
    [translate("BULK_FREIGHTER").toString().toLowerCase()]: "bulk_freighter",
    [translate("CARRIER").toString().toLowerCase()]: "carrier",
    [translate("CORVETTE").toString().toLowerCase()]: "corvette",
    [translate("FLEET_CRUISER").toString().toLowerCase()]: "fleet_cruiser",
    [translate("FREE_MERCHANT").toString().toLowerCase()]: "free_merchant",
    [translate("HEAVY_FRIGATE").toString().toLowerCase()]: "heavy_frigate",
    [translate("LARGE_STATION").toString().toLowerCase()]: "large_station",
    [translate("PATROL_BOAT").toString().toLowerCase()]: "patrol_boat",
    [translate("SMALL_STATION").toString().toLowerCase()]: "small_station",
    [translate("STRIKE_FIGHTER").toString().toLowerCase()]: "strike_fighter",
    [translate("SHUTTLE").toString().toLowerCase()]: "shuttle",
};
const reverseClasses = {
    [translate("ADVENTURER").toString().toLowerCase()]: "adventurer",
    [translate("EXPERT").toString().toLowerCase()]: "expert",
    [translate("PSYCHIC").toString().toLowerCase()]: "psychic",
    [translate("WARRIOR").toString().toLowerCase()]: "warrior",
};
const autofillSections = ["armor", "cyberware", "foci", "gear", "ship-defenses", "ship-fittings", "ship-weapons", "techniques", "weapons"];
type AutofillSectionsKey = "armor" | "cyberware" | "foci" | "gear" | "ship-defenses" | "ship-fittings" | "ship-weapons" | "techniques" | "weapons"
const autofillData = {
    "classes": {
        adventurer: {
            class_ability: translate("ADVENTURER_CLASS_ABILITY"),
        },
        expert: {
            class_ability: translate("EXPERT_CLASS_ABILITY"),
        },
        psychic: {
            class_ability: translate("PSYCHIC_CLASS_ABILITY"),
        },
        warrior: {
            attack_bonus: "1",
            class_ability: translate("WARRIOR_CLASS_ABILITY"),
        },
    },
    "drones": {
        alecto: {
            drone_AC: "18",
            drone_enc: "4",
            drone_HP: "30",
            drone_num_fittings: "4",
            drone_range: "5000 km",
            drone_price: "50000",
        },
        cuttlefish: {
            drone_AC: "13",
            drone_enc: "2",
            drone_HP: "10",
            drone_num_fittings: "5",
            drone_range: "1 km",
            drone_price: "2000",
        },
        ghostwalker: {
            drone_AC: "15",
            drone_enc: "3",
            drone_fitting_1_desc: translate("SENSOR_TRANSPARENCY_DESC"),
            drone_fitting_1_name: translate("SENSOR_TRANSPARENCY"),
            drone_HP: "1",
            drone_num_fittings: "3",
            drone_range: "5 km",
            drone_price: "3000",
        },
        pax: {
            drone_AC: "16",
            drone_enc: "4",
            drone_HP: "20",
            drone_num_fittings: "4",
            drone_range: "100 km",
            drone_price: "10000",
        },
        primitve_drone: {
            drone_AC: "12",
            drone_enc: "2",
            drone_HP: "1",
            drone_num_fittings: "1",
            drone_range: "500 m",
            drone_price: "250",
        },
        sleeper: {
            drone_AC: "12",
            drone_enc: "2",
            drone_fitting_1_desc: translate("STATIONKEEPING_DESC"),
            drone_fitting_1_name: translate("STATIONKEEPING"),
            drone_HP: "8",
            drone_num_fittings: "5",
            drone_range: "100 km",
            drone_price: "2500",
        },
        stalker: {
            drone_AC: "13",
            drone_enc: "2",
            drone_HP: "5",
            drone_num_fittings: "3",
            drone_range: "2 km",
            drone_price: "1000",
        },
        void_hawk: {
            drone_AC: "14",
            drone_enc: "6",
            drone_HP: "15",
            drone_num_fittings: "4",
            drone_range: "100 km",
            drone_price: "5000",
        },
    },
    "droneFittings": [
            "ammo_unit",
            "bomber",
            "environmental_power",
            "expert_system",
            "extended_flight",
            "grav_muffles",
            "heavy_lift",
            "holoskin",
            "medical_support",
            "observation_suite",
            "racing_gravitics",
            "reinforced_structure",
            "sensor_transparency",
            "stationkeeping",
            "suicide_charge",
            "weapon_fitting",
    ],
    "hulltypes": {
        battleship: {
            ship_ac: "16",
            ship_armor: "20",
            ship_class: translate("CAPITAL"),
            ship_crew_max: "1000",
            ship_crew_min: "200",
            ship_hardpoints_max: "15",
            ship_hp: "100",
            ship_mass_max: "50",
            ship_power_max: "75",
            ship_speed: "0",
            ship_hull_price: "50000000",
        },
        bulk_freighter: {
            ship_ac: "11",
            ship_armor: "0",
            ship_class: translate("CRUISER"),
            ship_crew_max: "40",
            ship_crew_min: "10",
            ship_hardpoints_max: "2",
            ship_hp: "40",
            ship_mass_max: "25",
            ship_power_max: "15",
            ship_speed: "0",
            ship_hull_price: "5000000",
        },
        carrier: {
            ship_ac: "14",
            ship_armor: "10",
            ship_class: translate("CAPITAL"),
            ship_crew_max: "1500",
            ship_crew_min: "300",
            ship_hardpoints_max: "4",
            ship_hp: "75",
            ship_mass_max: "100",
            ship_power_max: "50",
            ship_speed: "0",
            ship_hull_price: "60000000",
        },
        corvette: {
            ship_ac: "13",
            ship_armor: "10",
            ship_class: translate("FRIGATE"),
            ship_crew_max: "40",
            ship_crew_min: "10",
            ship_hardpoints_max: "6",
            ship_hp: "40",
            ship_mass_max: "15",
            ship_power_max: "15",
            ship_speed: "2",
            ship_hull_price: "4000000",
        },
        fleet_cruiser: {
            ship_ac: "14",
            ship_armor: "15",
            ship_class: translate("CRUISER"),
            ship_crew_max: "200",
            ship_crew_min: "50",
            ship_hardpoints_max: "10",
            ship_hp: "60",
            ship_mass_max: "30",
            ship_power_max: "50",
            ship_speed: "1",
            ship_hull_price: "10000000",
        },
        free_merchant: {
            ship_ac: "14",
            ship_armor: "2",
            ship_class: translate("FRIGATE"),
            ship_crew_max: "6",
            ship_crew_min: "1",
            ship_hardpoints_max: "2",
            ship_hp: "20",
            ship_mass_max: "15",
            ship_power_max: "10",
            ship_speed: "3",
            ship_hull_price: "500000",
        },
        heavy_frigate: {
            ship_ac: "15",
            ship_armor: "10",
            ship_class: translate("FRIGATE"),
            ship_crew_max: "120",
            ship_crew_min: "30",
            ship_hardpoints_max: "8",
            ship_hp: "50",
            ship_mass_max: "20",
            ship_power_max: "25",
            ship_speed: "1",
            ship_hull_price: "7000000",
        },
        large_station: {
            ship_ac: "17",
            ship_armor: "20",
            ship_class: translate("CAPITAL"),
            ship_crew_max: "1000",
            ship_crew_min: "100",
            ship_hardpoints_max: "30",
            ship_hp: "120",
            ship_mass_max: "75",
            ship_power_max: "125",
            ship_speed: "",
            ship_hull_price: "40000000",
        },
        patrol_boat: {
            ship_ac: "14",
            ship_armor: "5",
            ship_class: translate("FRIGATE"),
            ship_crew_max: "20",
            ship_crew_min: "5",
            ship_hardpoints_max: "4",
            ship_hp: "25",
            ship_mass_max: "10",
            ship_power_max: "15",
            ship_speed: "4",
            ship_hull_price: "2500000",
        },
        small_station: {
            ship_ac: "11",
            ship_armor: "5",
            ship_class: translate("CRUISER"),
            ship_crew_max: "200",
            ship_crew_min: "20",
            ship_hardpoints_max: "10",
            ship_hp: "120",
            ship_mass_max: "40",
            ship_power_max: "50",
            ship_speed: "",
            ship_hull_price: "5000000",
        },
        strike_fighter: {
            ship_ac: "16",
            ship_armor: "5",
            ship_class: translate("FIGHTER"),
            ship_crew_max: "1",
            ship_crew_min: "1",
            ship_hardpoints_max: "1",
            ship_hp: "8",
            ship_mass_max: "2",
            ship_power_max: "5",
            ship_speed: "5",
            ship_hull_price: "200000",
        },
        shuttle: {
            ship_ac: "11",
            ship_armor: "0",
            ship_class: translate("FIGHTER"),
            ship_crew_max: "10",
            ship_crew_min: "1",
            ship_hardpoints_max: "1",
            ship_hp: "15",
            ship_mass_max: "5",
            ship_power_max: "3",
            ship_speed: "3",
            ship_hull_price: "200000",
        },
    },
    "statblocks": {
        barbarian_hero: {
            npc_hd: "6",
            npc_ac: "16",
            npc_attack_bonus: "8",
            npc_damage: "Weapon+3",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "11",
            npc_skills: "3",
            npc_saves: "12",
            npc_armor_type: "PRIMITIVE"
        },
        barbarian_tribal: {
            npc_hd: "1",
            npc_ac: "12",
            npc_attack_bonus: "2",
            npc_damage: "Weapon",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "8",
            npc_skills: "1",
            npc_saves: "15",
            npc_armor_type: "PRIMITIVE",
        },
        civilian_security_bot: {
            npc_hd: "1",
            npc_ac: "15",
            npc_attack_bonus: "1",
            npc_damage: "1d8[Stun]",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "12",
            npc_skills: "1",
            npc_saves: "15",
            npc_armor_type: "",
        },
        companion_bot: {
            npc_hd: "1",
            npc_ac: "12",
            npc_attack_bonus: "0",
            npc_damage: "1d2[Unarmed]",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "6",
            npc_skills: "1",
            npc_saves: "15",
            npc_armor_type: "",
        },
        elite_fighter: {
            npc_hd: "3",
            npc_ac: "16",
            npc_attack_bonus: "4",
            npc_damage: "Weapon+1",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "10",
            npc_skills: "2",
            npc_saves: "14",
            npc_armor_type: "COMBAT",
        },
        gang_boss: {
            npc_hd: "3",
            npc_ac: "14",
            npc_attack_bonus: "4",
            npc_damage: "Weapon+1",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "9",
            npc_skills: "2",
            npc_saves: "15",
            npc_armor_type: "",
        },
        gang_member: {
            npc_hd: "1",
            npc_ac: "12",
            npc_attack_bonus: "1",
            npc_damage: "Weapon",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "7",
            npc_skills: "1",
            npc_saves: "15",
            npc_armor_type: "",
        },
        geneengineered_killer: {
            npc_hd: "4",
            npc_ac: "16",
            npc_attack_bonus: "5",
            npc_damage: "Weapon+1",
            npc_attacks: "1",
            npc_move: "15m",
            npc_morale: "10",
            npc_skills: "2",
            npc_saves: "13",
            npc_armor_type: "",
        },
        geneengineered_murder_beast: {
            npc_hd: "10",
            npc_ac: "18",
            npc_attack_bonus: "10",
            npc_damage: "1d10",
            npc_attacks: "4",
            npc_move: "20m",
            npc_morale: "12",
            npc_skills: "3",
            npc_saves: "10",
            npc_armor_type: "",
        },
        greater_lone_predator: {
            npc_hd: "5",
            npc_ac: "16",
            npc_attack_bonus: "6",
            npc_damage: "1d10",
            npc_attacks: "2",
            npc_move: "10m",
            npc_morale: "9",
            npc_skills: "2",
            npc_saves: "12",
            npc_armor_type: "",
        },
        heavy_warbot: {
            npc_hd: "6",
            npc_ac: "18",
            npc_attack_bonus: "8",
            npc_damage: "2d8[Plasma]",
            npc_attacks: "2",
            npc_move: "15m",
            npc_morale: "10",
            npc_skills: "2",
            npc_saves: "12",
            npc_armor_type: "",
        },
        heroic_fighter: {
            npc_hd: "6",
            npc_ac: "16",
            npc_attack_bonus: "8",
            npc_damage: "Weapon+3",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "11",
            npc_skills: "3",
            npc_saves: "12",
            npc_armor_type: "COMBAT",
        },
        industrial_work_bot: {
            npc_hd: "2",
            npc_ac: "15",
            npc_attack_bonus: "0",
            npc_damage: "1d10[Crush]",
            npc_attacks: "1",
            npc_move: "5",
            npc_morale: "8",
            npc_skills: "1",
            npc_saves: "14",
            npc_armor_type: "",
        },
        janitor_bot: {
            npc_hd: "1",
            npc_ac: "14",
            npc_attack_bonus: "0",
            npc_damage: "Unarmed",
            npc_attacks: "1",
            npc_move: "5m",
            npc_morale: "8",
            npc_skills: "1",
            npc_saves: "15",
            npc_armor_type: "",
        },
        large_aggressive_prey_animal: {
            npc_hd: "5",
            npc_ac: "13",
            npc_attack_bonus: "4",
            npc_damage: "1d10",
            npc_attacks: "1",
            npc_move: "15m",
            npc_morale: "8",
            npc_skills: "1",
            npc_saves: "12",
            npc_armor_type: "",
        },
        large_pack_hunter: {
            npc_hd: "2",
            npc_ac: "14",
            npc_attack_bonus: "2",
            npc_damage: "1d6",
            npc_attacks: "1",
            npc_move: "15m",
            npc_morale: "9",
            npc_skills: "1",
            npc_saves: "14",
            npc_armor_type: "",
        },
        legendary_fighter: {
            npc_hd: "10",
            npc_ac: "20",
            npc_attack_bonus: "12",
            npc_damage: "Weapon+4",
            npc_attacks: "2",
            npc_move: "10m",
            npc_morale: "12",
            npc_skills: "5",
            npc_saves: "10",
            npc_armor_type: "POWERED",
        },
        lesser_lone_predator: {
            npc_hd: "3",
            npc_ac: "14",
            npc_attack_bonus: "4",
            npc_damage: "1d8",
            npc_attacks: "2",
            npc_move: "15m",
            npc_morale: "8",
            npc_skills: "2",
            npc_saves: "14",
            npc_armor_type: "",
        },
        martial_human: {
            npc_hd: "1",
            npc_ac: "10",
            npc_attack_bonus: "1",
            npc_damage: "Weapon",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "8",
            npc_skills: "1",
            npc_saves: "15",
            npc_armor_type: "",
        },
        military_elite: {
            npc_hd: "3",
            npc_ac: "16",
            npc_attack_bonus: "4",
            npc_damage: "Weapon+1",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "10",
            npc_skills: "2",
            npc_saves: "14",
            npc_armor_type: "COMBAT",
        },
        military_soldier: {
            npc_hd: "1",
            npc_ac: "16",
            npc_attack_bonus: "1",
            npc_damage: "Weapon",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "9",
            npc_skills: "1",
            npc_saves: "15",
            npc_armor_type: "COMBAT",
        },
        normal_human: {
            npc_hd: "1",
            npc_ac: "10",
            npc_attack_bonus: "0",
            npc_damage: "Unarmed",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "6",
            npc_skills: "1",
            npc_saves: "15",
            npc_armor_type: "",
        },
        peaceful_human: {
            npc_hd: "1",
            npc_ac: "10",
            npc_attack_bonus: "0",
            npc_damage: "Unarmed",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "6",
            npc_skills: "1",
            npc_saves: "15",
            npc_armor_type: "",
        },
        pirate_king: {
            npc_hd: "7",
            npc_ac: "18",
            npc_attack_bonus: "9",
            npc_damage: "Weapon+2",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "11",
            npc_skills: "3",
            npc_saves: "12",
            npc_armor_type: "POWERED",
        },
        police_officer: {
            npc_hd: "1",
            npc_ac: "14",
            npc_attack_bonus: "1",
            npc_damage: "Weapon",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "8",
            npc_skills: "1",
            npc_saves: "15",
            npc_armor_type: "",
        },
        repair_bot: {
            npc_hd: "1",
            npc_ac: "14",
            npc_attack_bonus: "0",
            npc_damage: "1d6[Tool]",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "8",
            npc_skills: "1",
            npc_saves: "15",
            npc_armor_type: "",
        },
        serial_killer: {
            npc_hd: "6",
            npc_ac: "12",
            npc_attack_bonus: "8",
            npc_damage: "Weapon+3",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "12",
            npc_skills: "3",
            npc_saves: "12",
            npc_armor_type: "",
        },
        skilled_professional: {
            npc_hd: "1",
            npc_ac: "10",
            npc_attack_bonus: "0",
            npc_damage: "Weapon",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "6",
            npc_skills: "2",
            npc_saves: "15",
            npc_armor_type: "",
        },
        small_pack_hunter: {
            npc_hd: "1",
            npc_ac: "13",
            npc_attack_bonus: "1",
            npc_damage: "1d4",
            npc_attacks: "1",
            npc_move: "15m",
            npc_morale: "8",
            npc_skills: "1",
            npc_saves: "15",
            npc_armor_type: "",
        },
        small_vicious_beast: {
            npc_hd: "1hp",
            npc_ac: "14",
            npc_attack_bonus: "1",
            npc_damage: "1d2",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "7",
            npc_skills: "1",
            npc_saves: "15",
            npc_armor_type: "",
        },
        soldier_bot: {
            npc_hd: "2",
            npc_ac: "16",
            npc_attack_bonus: "1",
            npc_damage: "Weapon",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "10",
            npc_skills: "1",
            npc_saves: "14",
            npc_armor_type: "",
        },
        terrifying_apex_predator: {
            npc_hd: "8",
            npc_ac: "16",
            npc_attack_bonus: "8",
            npc_damage: "1d10",
            npc_attacks: "2",
            npc_move: "20m",
            npc_morale: "9",
            npc_skills: "2",
            npc_saves: "11",
            npc_armor_type: "",
        },
        veteran_fighter: {
            npc_hd: "2",
            npc_ac: "14",
            npc_attack_bonus: "2",
            npc_damage: "Weapon+1",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "9",
            npc_skills: "1",
            npc_saves: "14",
            npc_armor_type: "",
        },
        warrior_tyrant: {
            npc_hd: "8",
            npc_ac: "20",
            npc_attack_bonus: "10",
            npc_damage: "Weapon+3",
            npc_attacks: "1",
            npc_move: "10m",
            npc_morale: "11",
            npc_skills: "3",
            npc_saves: "11",
            npc_armor_type: "POWERED",
        },
    },
    "armor": {
        armored_undersuit: {
            armor_ac: "13",
            armor_encumbrance: "0",
            armor_type: "STREET",
            armor_price: "600",
        },
        armored_vacc_suit: {
            armor_ac: "13",
            armor_encumbrance: "2",
            armor_type: "STREET",
            armor_price: "400",
        },
        assault_suit: {
            armor_ac: "18",
            armor_encumbrance: "2",
            armor_type: "POWERED",
            armor_price: "10000",
        },
        combat_field_uniform: {
            armor_ac: "16",
            armor_encumbrance: "1",
            armor_type: "COMBAT",
            armor_price: "1000",
        },
        cuirass_brigandine_linothorax_half_plate: {
            armor_ac: "15",
            armor_encumbrance: "1",
            armor_type: "PRIMITIVE",
            armor_price: "50",
        },
        deflector_array: {
            armor_ac: "18",
            armor_encumbrance: "0",
            armor_type: "STREET",
            armor_price: "30000",
        },
        executive_security_suit: {
            armor_ac: "15",
            armor_encumbrance: "0",
            armor_type: "ARTIFACT",
        },
        field_emitter_panoply: {
            armor_ac: "20",
            armor_encumbrance: "1",
            armor_encumbrance_bonus: "4",
            armor_type: "POWERED",
            armor_price: "40000",
        },
        force_pavis: {
            armor_ac: "15",
            armor_ac_bonus: "1",
            armor_encumbrance: "1",
            armor_type: "SHIELD",
            armor_price: "10000",
        },
        full_plate_layered_mail: {
            armor_ac: "17",
            armor_encumbrance: "2",
            armor_type: "PRIMITIVE",
            armor_price: "100",
        },
        ghost_mantle: {
            armor_ac: "15",
            armor_encumbrance: "0",
            armor_type: "ARTIFACT",
        },
        icarus_harness: {
            armor_ac: "16",
            armor_encumbrance: "1",
            armor_type: "COMBAT",
            armor_price: "8000",
        },
        leather_jacks_thick_hides_quilted_armor: {
            armor_ac: "13",
            armor_encumbrance: "1",
            armor_type: "PRIMITIVE",
            armor_price: "10",
        },
        polyplast_carapace: {
            armor_ac: "18",
            armor_encumbrance: "1",
            armor_type: "ARTIFACT",
        },
        psitech_combat_suit: {
            armor_ac: "16",
            armor_encumbrance: "0",
            armor_type: "ARTIFACT",
        },
        secure_clothing: {
            armor_ac: "13",
            armor_encumbrance: "1",
            armor_type: "STREET",
            armor_price: "300",
        },
        security_armor: {
            armor_ac: "14",
            armor_encumbrance: "1",
            armor_type: "COMBAT",
            armor_price: "700",
        },
        shield: {
            armor_ac: "13",
            armor_ac_bonus: "1",
            armor_encumbrance: "2",
            armor_type: "SHIELD",
            armor_price: "10",
        },
        storm_armor: {
            armor_ac: "19",
            armor_encumbrance: "2",
            armor_encumbrance_bonus: "4",
            armor_type: "POWERED",
            armor_price: "20000",
        },
        stutterjump_suit: {
            armor_ac: "18",
            armor_encumbrance: "0",
            armor_type: "ARTIFACT",
        },
        tempest_assault_array: {
            armor_ac: "20",
            armor_encumbrance: "1",
            armor_encumbrance_bonus: "4",
            armor_type: "ARTIFACT",
        },
        titan_powered_armor: {
            armor_ac: "21",
            armor_encumbrance: "2",
            armor_encumbrance_bonus: "4",
            armor_type: "ARTIFACT",
        },
        vestimentum: {
            armor_ac: "18",
            armor_encumbrance: "0",
            armor_type: "POWERED",
            armor_price: "15000",
        },
        warpaint: {
            armor_ac: "12",
            armor_encumbrance: "0",
            armor_type: "STREET",
            armor_price: "300",
        },
        woven_body_armor: {
            armor_ac: "15",
            armor_encumbrance: "2",
            armor_type: "COMBAT",
            armor_price: "400",
        }
    },
    "cyberware": {
        adrenal_suppression_pump: {
            cyberware_strain: "1",
            cyberware_price: "30000"
        },
        bioadaptation_augments: {
            cyberware_strain: "1",
            cyberware_price: "10000"
        },
        body_arsenal_array: {
            cyberware_strain: "1",
            cyberware_price: "10000"
        },
        body_sculpting: {
            cyberware_strain: "1",
            cyberware_price: "10000"
        },
        dermal_armor: {
            cyberware_strain: "2",
            cyberware_price: "20000"
        },
        drone_control_link: {
            cyberware_strain: "1",
            cyberware_price: "20000"
        },
        eelskin_capacitor_mesh: {
            cyberware_strain: "1",
            cyberware_price: "25000"
        },
        gecko_anchors: {
            cyberware_strain: "1",
            cyberware_price: "15000"
        },
        ghost_talker_transceiver: {
            cyberware_strain: "1",
            cyberware_price: "15000"
        },
        holdout_cavity: {
            cyberware_strain: "1",
            cyberware_price: "10000"
        },
        holoskin_emitter: {
            cyberware_strain: "1",
            cyberware_price: "15000"
        },
        identity_submersion_trigger: {
            cyberware_strain: "1",
            cyberware_price: "25000"
        },
        immunofiltration_systems: {
            cyberware_strain: "2",
            cyberware_price: "25000"
        },
        induced_coma_trigger: {
            cyberware_strain: "1",
            cyberware_price: "20000"
        },
        neurointruder_alert: {
            cyberware_strain: "1",
            cyberware_price: "50000"
        },
        panspectral_optics: {
            cyberware_strain: "1",
            cyberware_price: "15000"
        },
        pressure_sheathing: {
            cyberware_strain: "1",
            cyberware_price: "15000"
        },
        prosthetic_limb: {
            cyberware_strain: "1",
            cyberware_price: "2500"
        },
        revenant_wiring: {
            cyberware_strain: "3",
            cyberware_price: "50000"
        },
        slowtime_window: {
            cyberware_strain: "2",
            cyberware_price: "30000"
        },
        stabilization_overrides: {
            cyberware_strain: "2",
            cyberware_price: "25000"
        },
        tagger_nanites: {
            cyberware_strain: "1",
            cyberware_price: "15000"
        },
        toxin_injector: {
            cyberware_strain: "2",
            cyberware_price: "20000"
        },
        twitchlock_actuators: {
            cyberware_strain: "2",
            cyberware_price: "30000"
        },
    },
    "foci": {
        alert: {},
        armsman: {},
        assassin: {},
        authority: {},
        close_combatant: {},
        connected: {},
        die_hard: {},
        diplomat: {},
        gunslinger: {},
        hacker: {},
        healer: {},
        henchkeeper: {},
        ironhide: {},
        psychic_training: {},
        savage_fray: {},
        shocking_assault: {},
        sniper: {},
        specialist: {},
        star_captain: {},
        starfarer: {},
        tinker: {},
        unarmed_combatant: {},
        unique_gift: {},
        wanderer: {},
        wild_psychic_talent: {},
    },
    "gear": {
        ai_companion: {
            gear_encumbrance: "0",
        },
        ammo_20_rounds: {
            gear_encumbrance: "1#",
            gear_price: "10",
        },
        ammo_missile: {
            gear_encumbrance: "1",
            gear_price: "50",
        },
        atmofilter: {
            gear_encumbrance: "1",
            gear_price: "100",
        },
        backpack: {
            gear_encumbrance: "1",
            gear_price: "5/50",
        },
        bezoar: {
            gear_encumbrance: "0",
            gear_price: "200",
        },
        binoculars: {
            gear_encumbrance: "1",
            gear_price: "20/200",
        },
        bioscanner: {
            gear_encumbrance: "1",
            gear_price: "300",
        },
        black_slab: {
            gear_encumbrance: "1",
            gear_price: "10000",
        },
        brainwave: {
            gear_encumbrance: "0",
            gear_price: "1000",
        },
        climbing_harness: {
            gear_encumbrance: "1",
            gear_price: "50",
        },
        comm_server: {
            gear_encumbrance: "3",
            gear_price: "1000",
        },
        compad: {
            gear_encumbrance: "0",
            gear_price: "100",
        },
        data_phase_tab: {
            gear_encumbrance: "1",
            gear_price: "5000",
        },
        data_protocol: {
            gear_encumbrance: "0",
            gear_price: "1000",
        },
        dataslab: {
            gear_encumbrance: "1",
            gear_price: "300",
        },
        field_radio: {
            gear_encumbrance: "1",
            gear_price: "200",
        },
        glowbug: {
            gear_encumbrance: "0",
            gear_price: "5",
        },
        grapnel_launcher: {
            gear_encumbrance: "1",
            gear_price: "200",
        },
        grav_chute: {
            gear_encumbrance: "1",
            gear_price: "300/1000",
        },
        grav_harness: {
            gear_encumbrance: "3",
            gear_price: "5000",
        },
        hush: {
            gear_encumbrance: "0",
            gear_price: "200",
        },
        instapanel: {
            gear_encumbrance: "1#",
            gear_price: "50",
        },
        integrity_stims: {
            gear_encumbrance: "0",
        },
        juggernaut_stims: {
            gear_encumbrance: "0",
        },
        lazarus_patch: {
            gear_encumbrance: "1#",
            gear_price: "30",
        },
        lift: {
            gear_encumbrance: "0",
            gear_price: "50",
        },
        line_shunt: {
            gear_encumbrance: "0",
            gear_price: "100",
        },
        low_light_goggles: {
            gear_encumbrance: "1",
            gear_price: "200",
        },
        medkit: {
            gear_encumbrance: "2",
            gear_price: "100",
        },
        metatool: {
            gear_encumbrance: "1",
            gear_price: "200",
        },
        micropurgator_stims: {
            gear_encumbrance: "0",
        },
        mindwall_helmet: {
            gear_encumbrance: "0",
        },
        navcomp: {
            gear_encumbrance: "1",
            gear_price: "500",
        },
        polymorphic_nanites: {
            gear_encumbrance: "1",
        },
        portabox: {
            gear_encumbrance: "1",
            gear_price: "50",
        },
        pseudonuke: {
            gear_encumbrance: "1",
        },
        power_cell_type_a: {
            gear_encumbrance: "1#",
            gear_price: "10",
        },
        power_cell_type_b: {
            gear_encumbrance: "1",
            gear_price: "100",
        },
        pressure_tent: {
            gear_encumbrance: "4",
            gear_price: "100",
        },
        pretech_cosmetic: {
            gear_encumbrance: "0",
            gear_price: "1000",
        },
        psych: {
            gear_encumbrance: "0",
            gear_price: "25",
        },
        rations_1_day: {
            gear_encumbrance: "1#",
            gear_price: "5",
        },
        redivivus_sheath: {
            gear_encumbrance: "1",
        },
        remote_link_unit: {
            gear_encumbrance: "1",
            gear_price: "250",
        },
        reverie: {
            gear_encumbrance: "0",
            gear_price: "100",
        },
        rope_20_meters: {
            gear_encumbrance: "2/1",
            gear_price: "4/40",
        },
        scout_report: {
            gear_encumbrance: "0",
            gear_price: "200",
        },
        solar_recharger: {
            gear_encumbrance: "3",
            gear_price: "500",
        },
        spare_parts: {
            gear_encumbrance: "1#",
            gear_price: "50",
        },
        squeal: {
            gear_encumbrance: "0",
            gear_price: "300",
        },
        stiletto_charge: {
            gear_encumbrance: "1",
            gear_price: "Priceless",
        },
        storage_unit: {
            gear_encumbrance: "3",
            gear_price: "500",
        },
        survey_scanner: {
            gear_encumbrance: "1",
            gear_price: "250",
        },
        survival_kit: {
            gear_encumbrance: "1",
            gear_price: "60",
        },
        system_reset_inductor: {
            gear_encumbrance: "0",
        },
        tailored_antiallergens: {
            gear_encumbrance: "0",
            gear_price: "5",
        },
        telekinetic_generator: {
            gear_encumbrance: "2",
            gear_price: "250",
        },
        telescoping_pole: {
            gear_encumbrance: "0",
            gear_price: "10",
        },
        thermal_flare: {
            gear_encumbrance: "0",
            gear_price: "5",
        },
        tightbeam_link_unit: {
            gear_encumbrance: "1",
            gear_price: "1000",
        },
        toolkit_postech: {
            gear_encumbrance: "3",
            gear_price: "300",
        },
        toolkit_pretech: {
            gear_encumbrance: "1",
            gear_price: "1000",
        },
        trade_goods: {
            gear_encumbrance: "1#",
            gear_price: "50",
        },
        trade_metals: {
            gear_encumbrance: "1#",
            gear_price: "10",
        },
        translator_torc: {
            gear_encumbrance: "0",
            gear_price: "200",
        },
        tsunami: {
            gear_encumbrance: "0",
            gear_price: "50",
        },
        vacc_fresher: {
            gear_encumbrance: "1",
            gear_price: "400",
        },
        vacc_skin: {
            gear_encumbrance: "1",
            gear_price: "1000",
        },
        vacc_suit: {
            gear_encumbrance: "2",
            gear_price: "100",
        },
        wideawake_serum: {
            gear_encumbrance: "0",
        },
    },
    "ship-defenses": {
        ablative_hull_compartments: {
            class: "CAPITAL",
            defense_effect: `+1 ${translate("AC")}, +20 ${translate("MAXIMUM_HIT_POINTS").toString().toLowerCase()}.`,
            defense_mass: "2#",
            defense_power: "5",
            defense_price: "100000*",
        },
        augmented_plating: {
            class: "FIGHTER",
            defense_effect: `+2 ${translate("AC")}, -1 ${translate("SPEED")}.`,
            defense_mass: "1#",
            defense_power: "0",
            defense_price: "25000*",
        },
        boarding_countermeasures: {
            class: "FRIGATE",
            defense_effect: translate("BOARDING_COUNTERMEASURES_DESC"),
            defense_mass: "1#",
            defense_power: "2",
            defense_price: "25000*",
        },
        burst_ecm_generator: {
            class: "FRIGATE",
            defense_effect: translate("BURST_ECM_GENERATOR_DESC"),
            defense_mass: "1#",
            defense_power: "2",
            defense_price: "25000*",
        },
        foxer_drones: {
            class: "CRUISER",
            defense_effect: translate("FOXER_DRONES_DESC"),
            defense_mass: "1#",
            defense_power: "2",
            defense_price: "10000*",
        },
        grav_eddy_displacer: {
            class: "FRIGATE",
            defense_effect: translate("GRAV_EDDY_DISPLACER_DESC"),
            defense_mass: "2#",
            defense_power: "5",
            defense_price: "50000*",
        },
        hardened_polyceramic_overlay: {
            class: "FIGHTER",
            defense_effect: translate("HARDENED_POLYCERAMIC_OVERLAY_DESC"),
            defense_mass: "1#",
            defense_power: "0",
            defense_price: "25000*",
        },
        planetary_defense_array: {
            class: "FRIGATE",
            defense_effect: translate("PLANETARY_DEFENSE_ARRAY_DESC"),
            defense_mass: "2#",
            defense_power: "4",
            defense_price: "50000*",
        },
        point_defense_lasers: {
            class: "FRIGATE",
            defense_effect: translate("POINT_DEFENSE_LASERS_DESC"),
            defense_mass: "2#",
            defense_power: "3",
            defense_price: "10000*",
        },
    },
    "ship-fittings": {
        advanced_lab: {
            class: "FRIGATE",
            fitting_mass: "2",
            fitting_power: "1#",
            fitting_price: "10000*",
        },
        advanced_nav_computer: {
            class: "FRIGATE",
            fitting_mass: "0",
            fitting_power: "1#",
            fitting_price: "10000*",
        },
        amphibious_operation: {
            class: "FIGHTER",
            fitting_mass: "1#",
            fitting_power: "1",
            fitting_price: "25000*",
        },
        armory: {
            class: "FRIGATE",
            fitting_mass: "0",
            fitting_power: "0",
            fitting_price: "10000*",
        },
        atmospheric_configuration: {
            class: "FIGHTER",
            fitting_mass: "1#",
            fitting_power: "0",
            fitting_price: "5000*",
        },
        auto_targeting_system: {
            class: "FIGHTER",
            fitting_mass: "0",
            fitting_power: "1",
            fitting_price: "50000",
        },
        automation_support: {
            class: "FIGHTER",
            fitting_mass: "1",
            fitting_power: "2",
            fitting_price: "10000*",
        },
        boarding_tubes: {
            class: "FRIGATE",
            fitting_mass: "1",
            fitting_power: "0",
            fitting_price: "5000*",
        },
        cargo_lighter: {
            class: "FRIGATE",
            fitting_mass: "2",
            fitting_power: "0",
            fitting_price: "25000",
        },
        cargo_space: {
            class: "FIGHTER",
            fitting_mass: "1",
            fitting_power: "0",
            fitting_price: "",
        },
        cold_sleep_pods: {
            class: "FRIGATE",
            fitting_mass: "1",
            fitting_power: "1",
            fitting_price: "5000*",
        },
        colony_core: {
            class: "FRIGATE",
            fitting_mass: "2#",
            fitting_power: "4",
            fitting_price: "100000*",
        },
        drill_course_regulator: {
            class: "FRIGATE",
            fitting_mass: "1",
            fitting_power: "1#",
            fitting_price: "25000*",
        },
        spike_drive_2: {
            class: "FIGHTER",
            fitting_mass: "1#",
            fitting_power: "1#",
            fitting_price: "10000*",
        },
        spike_drive_3: {
            class: "FIGHTER",
            fitting_mass: "2#",
            fitting_power: "2#",
            fitting_price: "20000*",
        },
        spike_drive_4: {
            class: "FRIGATE",
            fitting_mass: "3#",
            fitting_power: "2#",
            fitting_price: "40000*",
        },
        spike_drive_5: {
            class: "FRIGATE",
            fitting_mass: "3#",
            fitting_power: "3#",
            fitting_price: "100000*",
        },
        spike_drive_6: {
            class: "CRUISER",
            fitting_mass: "4#",
            fitting_power: "3#",
            fitting_price: "500000*",
        },
        drop_pod: {
            class: "FRIGATE",
            fitting_mass: "2",
            fitting_power: "0",
            fitting_price: "300000",
        },
        emissions_dampers: {
            class: "FIGHTER",
            fitting_mass: "1#",
            fitting_power: "1#",
            fitting_price: "25000*",
        },
        exodus_bay: {
            class: "CRUISER",
            fitting_mass: "2#",
            fitting_power: "1#",
            fitting_price: "50000*",
        },
        extended_life_support: {
            class: "FIGHTER",
            fitting_mass: "1#",
            fitting_power: "1#",
            fitting_price: "5000*",
        },
        extended_medbay: {
            class: "FRIGATE",
            fitting_mass: "1",
            fitting_power: "1",
            fitting_price: "5000*",
        },
        extended_store: {
            class: "FIGHTER",
            fitting_mass: "1#",
            fitting_power: "0",
            fitting_price: "2500*",
        },
        fuel_bunkers: {
            class: "FIGHTER",
            fitting_mass: "1",
            fitting_power: "0",
            fitting_price: "2500*",
        },
        fuel_scoops: {
            class: "FRIGATE",
            fitting_mass: "1#",
            fitting_power: "2",
            fitting_price: "5000*",
        },
        hydroponic_production: {
            class: "CRUISER",
            fitting_mass: "2#",
            fitting_power: "1#",
            fitting_price: "10000*",
        },
        lifeboats: {
            class: "FRIGATE",
            fitting_mass: "1",
            fitting_power: "0",
            fitting_price: "2500*",
        },
        luxury_cabins: {
            class: "FRIGATE",
            fitting_mass: "1#",
            fitting_power: "1",
            fitting_price: "10000*",
        },
        mobile_extractor: {
            class: "FRIGATE",
            fitting_mass: "1",
            fitting_power: "2",
            fitting_price: "50000",
        },
        mobile_factory: {
            class: "CRUISER",
            fitting_mass: "2#",
            fitting_power: "3",
            fitting_price: "50000*",
        },
        precognitive_nav_chamber: {
            class: "FRIGATE",
            fitting_mass: "0",
            fitting_power: "1",
            fitting_price: "100000*",
        },
        psionic_anchorpoint: {
            class: "FRIGATE",
            fitting_mass: "0",
            fitting_power: "3",
            fitting_price: "Special",
        },
        sensor_mask: {
            class: "FRIGATE",
            fitting_mass: "0",
            fitting_power: "1#",
            fitting_price: "10000*",
        },
        ship_bay_fighter: {
            class: "CRUISER",
            fitting_mass: "2",
            fitting_power: "0",
            fitting_price: "200000",
        },
        ship_bay_frigate: {
            class: "CAPITAL",
            fitting_mass: "4",
            fitting_power: "1",
            fitting_price: "1000000",
        },
        ships_locker: {
            class: "FRIGATE",
            fitting_mass: "0",
            fitting_power: "0",
            fitting_price: "2000*",
        },
        shiptender_mount: {
            class: "FRIGATE",
            fitting_mass: "1",
            fitting_power: "1",
            fitting_price: "25000*",
        },
        smugglers_hold: {
            class: "FIGHTER",
            fitting_mass: "1",
            fitting_power: "0",
            fitting_price: "2500*",
        },
        survey_sensor_array: {
            class: "FRIGATE",
            fitting_mass: "1",
            fitting_power: "2",
            fitting_price: "5000*",
        },
        system_drive: {
            class: "FIGHTER",
            fitting_mass: "-2#",
            fitting_power: "-1#",
            fitting_price: "Special",
        },
        teleportation_pads: {
            class: "FRIGATE",
            fitting_mass: "1",
            fitting_power: "1",
            fitting_price: "Special",
        },
        tractor_beams: {
            class: "FRIGATE",
            fitting_mass: "1",
            fitting_power: "2",
            fitting_price: "10000*",
        },
        vehicle_transport_fittings: {
            class: "FRIGATE",
            fitting_mass: "1#",
            fitting_power: "0",
            fitting_price: "2500*",
        },
        workshop: {
            class: "FRIGATE",
            fitting_mass: "0.5#",
            fitting_power: "1",
            fitting_price: "500*",
        },
    },
    "ship-weapons": {
        charged_particle_caster: {
            class: "FRIGATE",
            weapon_damage: "3d6",
            weapon_hardpoints: "2",
            weapon_mass: "1",
            weapon_power: "10",
            weapon_price: "800000",
            weapon_qualities: `${translate("AP")} 15, ${translate("CLUMSY")}`,
        },
        flak_emitter_battery: {
            class: "FRIGATE",
            weapon_damage: "2d6",
            weapon_hardpoints: "1",
            weapon_mass: "3",
            weapon_power: "5",
            weapon_price: "500000",
            weapon_qualities: `${translate("AP")} 10, ${translate("FLAK")}`,
        },
        fractal_impact_charge: {
            weapon_ammo: "4",
            weapon_ammo_price: "500",
            class: "FIGHTER",
            weapon_damage: "2d6",
            weapon_hardpoints: "1",
            weapon_mass: "1",
            weapon_power: "5",
            weapon_price: "200000",
            weapon_qualities: `${translate("AP")} 15`,
        },
        gravcannon: {
            class: "CRUISER",
            weapon_damage: "4d6",
            weapon_hardpoints: "3",
            weapon_mass: "4",
            weapon_power: "15",
            weapon_price: "2000000",
            weapon_qualities: `${translate("AP")} 20`,
        },
        lightning_charge_mantle: {
            class: "CAPITAL",
            weapon_damage: "1d20",
            weapon_hardpoints: "2",
            weapon_mass: "5",
            weapon_power: "15",
            weapon_price: "4000000",
            weapon_qualities: `${translate("AP")} 5, ${translate("CLOUD")}`,
        },
        mag_spike_array: {
            weapon_ammo: "5",
            weapon_ammo_price: "5000",
            class: "FRIGATE",
            weapon_damage: "2d6+2",
            weapon_hardpoints: "2",
            weapon_mass: "2",
            weapon_power: "5",
            weapon_price: "1000000",
            weapon_qualities: `${translate("AP")} 10, ${translate("FLAK")}`,
        },
        mass_cannon: {
            weapon_ammo: "4",
            weapon_ammo_price: "50000",
            class: "CAPITAL",
            weapon_damage: "2d20",
            weapon_hardpoints: "4",
            weapon_mass: "5",
            weapon_power: "10",
            weapon_price: "5000000",
            weapon_qualities: `${translate("AP")} 20`,
        },
        multifocal_laser: {
            class: "FIGHTER",
            weapon_damage: "1d4",
            weapon_hardpoints: "1",
            weapon_mass: "1",
            weapon_power: "5",
            weapon_price: "100000",
            weapon_qualities: `${translate("AP")} 20`,
        },
        nuclear_missiles: {
            weapon_ammo: "5",
            weapon_ammo_price: "5000",
            class: "FRIGATE",
            weapon_damage: "",
            weapon_hardpoints: "2",
            weapon_mass: "1",
            weapon_power: "5",
            weapon_price: "50000",
            weapon_qualities: "",
        },
        plasma_beam: {
            class: "FRIGATE",
            weapon_damage: "3d6",
            weapon_hardpoints: "2",
            weapon_mass: "2",
            weapon_power: "5",
            weapon_price: "700000",
            weapon_qualities: `${translate("AP")} 10`,
        },
        polyspectral_mes_beam: {
            class: "FIGHTER",
            weapon_damage: "2d4",
            weapon_hardpoints: "1",
            weapon_mass: "1",
            weapon_power: "5",
            weapon_price: "2000000",
            weapon_qualities: `${translate("AP")} 25`,
        },
        reaper_battery: {
            class: "FIGHTER",
            weapon_damage: "3d4",
            weapon_hardpoints: "1",
            weapon_mass: "1",
            weapon_power: "4",
            weapon_price: "100000",
            weapon_qualities: translate("CLUMSY"),
        },
        sandthrower: {
            class: "FIGHTER",
            weapon_damage: "2d4",
            weapon_hardpoints: "1",
            weapon_mass: "1",
            weapon_power: "3",
            weapon_price: "50000",
            weapon_qualities: translate("FLAK"),
        },
        singularity_gun: {
            class: "CAPITAL",
            weapon_damage: "5d20",
            weapon_hardpoints: "5",
            weapon_mass: "10",
            weapon_power: "25",
            weapon_price: "20000000",
            weapon_qualities: `${translate("AP")} 25`,
        },
        smart_cloud: {
            class: "CRUISER",
            weapon_damage: "3d10",
            weapon_hardpoints: "2",
            weapon_mass: "5",
            weapon_power: "10",
            weapon_price: "2000000",
            weapon_qualities: `${translate("CLOUD")}, ${translate("CLUMSY")}`,
        },
        spike_inversion_projector: {
            class: "CRUISER",
            weapon_damage: "3d8",
            weapon_hardpoints: "3",
            weapon_mass: "3",
            weapon_power: "10",
            weapon_price: "2500000",
            weapon_qualities: `${translate("AP")} 15`,
        },
        spinal_beam_cannon: {
            class: "CRUISER",
            weapon_damage: "3d10",
            weapon_hardpoints: "3",
            weapon_mass: "5",
            weapon_power: "10",
            weapon_price: "1500000",
            weapon_qualities: `${translate("AP")} 15, ${translate("CLUMSY")}`,
        },
        torpedo_launcher: {
            weapon_ammo: "4",
            weapon_ammo_price: "2500",
            class: "FRIGATE",
            weapon_damage: "3d8",
            weapon_hardpoints: "1",
            weapon_mass: "3",
            weapon_power: "10",
            weapon_price: "500000",
            weapon_qualities: `${translate("AP")} 20`,
        },
        vortex_tunnel_inductor: {
            class: "CAPITAL",
            weapon_damage: "3d20",
            weapon_hardpoints: "4",
            weapon_mass: "10",
            weapon_power: "20",
            weapon_price: "5000000",
            weapon_qualities: `${translate("AP")} 20, ${translate("CLUMSY")}`,
        },
    },
    "techniques": {
        accelerated_succor: {
            level: "3",
            technique_discipline: translate("BIOPSIONICS"),
        },
        alternate_outcome: {
            level: "2",
            technique_discipline: translate("PRECOGNITION"),
        },
        anguished_vision: {
            level: "3",
            technique_discipline: translate("PRECOGNITION"),
        },
        burdened_apportation: {
            level: "2",
            technique_discipline: translate("TELEPORTATION"),
        },
        cloak_powers: {
            level: "1",
            technique_discipline: translate("METAPSIONICS"),
        },
        concert_of_minds: {
            level: "3",
            technique_discipline: translate("METAPSIONICS"),
        },
        cursed_luck: {
            level: "3",
            technique_discipline: translate("PRECOGNITION"),
        },
        deep_intrusion: {
            level: "4",
            technique_discipline: translate("TELEPORTATION"),
        },
        destinys_shield: {
            level: "2",
            technique_discipline: translate("PRECOGNITION"),
        },
        effortless_apportation: {
            level: "3",
            technique_discipline: translate("TELEPORTATION"),
        },
        facile_mind: {
            level: "1",
            technique_discipline: translate("TELEPATHY"),
        },
        far_thought: {
            level: "2",
            technique_discipline: translate("TELEPATHY"),
        },
        flawless_mastery: {
            level: "4",
            technique_discipline: translate("METAPSIONICS"),
        },
        force_puppetry: {
            level: "4",
            technique_discipline: translate("TELEKINESIS"),
        },
        forced_outcome: {
            level: "3",
            technique_discipline: translate("PRECOGNITION"),
        },
        holistic_optimization_patterning: {
            level: "4",
            technique_discipline: translate("BIOPSIONICS"),
        },
        impact_sump: {
            level: "2",
            technique_discipline: translate("TELEKINESIS"),
        },
        impervious_pavis_of_will: {
            level: "4",
            technique_discipline: translate("METAPSIONICS"),
        },
        intuitive_response: {
            level: "1",
            technique_discipline: translate("PRECOGNITION"),
        },
        invincible_stand: {
            level: "2",
            technique_discipline: translate("BIOPSIONICS"),
        },
        kinetic_transversal: {
            level: "1",
            technique_discipline: translate("TELEKINESIS"),
        },
        major_organ_restoration: {
            level: "2",
            technique_discipline: translate("BIOPSIONICS"),
        },
        mastered_succor: {
            level: "1",
            technique_discipline: translate("BIOPSIONICS"),
        },
        memory_editing: {
            level: "4",
            technique_discipline: translate("TELEPATHY"),
        },
        metadimensional_friction: {
            level: "3",
            technique_discipline: translate("METAPSIONICS"),
        },
        metamorph: {
            level: "3",
            technique_discipline: translate("BIOPSIONICS"),
        },
        mindtracing: {
            level: "1",
            technique_discipline: translate("METAPSIONICS"),
        },
        neural_trap: {
            level: "2",
            technique_discipline: translate("METAPSIONICS"),
        },
        not_my_time: {
            level: "4",
            technique_discipline: translate("PRECOGNITION"),
        },
        offensive_apportation: {
            level: "4",
            technique_discipline: translate("TELEPORTATION"),
        },
        oracle: {
            level: "0",
            technique_discipline: translate("PRECOGNITION"),
        },
        organic_purification_protocols: {
            level: "1",
            technique_discipline: translate("BIOPSIONICS"),
        },
        perceptive_dislocation: {
            level: "2",
            technique_discipline: translate("TELEPORTATION"),
        },
        personal_apportation: {
            level: "0",
            technique_discipline: translate("TELEPORTATION"),
        },
        pressure_field: {
            level: "1",
            technique_discipline: translate("TELEKINESIS"),
        },
        proficient_apportation: {
            level: "1",
            technique_discipline: translate("TELEPORTATION"),
        },
        prophecy: {
            level: "4",
            technique_discipline: translate("PRECOGNITION"),
        },
        psychic_refinement: {
            level: "0",
            technique_discipline: translate("METAPSIONICS"),
        },
        psychic_static: {
            level: "2",
            technique_discipline: translate("METAPSIONICS"),
        },
        psychic_succor: {
            level: "0",
            technique_discipline: translate("BIOPSIONICS"),
        },
        psychic_tutelage: {
            level: "3",
            technique_discipline: translate("METAPSIONICS"),
        },
        quintessential_reconstruction: {
            level: "4",
            technique_discipline: translate("BIOPSIONICS"),
        },
        reactive_telekinesis: {
            level: "3",
            technique_discipline: translate("TELEKINESIS"),
        },
        reflex_response: {
            level: "3",
            technique_discipline: translate("TELEPATHY"),
        },
        remote_repair: {
            level: "1",
            technique_discipline: translate("BIOPSIONICS"),
        },
        rift_reduplication: {
            level: "3",
            technique_discipline: translate("TELEPORTATION"),
        },
        sense_the_need: {
            level: "1",
            technique_discipline: translate("PRECOGNITION"),
        },
        slip_field: {
            level: "2",
            technique_discipline: translate("TELEKINESIS"),
        },
        spatial_awareness: {
            level: "1",
            technique_discipline: translate("TELEPORTATION"),
        },
        spatial_synchrony_mandala: {
            level: "2",
            technique_discipline: translate("TELEPORTATION"),
        },
        stutterjump: {
            level: "3",
            technique_discipline: translate("TELEPORTATION"),
        },
        suppress_cognition: {
            level: "2",
            technique_discipline: translate("TELEPATHY"),
        },
        surge_momentum: {
            level: "3",
            technique_discipline: translate("METAPSIONICS"),
        },
        suspended_manifestation: {
            level: "2",
            technique_discipline: translate("METAPSIONICS"),
        },
        synthetic_adaptation: {
            level: "1",
            technique_discipline: translate("METAPSIONICS"),
        },
        tangible_force_construct: {
            level: "3",
            technique_discipline: translate("TELEKINESIS"),
        },
        telekinetic_armory: {
            level: "1",
            technique_discipline: translate("TELEKINESIS"),
        },
        telekinetic_expertise: {
            level: "2",
            technique_discipline: translate("TELEKINESIS"),
        },
        telekinetic_flight: {
            level: "4",
            technique_discipline: translate("TELEKINESIS"),
        },
        telekinetic_manipulation: {
            level: "0",
            technique_discipline: translate("TELEKINESIS"),
        },
        telekinetic_ram: {
            level: "3",
            technique_discipline: translate("TELEKINESIS"),
        },
        telepathic_assault: {
            level: "3",
            technique_discipline: translate("TELEPATHY"),
        },
        telepathic_contact: {
            level: "0",
            technique_discipline: translate("TELEPATHY"),
        },
        teratic_overload: {
            level: "3",
            technique_discipline: translate("BIOPSIONICS"),
        },
        terminal_reflection: {
            level: "1",
            technique_discipline: translate("PRECOGNITION"),
        },
        thermokinesis: {
            level: "2",
            technique_discipline: translate("TELEKINESIS"),
        },
        tissue_integrity_field: {
            level: "2",
            technique_discipline: translate("BIOPSIONICS"),
        },
        transmit_thought: {
            level: "1",
            technique_discipline: translate("TELEPATHY"),
        },
        unity_of_thought: {
            level: "4",
            technique_discipline: translate("TELEPATHY"),
        },
    },
    "weapons": {
        advanced_bow: {
            weapon_ammo: "1",
            weapon_damage: "1d6",
            weapon_encumbrance: "2",
            weapon_range: "100/150",
            weapon_price: "50",
        },
        anti_vehicle_laser: {
            weapon_ammo: "15",
            weapon_damage: "3d10",
            weapon_range: "2000/4000",
            weapon_price: "10000",
        },
        combat_rifle: {
            weapon_ammo: "30",
            weapon_burst: "true",
            weapon_damage: "1d12",
            weapon_encumbrance: "2",
            weapon_range: "100/300",
            weapon_price: "300",
        },
        combat_shotgun: {
            weapon_ammo: "12",
            weapon_burst: "true",
            weapon_damage: "3d4",
            weapon_encumbrance: "2",
            weapon_range: "10/30",
            weapon_price: "300",
        },
        conversion_bow: {
            weapon_ammo: "1",
            weapon_damage: "1d8",
            weapon_encumbrance: "2",
            weapon_range: "150/300",
            weapon_price: "500",
        },
        crude_pistol: {
            weapon_ammo: "1",
            weapon_damage: "1d6",
            weapon_encumbrance: "1",
            weapon_range: "5/15",
            weapon_price: "20",
        },
        demo_charge: {
            weapon_damage: "3d10",
            weapon_encumbrance: "1",
            weapon_range: "20/40",
            weapon_price: "250",
        },
        distortion_cannon: {
            weapon_attack: "1",
            weapon_ammo: "6",
            weapon_damage: "2d12",
            weapon_encumbrance: "2",
            weapon_range: "100/300",
            weapon_price: "1250",
        },
        grenade: {
            weapon_damage: "2d6",
            weapon_encumbrance: "1",
            weapon_range: "10/30",
            weapon_price: "25",
        },
        heavy_machine_gun: {
            weapon_ammo: "10",
            weapon_damage: "3d6",
            weapon_encumbrance: "3",
            weapon_range: "500/2000",
            weapon_price: "5000",
        },
        hydra_array: {
            weapon_ammo: "10",
            weapon_damage: "3d6",
            weapon_range: "4000/8000",
            weapon_price: "20000",
        },
        large_advanced_weapon: {
            weapon_attribute_mod: "@{strength_mod}",
            weapon_damage: "1d10+1",
            weapon_encumbrance: "2",
            weapon_shock_ac: "15",
            weapon_shock_damage: "2",
            weapon_skill_bonus: "@{skill_stab}",
            weapon_price: "80",
        },
        large_primitive_weapon: {
            weapon_attribute_mod: "@{strength_mod}",
            weapon_damage: "1d8+1",
            weapon_encumbrance: "2",
            weapon_shock_ac: "15",
            weapon_shock_damage: "2",
            weapon_skill_bonus: "@{skill_stab}",
            weapon_price: "30",
        },
        laser_pistol: {
            weapon_attack: "1",
            weapon_ammo: "10",
            weapon_damage: "1d6",
            weapon_encumbrance: "1",
            weapon_range: "100/300",
            weapon_price: "200",
        },
        laser_rifle: {
            weapon_attack: "1",
            weapon_ammo: "20",
            weapon_burst: "true",
            weapon_damage: "1d10",
            weapon_encumbrance: "2",
            weapon_range: "300/500",
            weapon_price: "300",
        },
        mag_pistol: {
            weapon_ammo: "6",
            weapon_damage: "2d6+2",
            weapon_encumbrance: "1",
            weapon_range: "100/300",
            weapon_price: "400",
        },
        mag_rifle: {
            weapon_ammo: "10",
            weapon_damage: "2d8+2",
            weapon_encumbrance: "2",
            weapon_range: "300/600",
            weapon_price: "500",
        },
        medium_advanced_weapon: {
            weapon_attribute_mod: "@{str_dex_mod}",
            weapon_damage: "1d8+1",
            weapon_encumbrance: "1",
            weapon_shock_ac: "13",
            weapon_shock_damage: "2",
            weapon_skill_bonus: "@{skill_stab}",
            weapon_price: "60",
        },
        medium_primitive_weapon: {
            weapon_attribute_mod: "@{str_dex_mod}",
            weapon_damage: "1d6+1",
            weapon_encumbrance: "1",
            weapon_shock_ac: "13",
            weapon_shock_damage: "2",
            weapon_skill_bonus: "@{skill_stab}",
            weapon_price: "20",
        },
        musket: {
            weapon_ammo: "1",
            weapon_damage: "1d12",
            weapon_encumbrance: "2",
            weapon_range: "25/50",
            weapon_price: "30",
        },
        plasma_projector: {
            weapon_attack: "1",
            weapon_ammo: "6",
            weapon_damage: "2d8",
            weapon_encumbrance: "2",
            weapon_range: "50/100",
            weapon_price: "400",
        },
        primitive_bow: {
            weapon_ammo: "1",
            weapon_damage: "1d6",
            weapon_encumbrance: "2",
            weapon_range: "50/75",
            weapon_price: "15",
        },
        punch: {
            weapon_attribute_mod: "@{str_dex_mod}",
            weapon_damage: "1d2",
            weapon_skill_bonus: "@{skill_punch}",
        },
        railgun: {
            weapon_ammo: "20",
            weapon_damage: "3d8",
            weapon_range: "4000/8000",
            weapon_price: "8000",
        },
        revolver: {
            weapon_ammo: "6",
            weapon_damage: "1d8",
            weapon_encumbrance: "1",
            weapon_range: "30/100",
            weapon_price: "50",
        },
        rifle: {
            weapon_ammo: "6",
            weapon_damage: "1d10+2",
            weapon_encumbrance: "2",
            weapon_range: "200/400",
            weapon_price: "75",
        },
        rocket_launcher: {
            weapon_ammo: "1",
            weapon_damage: "3d10",
            weapon_encumbrance: "2",
            weapon_range: "2000/4000",
            weapon_price: "4000",
        },
        semi_auto_pistol: {
            weapon_ammo: "12",
            weapon_damage: "1d6+1",
            weapon_encumbrance: "1",
            weapon_range: "30/100",
            weapon_price: "75",
        },
        shear_rifle: {
            weapon_attack: "1",
            weapon_ammo: "10",
            weapon_burst: "true",
            weapon_damage: "2d8",
            weapon_encumbrance: "2",
            weapon_range: "100/300",
            weapon_price: "600",
        },
        shotgun: {
            weapon_ammo: "2",
            weapon_damage: "3d4",
            weapon_encumbrance: "2",
            weapon_range: "10/30",
            weapon_price: "50",
        },
        small_advanced_weapon: {
            weapon_attribute_mod: "@{str_dex_mod}",
            weapon_damage: "1d6",
            weapon_encumbrance: "1",
            weapon_shock_ac: "15",
            weapon_shock_damage: "1",
            weapon_skill_bonus: "@{skill_stab}",
            weapon_price: "40",
        },
        small_primitive_weapon: {
            weapon_attribute_mod: "@{str_dex_mod}",
            weapon_damage: "1d4",
            weapon_encumbrance: "1",
            weapon_shock_ac: "15",
            weapon_shock_damage: "1",
            weapon_skill_bonus: "@{skill_stab}",
        },
        sniper_rifle: {
            weapon_ammo: "1",
            weapon_damage: "2d8",
            weapon_encumbrance: "2",
            weapon_range: "1000/2000",
            weapon_price: "400",
        },
        spike_thrower: {
            weapon_ammo: "15",
            weapon_burst: "true",
            weapon_damage: "3d8",
            weapon_encumbrance: "2",
            weapon_range: "20/40",
            weapon_price: "600",
        },
        stun_baton: {
            weapon_attribute_mod: "@{str_dex_mod}",
            weapon_damage: "1d8",
            weapon_encumbrance: "1",
            weapon_shock_ac: "15",
            weapon_shock_damage: "1",
            weapon_skill_bonus: "@{skill_stab}",
            weapon_price: "75",
        },
        submachine_gun: {
            weapon_ammo: "20",
            weapon_burst: "true",
            weapon_damage: "1d8",
            weapon_encumbrance: "1",
            weapon_range: "30/100",
            weapon_price: "200",
        },
        suit_ripper: {
            weapon_attribute_mod: "@{str_dex_mod}",
            weapon_damage: "1d6",
            weapon_encumbrance: "1",
            weapon_skill_bonus: "@{skill_stab}",
            weapon_price: "75",
        },
        thermal_pistol: {
            weapon_attack: "1",
            weapon_ammo: "5",
            weapon_damage: "2d6",
            weapon_encumbrance: "1",
            weapon_range: "25/50",
            weapon_price: "300",
        },
        thunder_gun: {
            weapon_attack: "1",
            weapon_ammo: "6",
            weapon_damage: "2d10",
            weapon_encumbrance: "2",
            weapon_range: "100/300",
            weapon_price: "1000",
        },
        void_carbine: {
            weapon_ammo: "10",
            weapon_damage: "2d6",
            weapon_encumbrance: "2",
            weapon_range: "100/300",
            weapon_price: "400",
        },
        vortex_cannon: {
            weapon_ammo: "5",
            weapon_damage: "5d12",
            weapon_range: "1000/2000",
            weapon_price: "75000",
        },
        wheatcutter_belt: {
            weapon_ammo: "5",
            weapon_damage: "2d12",
            weapon_range: "10/20",
            weapon_price: "1000",
        },
    },
};
