/**
 * @typedef Roll20Event
 * @type {object}
 * @property {string} sourceAttribute - The attribute name of the change; undefined for button events.
 * @property {string} triggerName - The name of the trigger including the trigger type. E.g. `change:attribute_name` or `clicked:button-name`
 * @property {string} sourceType - Who made the change; player (or API) or sheetworker
 * @property {string|number} previousValue - The value of the attribute before the change was made
 * @property {string|number} newValue - What the attribute value was changed to
 * @property {object} removedInfo - The contents of the removed repeating row
 */

/**
 * An object containing arrays of section ids indexed by section (e.g. `{repeating_inventory:['id1','id2']}`). Is auto generated by the PUG side of the kscaffold.
 * @typedef {object} sectionObj
 * @property {...sectionIDS[]} sectionname
 */

/**
 * @typedef {object} expandedCascade
 * @property {...object} itemName - Object with details of how to handle the attribute or button. Attribute names are used as the key with a prefix of `attr_` and button names are used as the key with a prefix of `act_`. Repeating attributes/buttons should use $x or $X in place of an explicit ID. This will be expanded by the scaffold in response to an event.
 * @property {string} itemName.name - The name of the attribute without the `act_` or `attr_` prefix.
 * @property {string} itemName.type - The type of the attribute. Autopopulated from the `type` property from the attribute definition in the PUG.
 * @property {string=} [itemName.listener] - the listener text to be used in a [roll20 event listener](https://wiki.roll20.net/Sheet_Worker_Scripts#Event_listener).
 * @property {string|number} [defaultValue] - The default value of the attribute. Not used for buttons. Autopopulated from the `value` property of the PUG definition of the attribute.
 * @property {string=} [itemName.listenerFunc] - Name of function to call from the [roll20 event listener](https://wiki.roll20.net/Sheet_Worker_Scripts#Event_listener). Is used as a string to call the function from the {@link funcs} object.
 * @property {string} [itemName.initialFunc] - Name of function to call only when the attribute is the change event that triggered the listener.
 * @property {string} [itemName.calculation] - Name of function to call to calculate the value of this attribute.
 * @property {string[]} [itemName.triggeredFuncs] - Array of function names that should be called any time this attribute is changed or affected.
 * @property {...*} [itemName.yourPropertyName] - Additional properties can be added to this setup via the K-Scaffold's PUG interface.
 */