.PHONY: all


all:
	./fileval.py -v template.html Ars_Magica_5th.html --global-namespaces arm5_py_integration.GLOBALS
	./fileval.py -v template.css Ars_Magica_5th.css --global-namespaces arm5_py_integration.GLOBALS

	