.PHONY: all


all: Ars_Magica_5th.html
	./fileval.py template.html Ars_Magica_5th.html --global-namespaces arm5_py_integration.GLOBALS
	./fileval.py template.css Ars_Magica_5th.css --global-namespaces arm5_py_integration.GLOBALS

	