function resetRoll() {
  setAttrs({
    rolling_type: "independent",
    rolling_obstacle: 1,
    rolling_disposition_ability: "will",
    rolling_grind: 1,
    rolling_bl_select: "health",
    rolling_bl_nature_within: "within",
    rolling_trait: 0,
    rolling_trait_option: "forme",
    rolling_persona: 0,
    rolling_channel_nature: 0,
    rolling_nature_within: "within",
    rolling_help: 0,
    rolling_synergy: 0,
    rolling_aid: 0,
    rolling_gearetal: 0,
    rolling_otherdice: 0,
    rolling_othersuccesses: 0,
    rolling_hnt: 0,
    rolling_exhausted: 0,
    rolling_deeper_understanding: 0,
    rolling_du_wise: 0,
    rolling_luck: 0,
    rolling_luck_dice: 0,
    rolling_of_course: 0,
    rolling_oc_wise: 0,
    rolling_failed_dice: 0,
    rolling_beginners_luck_roll: 0,
  })
};