/* global setAttrs:false, getAttrs:false, on:false, getSectionIDs:false, generateRowID:false, getTranslationByKey:false */

import { Abilities } from './Abilities';
const abilities = new Abilities();
abilities.setup();
import { AbilityChecks } from './AbilityChecks';
const abilityChecks = new AbilityChecks();
abilityChecks.setup();
import { Actions } from './Actions';
const actions = new Actions();
actions.setup();
import { Attachers } from './Attachers';
const attachers = new Attachers();
attachers.setup();
import { Attacks } from './Attacks';
const attacks = new Attacks();
attacks.setup();
import { Character } from './Character';
const character = new Character();
character.setup();
import { Equipment } from './Equipment';
const equipment = new Equipment();
equipment.setup();
import { ImportData } from './ImportData';
const importData = new ImportData();
importData.setup();
import { Initialize } from './Initialize';
const initialize = new Initialize();
initialize.setup();
import { Overlay } from './../components/overlay/Overlay';
const overlay = new Overlay();
overlay.setup();
import { Npc } from './Npc';
const npc = new Npc();
npc.setup();
import { ProficiencyBonus } from './ProficiencyBonus';
const proficiencyBonus = new ProficiencyBonus();
proficiencyBonus.setup();
import { Resistances } from './Resistances';
const resistances = new Resistances();
resistances.setup();
import { SavingThrows } from './SavingThrows';
const savingThrows = new SavingThrows();
savingThrows.setup();
import { Settings } from './Settings';
const settings = new Settings();
settings.setup();
import { Spells } from './Spells';
const spells = new Spells();
spells.setup();
import { Psionics } from './Psionics';
const psionics = new Psionics();
psionics.setup();
