/* global setAttrs:false, getAttrs:false, on:false, getSectionIDs:false, generateRowID:false, getTranslationByKey:false */

import { Abilities } from './../components/abilities/Abilities';
const abilities = new Abilities();
abilities.setup();
import { AbilityChecks } from './../components/abilityChecks/AbilityChecks';
const abilityChecks = new AbilityChecks();
abilityChecks.setup();
import { Actions } from './../components/actions/Actions';
const actions = new Actions();
actions.setup();
import { Attachers } from './../components/attachers/Attachers';
const attachers = new Attachers();
attachers.setup();
import { Attacks } from './../components/attacks/Attacks';
const attacks = new Attacks();
attacks.setup();
import { Character } from './../components/character/Character';
const character = new Character();
character.setup();
import { Classes } from './../components/classes/Classes';
const classes = new Classes();
classes.setup();
import { Equipment } from './../components/equipment/Equipment';
const equipment = new Equipment();
equipment.setup();
import { ImportData } from './ImportData';
const importData = new ImportData();
importData.setup();
import { Initialize } from './Initialize';
const initialize = new Initialize();
initialize.setup();
import { Overlay } from './../components/overlay/Overlay';
const overlay = new Overlay();
overlay.setup();
import { Npc } from './../components/npc/Npc';
const npc = new Npc();
npc.setup();
import { ProficiencyBonus } from './../components/proficiencyBonus/ProficiencyBonus';
const proficiencyBonus = new ProficiencyBonus();
proficiencyBonus.setup();
import { Resistances } from './../components/resistances/Resistances';
const resistances = new Resistances();
resistances.setup();
import { SavingThrows } from './../components/savingThrows/SavingThrows';
const savingThrows = new SavingThrows();
savingThrows.setup();
import { Settings } from './../components/settings/Settings';
const settings = new Settings();
settings.setup();
import { Spells } from './../components/spells/Spells';
const spells = new Spells();
spells.setup();
import { Psionics } from './../components/psionics/Psionics';
const psionics = new Psionics();
psionics.setup();
