/**
 * Run this function in the console, and modify as needed
 * for other definitions
 */
function getKeysFromH2h() {
  const keys = new Set();
  Object.entries(H2H).forEach(([name, skill]) => {
    skill.forEach((level) => {
      Object.keys(level).forEach((mod) => {
        keys.add(mod);
      });
    });
  });
  console.log(JSON.stringify([...keys]));
}

const H2H = {
  "hand to hand: basic": [
    { attacks: 4, pull: 2, roll: 2 },
    { parry: 2, dodge: 2 },
    { description: "Kick attack does 1D8 points of damage\n" },
    { attacks: 1 },
    { strike: 1, disarm: 1 },
    { critical: 19 },
    { damage: 2 },
    {
      description:
        "Judo-style body flip/throw; does 1D6 damage, and victim loses initiative and one attack\n",
    },
    { attacks: 1 },
    { pull: 2, roll: 2 },
    { parry: 1, dodge: 1 },
    { strike: 1 },
    { description: "Critical Strike or knockout from behind\n" },
    { damage: 2 },
    { attacks: 1 },
  ],
  "hand to hand: expert": [
    { attacks: 4, pull: 2, roll: 2, description: "kick attack 1D8 damage\n" },
    { parry: 3, dodge: 3, pull: 1 },
    { strike: 2, disarm: 2, description: "can perform a Karate Punch\n" },
    { attacks: 1 },
    { description: "Can perform a Karate Kick, does 2D6 damage\n" },
    { critical: 18 },
    {
      description:
        "W.P. Paired Weapons\nbackhand strike (average, does 1D4 damage)\n",
    },
    {
      description:
        "Body flip/throw; does 1D6 damage, and victim loses initiative and one attack\n",
    },
    { attacks: 1, disarm: 1 },
    { damage: 3 },
    { knockout: 18 },
    { parry: 2, dodge: 2 },
    {
      description: "Critical Strike or knockout from behind (triple damage)\n",
    },
    { attacks: 1 },
    { deathblow: 20 },
  ],
  "hand to hand: martial arts": [
    {
      attacks: 4,
      pull: 3,
      roll: 3,
      description:
        "body flip/throw; does ID6 damage, victim loses initiative and one attack\n",
    },
    {
      parry: 3,
      dodge: 3,
      strike: 2,
      description: "may perform Ka­rate and any hand strike/punch\n",
    },
    {
      initiative: 1,
      description:
        "may perform a Karate-style kick (does 2D6 damage) and any foot strike except Leap Kick\n",
    },
    { attacks: 1 },
    {
      entangle: 2,
      description: "Leap Kick (3D8 damage, but counts as two melee attacks)\n",
    },
    { critical: 18 },
    { disarm: 2, description: "W.P. Paired Weapons\ncan perform Holds\n" },
    { description: "Back flip and back flip escape\n" },
    { attacks: 1 },
    { disarm: 2, description: "Back flip attack\n" },
    { damage: 4, initiative: 1 },
    { parry: 2, dodge: 2 },
    { knockout: 18 },
    { attacks: 1 },
    { deathblow: 20 },
  ],
  "hand to hand: assassin": [
    { attacks: 3, strike: 2, description: "W.P. Paired Weapons\n" },
    { initiative: 1, attacks: 2 },
    { pull: 3, roll: 2, description: "Karate Punch (2D4 damage)\n" },
    { damage: 4, initiative: 1, description: "Karate Kick (2D6 damage)\n" },
    { attacks: 1, throw: 1 },
    {
      parry: 3,
      dodge: 3,
      entangle: 2,
      description: "backhand strike (martial arts 1D6)\n",
    },
    {
      knockout: 17,
      description: "leap kick (3D8 damage, but counts as two melee attacks)\n",
    },
    { attacks: 1, strike_range: 1, initiative: 1 },
    { initiative: 1 },
    { critical: 19 },
    {
      strike: 2,
      throw: 1,
      strike_range: 1,
      description: "can perform back flip attack\n",
    },
    { pull: 2, deathblow: 19 },
    { attacks: 1 },
    { damage: 2, description: "can perform Holds\n" },
    { strike: 2, strike_range: 1 },
  ],
  "hand to hand: commando": [
    {
      attacks: 4,
      horrorfactor: 2,
      description: "W.P. Paired Weapons, body flip/throw, body block/tackle\n",
    },
    {
      initiative: 1,
      strike: 1,
      parry: 2,
      dodge: 2,
      roll: 3,
      pull: 3,
      description:
        "Backward sweep kick, used only against opponents coming up behind the character. Does no damage; it is purely a knockdown attack (same penalties as body flip) but cannot be parried (an opponent can try to dodge it but is -2 to do so)\n",
    },
    {
      initiative: 1,
      disarm: 1,
      description: "Karate punch/strike (does 2D4 damage)\n",
    },
    {
      attacks: 1,
      description:
        "Karate kick (does 2D6). The karate-style kick starts with bringing the knee, folded, up to chest level, then the foot is completely extended\n",
    },
    { dodge_auto: 2, description: "Automatic dodge, all foot strikes\n" },
    { initiative: 1, strike: 1, parry: 1, dodge: 1, flipthrow: 1 },
    { damage: 2, horrorfactor: 1, disarm: 1, dodge_auto: 1, pull: 2 },
    { attacks: 1, flipthrow: 2, roll: 1 },
    { deathblow: 18, pull: 2 },
    { horrorfactor: 2, initiative: 1, strike: 1 },
    { disarm: 1, pull: 1, flipthrow: 2 },
    { damage: 2, parry: 1, dodge: 1, dodge_auto: 2 },
    { attacks: 1 },
    { initiative: 1, description: "Can perform holds\n" },
    { critical: 17 },
  ],
  "hand to hand: aikido": [
    {
      attacks: 4,
      breakfall: 3,
      roll: 2,
      flipthrow: 2,
      pull: 2,
      mod_pp: 1,
      mod_pe: 1,
      description: "+2D6 S.D.C., +1D4 to M.E.\n",
    },
    { initiative: 1, parry: 2, dodge: 2 },
    { disarm: 1, description: "Automatic dodge\n" },
    { attacks: 1, flipthrow: 1 },
    {
      description:
        "Critical body flip/throw on Natural 18-20 (double damage)\n",
    },
    { parry: 1, dodge: 1, flipthrow: 1 },
    { pull: 2, description: "Automatic flip/throw\n" },
    { attacks: 1 },
    { initiative: 1, strike: 1, parry: 1, dodge: 1 },
    { disarm: 1, description: "Double existing P.P.E. (inner spirit)\n" },
    { parry: 1, dodge: 2, flipthrow: 1 },
    { attacks: 1 },
    { initiative: 1, tackle: 2 },
    { critical: 18 },
    { attacks: 1 },
  ],
  "hand to hand: judo": [
    {
      attacks: 4,
      roll: 3,
      pull: 3,
      mod_me: 1,
      mod_pp: 1,
      description:
        "+2D4 S.D.C.\nBody block/tackle, body flip/throw, break fall, disarm, roll with punch/fall/impact, strike, parry, dodge, and pull punch are available at first level.\n",
    },
    { parry: 2, dodge: 2, strike: 1 },
    { flipthrow: 1, tackle: 1, disarm: 1 },
    { attacks: 1, description: "Karate-style kick (2D6 damage).\n" },
    { critical: 19 },
    { strike: 1, parry: 1, dodge: 1, flipthrow: 1 },
    { damage: 2, description: "W.P. Paired Weapons\n" },
    { roll: 1, description: "Jump kick\n" },
    { attacks: 1 },
    { initiative: 2, parry: 1, dodge: 1 },
    { breakfall: 1, disarm: 1 },
    { critical: 18 },
    { damage: 2, knockout: 19 },
    { attacks: 1 },
    { description: "Automatic body flip/throw.\n" },
  ],
  "hand to hand: jujitsu": [
    {
      mod_ps: 2,
      mod_pp: 1,
      attacks: 4,
      roll: 3,
      parry: 2,
      dodge: 2,
      pull: 2,
      description:
        "+3D6 S.D.C.\nsnap kick (1D6 damage), knife hand (2D4 damage)\nMaintain balance, break fall, disarm, body block/tackle, body flip/throw, holds, roll with punch/fall/impact, pull punch, kick attack (2D4 damage), knee and elbow strikes (1D6 damage), and the usual strike, parry and dodge.\n",
    },
    { strike: 1, leghook: 1, backwardsweepkick: 1 },
    { initiative: 1, description: "Critical strike from behind.\n" },
    { attacks: 1, damage: 2 },
    { description: "Palm strike (2D4 damage) and drop kick.\n" },
    { critical: 18 },
    { strike: 1, flipthrow: 1, disarm: 1 },
    { attacks: 1, maintainbalance: 1 },
    { description: "Critical body flip/throw on natural 1 7-20.\n" },
    { description: "Jump kick and leap attacks.\n" },
    { attacks: 1, pull: 2 },
    { initiative: 1, parry: 1, dodge: 1, strike: 1 },
    { damage: 2, pull: 2, breakfall: 2 },
    { attacks: 1 },
    { description: "Death blow!\n" },
  ],
  "hand to hand: karate": [
    {
      mod_pe: 2,
      mod_spd: 2,
      attacks: 4,
      initiative: 1,
      roll: 2,
      parry: 2,
      dodge: 1,
      breakfall: 1,
      pull: 2,
      description:
        "+3D6 S.D.C., +1D4 to P.S.\nBreak fall, body block/tackle, roll with punch/fall/impact, pull punch, kick at­tack (2D4 damage), karate kick (2D6 damage), karate punch (2D4 damage), knees and elbow strikes (1D6 damage), and the usual strike, parry and dodge.\n",
    },
    { strike: 1, leghook: 1, backwardsweepkick: 1 },
    { attacks: 1, damage: 2 },
    {
      initiative: 1,
      disarm: 1,
      description: "roundhouse kick (3D6 damage).\n",
    },
    { description: "Power punch and palm strike (2D4 damage).\n" },
    { attacks: 1, pull: 2 },
    {
      strike: 1,
      parry: 1,
      breakfall: 1,
      description: "Power kick, wheel kick\n",
    },
    {
      critical: 18,
      deathblow: 20,
      description: "critical strike from behind.\n",
    },
    { attacks: 1, damage: 2 },
    { description: "Jump kick and leap attacks.\n" },
    { initiative: 1, parry: 1, dodge: 1, strike: 1 },
    { attacks: 1, pull: 2 },
    { description: "Death Blow!\n" },
    { damage: 2, pull: 2, breakfall: 2 },
    { attacks: 1 },
  ],
  "hand to hand: kendo": [
    {
      mod_ps: 1,
      mod_pp: 1,
      mod_spd: 2,
      attacks: 4,
      initiative: 1,
      roll: 2,
      disarm: 1,
      parry: 1,
      dodge: 1,
      breakfall: 1,
      pull: 2,
      description:
        "+2D4 S.D.C.\n+2 to parry with sword or staff (in addition to W.P. bonuses)\nDisarm, break fall, roll with punch/fall/impact, pull punch, karate punch (2D4 damage), kick attack (2D4), knees and elbow strikes (1D6 damage), and the usual strike, parry and dodge.\n",
    },
    { strike: 1, description: "W.P. Paired Weapons\n" },
    { attacks: 1, damage: 2 },
    { initiative: 1, disarm: 1, parry: 1 },
    { description: "Tripping/leg hook and backward sweep kicks.\n" },
    { description: "Power punch and palm strike (2D4 damage).\n" },
    { attacks: 1, pull: 2 },
    {
      critical: 18,
      deathblow: 19,
      description: "critical strike from behind\n",
    },
    { attacks: 1, damage: 4 },
    { description: "Automatic dodge.\n" },
    { initiative: 1, strike: 1, breakfall: 2 },
    { attacks: 1, pull: 2 },
    { description: "Jump kick and leap attacks.\n" },
    { description: "Death Blow!\n" },
    { attacks: 1 },
  ],
  "hand to hand: ninjitsu": [
    {
      mod_ma: 2,
      mod_ps: 1,
      mod_pe: 1,
      mod_pp: 1,
      mod_spd: 4,
      attacks: 4,
      roll: 2,
      initiative: 2,
      parry: 1,
      dodge: 2,
      pull: 2,
      description:
        "snap kick (1D6 dam­age), knife hand (2D4 damage)\nW.P. Paired Weapons\nMaintain balance, back flip, body block/tackle, body flip/throw, holds, roll with punch/fall/impact, pull punch, drop kick, kick attack (2D4 damage), knee and elbow strikes (1D6 damage), paired weapons, and the usual strike, parry and dodge. Also see Samurai Hand to Hand combat.",
    },
    {
      strike: 1,
      description:
        "cartwheel (attack), back flip (escape), back flip (defensive), and back flip (attack).\n",
    },
    { attacks: 1, description: "palm strike (2D4 damage).\n" },
    {
      description:
        "Leap attack, axe kick, and +2 to strike when performing any backflip or cartwheel.\n",
    },
    { description: "Tripping/leg hook and backward sweep kicks\n", damage: 2 },
    { attacks: 1, description: "roundhouse kick (3D6).\n" },
    { critical: 18, deathblow: 20, description: "Critical from behind.\n" },
    { initiative: 1, strike: 1, parry: 1, roll: 1, maintainbalance: 2 },
    { description: "Death Blow!\n" },
    { attacks: 1, pull: 2 },
    { description: "Double existing P.P.E. (inner spirit)!\n" },
    { initiative: 1, roll: 2 },
    { damage: 2, disarm: 1 },
    { damage: 2, description: "Jump kick, +2 to back flip/cartwheel\n" },
    { attacks: 1 },
  ],
  "hand to hand: samurai": [
    {
      mod_me: 2,
      mod_pp: 2,
      mod_pe: 1,
      attacks: 4,
      initiative: 2,
      roll: 2,
      dodge: 3,
      damage: 2,
      pull: 2,
      description:
        "+3D6 S.D.C.\n+2 to parry with sword or staff (in addition to W.P. bonuses)\nDisarm, maintain balance, roll with punch/fall/im­ pact, pull punch, Karate punch (2D4 damage), kick attack (2D4), knee and elbow strikes (1D6 damage), and the usual strike, parry and dodge.\n",
    },
    { attacks: 1, disarm: 1, maintainbalance: 1 },
    {
      initiative: 1,
      strike: 1,
      parry: 1,
      deathblow: 20,
      description: "critical strike from behind\n",
    },
    { attacks: 1, damage: 2 },
    { critical: 18, maintainbalance: 1 },
    { roll: 1, dodge: 1, maintainbalance: 1 },
    {
      description:
        "Power punch/stab (with hand or sword), jump kick and backward sweep kick.\n",
    },
    { attacks: 1, dodge: 1 },
    { description: "Death Blow!\n" },
    { initiative: 1, horrorfactor: 1, maintainbalance: 1 },
    { attacks: 1 },
    {
      damage: 2,
      horrorfactor: 1,
      description:
        'the knowledge and skill to create a "true" samurai sword.\n',
    },
    { attacks: 1 },
    { disarm: 1, description: "Double existing P.P.E. (inner spirit)\n" },
    { attacks: 1 },
  ],
  "hand to hand: teng-jutsu": [
    {
      attacks: 4,
      dodge: 2,
      pull: 2,
      disarm: 1,
      roll: 1,
      maintainbalance: 3,
      breakfall: 1,
      description:
        "Break fall, roll with punch/fall/impact, maintain balance, back flip escape, back flip attack, cartwheel (attack), body block/tackle, pull punch, kick attack (2D4 damage), karate kick (2D6 damage), karate punch (2D4 damage), knees and elbow strikes (1D6 damage), and the usual strike, parry and dodge, plus the Tengu special mystic martial art powers.\n",
    },
    {
      initiative: 1,
      description: "Drop kick, +2 on all back flips.\n",
    },
    { strike: 1, disarm: 1, description: "+1 to leap dodge." },
    { attacks: 1 },
    {
      description:
        "Critical strike from all kicks (double damage) and jump kick and leap attacks.\n",
    },
    { roll: 1, pull: 2, description: "+ 1 to leap dodge.\n" },
    {
      initiative: 1,
      description: "tripping/leg hook and backward sweep kicks.\n",
    },
    { attacks: 1 },
    {
      disarm: 2,
      description: "+1 on all back flips, and +1 on cartwheel attack.\n",
    },
    { initiative: 1, parry: 1, description: "Axe kick\n" },
    { attacks: 1 },
    { disarm: 1, description: "+1 to leap dodge\n" },
    { description: "Snap kick and wheel kick.\n" },
    { pull: 1, description: "+1 to leap dodge\n" },
    { attacks: 1 },
  ],
  "hand to hand: drunken style kung fu": [
    {
      attacks: 3,
      roll: 2,
      knockout: 19,
      critical: 19,
      description:
        "Drunken Style Foot Play\nDrunken Style Controlled Staggering\n+2 to somersault/stagger/roll/backflip\nCritical Strike from behind\n",
    },
    {
      dodge: 2,
      dodge_auto: 2,
      pull: 2,
    },
    { strike: 1, initiative: 1 },
    { description: "Faked Alcohol Sickness\n" },
    { attacks: 1 },
    { strike: 1 },
    { disarm: 2, entangle: 2 },
    { description: "Projectile Vomit\n" },
    { attacks: 1 },
    { roll: 2, pull: 1 },
    { description: "Joint Twisting\n" },
    { dodge: 1, dodge_auto: 1, strike: 1 },
    { roll: 2, pull: 1 },
    { attacks: 1 },
    { damage: 1, knockout: 17 },
  ],
  "hand to hand: dragon": [
    {
      attacks: 3,
      roll: 2,
      pull: 1,
      description:
        "Instinctively knows the following attack types: Bite, punch, kick, Claw Swipe, and standard use of breath weapon (counts as one melee attack). Dragon metamor­phosis takes one full melee (15 seconds).\n",
    },
    {
      parry: 2,
      dodge: 2,
      description: "Tail Slap, Wing At­tack: Basic, and Crush\n",
    },
    {
      damage: 2,
      description:
        "Dragon metamorphosis takes half a melee round (7 sec­onds), and Tail Slap Power Strike\n",
    },
    { attacks: 1, description: "Bite & Grip, and Tail Sweep\n" },
    { strike: 1, parry: 1, dodge_flight: 2, description: "Tail Parry\n" },
    {
      mod_spellstrength: 1,
      description: "gains the Wing Sweep and Grappling Hold.\n",
    },
    { disarm: 2, entangle: 2, pull: 2, description: "Wing Attack: Advanced\n" },
    {
      attacks: 1,
      strike: 1,
      parry: 1,
      dodge_flight: 1,
      description: "Wing Gliding Sweep Attack\n",
    },
    {
      roll: 1,
      pull: 1,
      description:
        "Gains Breath Weapon Concentrated Beam, and an additional +5% to Dimensional Teleport (a natural ability).\n",
    },
    { initiative: 1, critical: 19, description: "Teleport Dodge\n" },
    { damage: 2, dodge_flight: 2, mod_spellstrength: 1 },
    { attacks: 1, strike: 1, dodge_teleport: 1 },
    { initiative: 1, description: "Breath Weapon Cone\n" },
    { dodge_teleport: 1, pull: 1 },
    { mod_spellstrength: 1, description: "+ 1D4x10 to M.D.C\n" },
    { attacks: 1, damage: 2 },
    { dodge_teleport: 1, dodge_flight: 1 },
    { strike: 1, parry: 1, description: "+ 1 to Spell Strength\n" },
    {
      dodge_teleport: 1,
      disarm: 1,
      roll: 1,
      description: "+1D4x10 to physical M.D.C.\n",
    },
    { attacks: 1 },
  ],
  "rpa combat: basic": [
    {
      attacks: 1,
      strike: 1,
      parry: 1,
      dodge: 1,
      roll: 1,
      description:
        "Power Armor Body Block/Tackle/Ram: 1D4 M.D. plus a 01-50% chance of knocking an opponent down, causing him to lose initiative and one melee attack/action. Counts as two of the power armor's melee attacks.\n" +
        "Robot Body Block/Tackle/Ram: M.D. equal to Robot Punch M.D. plus a 01-60% chance of knocking down an opponent that is approxi­ mately the same size or larger. Increase the odds of knocking down an opponent that is half the size or smaller than the robot to 0 1 -80%. The victim suffers M.D. and loses initiative and two melee attacks/actions. Counts as two ofthe robot's melee attacks.\n",
    },
  ],
  "rpa combat: flying power armor": [
    {
      attacks: 1,
      initiative: 2,
      strike_range: 2,
      strike: 2,
      parry: 2,
      dodge: 2,
      dodge_flight: 5,
      disarm: 2,
      pull: 3,
      roll: 4,
      description:
        "Punch Damage: As per Robot (or Augmented) P.S.\nPower Punch: Double damage, but counts as two melee attacks. Tear or Pry with Hands: 1D4 M.D.\nKick Damage: As per Robot (or Augmented) P.S.\nBody B1ock/Ram: Equal to the Robot P.S. punch damage.\nFull Speed Running Ram: Double Robot P.S. punch damage, plus 01-60% likelihood of knocking an opponent off his feet if the opponent is the same size or smaller (reduce by half if twice as big). Victim takes M.D. and is knocked off his feet, losing initiative and two melee at­tacks/actions.\n",
    },
    {},
    { attacks: 1 },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
  ],
  "rpa combat: ground-based power armor": [
    {
      attacks: 1,
      initiative: 1,
      strike_range: 2,
      strike: 3,
      parry: 2,
      dodge: 2,
      disarm: 3,
      pull: 3,
      roll: 2,
      description:
        "Punch Damage: As per Robot (or Augmented) P.S.\nPower Punch: Double damage, but counts as two melee attacks.\nTear or Pry with Hands: 1D4 M.D.\nKick Damage: As per Robot (or Augmented) P.S.\nBody B1ock/Ram: Equal to the Robot P.S. punch damage.\nFull Speed Running Ram: Double Robot P.S. punch damage, plus 01-50% likelihood of knocking an opponent off his feet if the opponent is the same size or smaller (reduce by half if twice as big). Victim takes M.D. and is knocked off his feet, losing initiative and two melee at­tacks/actions.\n",
    },
    {},
    { attacks: 1 },
    {},
    { attacks: 1 },
    {},
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    {},
    { attacks: 1 },
  ],
  "rpa combat: heavy vehicular style robots": [
    {
      attacks: 1,
      initiative: 1,
      strike_range: 3,
      strike: 1,
      parry: 1,
      dodge: 1,
      dodge_motion: 2,
      roll: 1,
      description:
        "Punch/Kick Damage: As per Robot P.S.\n" +
        "Power Punch/Kick: Double damage, but counts as two melee attacks.\n" +
        "Kick Damage: As per Robot P.S.\n" +
        "Body Block/Ram: Equal to the Robot P.S. punch damage.\n" +
        "Full Speed Running Ram: Triple the Robot P.S. punch damage, plus 01-80% likelihood of knocking opponent off his feet if the opponent is the same size or smaller. Victim takes M.D. and is knocked off his feet, losing initiative and two melee attacks/actions.\n" +
        "Stomp: 1D6 M.D.; effective only against objects smaller than one third the robot's total height.\n",
    },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
  ],
  "rpa combat: heavy ground robots": [
    {
      attacks: 1,
      initiative: 1,
      strike_range: 1,
      strike: 2,
      parry: 3,
      dodge: 1,
      dodge_motion: 2,
      disarm: 1,
      pull: 2,
      roll: 3,
      description:
        "Punch Damage: As per Robot P.S.\n" +
        "Power Punch: Double damage, but counts as two melee attacks.\n" +
        "Tear or Pry with Hands: 1D6 M.D.\n" +
        "Kick Damage: As per Robot P.S.\n" +
        "Body Block/Ram: Equal to the Robot P.S. punch damage.\n" +
        "Full Speed Running Ram: Double the Robot P.S. punch damage, plus 01-85% likelihood of knocking opponent off his feet if the opponent is the same size or smaller. Victim takes M.D. and is knocked off his feet, losing initiative and two melee attacks/actions.\n" +
        "Stomp: 1D6 M.D.; effective only against objects smaller than one third the robot's total height.\n",
    },
    {},
    { attacks: 1 },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    {},
    { attacks: 1 },
  ],
  "rpa combat: light ground robots": [
    {
      attacks: 1,
      initiative: 2,
      strike_range: 1,
      strike: 3,
      parry: 3,
      dodge: 2,
      dodge_motion: 3,
      disarm: 2,
      pull: 4,
      roll: 4,
      description:
        "Punch Damage: As per Robot P.S.\n" +
        "Power Punch: Double damage, but counts as two melee attacks.\n" +
        "Tear or Pry with Hands: 1D4 M.D.\n" +
        "Kick Damage: As per Robot P.S.\n" +
        "Body Block/Ram: Equal to the Robot P.S. punch damage.\n" +
        "Full Speed Running Ram: Double the Robot P.S. punch damage, plus 01-70% likelihood of knocking opponent off his feet if the opponent is the same size or smaller. Victim takes M.D. and is knocked off his feet, losing initiative and two melee attacks/actions.\n" +
        "Stomp: 1D4 M.D.; effective only against objects smaller than one third the robot's total height.\n",
    },
    {},
    { attacks: 1 },
    {},
    { attacks: 1 },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
  ],
  "rpa combat: glitter boy": [
    {
      attacks: 2,
      initiative: 2,
      strike_range: 2,
      strike: 2,
      parry: 2,
      dodge: 2,
      disarm: 1,
      pull: 4,
      roll: 3,
      description:
        "Punch Damage: 1D4 M.D. on a restrained punch, 1D6 M.D. on a full strength punch.\n" +
        "Power Punch: 2D6 M.D., but counts as two melee attacks.\n" +
        "Kick Damage: 2D4 M.D., Power Kick is not possible.\n" +
        "Running Leap Kick: 4D6 M.D., but counts as three attacks.\n" +
        "Tear or Pry with Hands (Special): 1D6 M.D.\n" +
        "Body BlocklRam: 2D4 M.D.\n" +
        "Full Speed Running Ram: 3D6 M.D., but this attack uses up three melee actions.\n" +
        "Stomp: 1D6 M.D.; effective only against objects smaller than three feet (0.9 m) tall.\n" +
        "Pylon Impalement: 1D6 M.D., not very useful in most combat situa­tions.\n",
    },
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    {},
  ],
  "rpa combat: silverhawk": [
    {
      strike: 2,
      parry: 4,
      dodge: 4,
      dodge_flight: 6,
      roll: 3,
      pull: 2,
      attacks: 2,
      description:
        "Restrained Punch - 1D6 M.D.\n" +
        "Full Strength Punch - 3D6 M.D.\n" +
        "Power Punch - 6D6 M.D. (counts as two attacks) Kick - 4D6 M.D.\n" +
        "Leap Kick - 6D6 +3 (counts as two attacks) Body Block/Ram (on the ground) - 2D6 M.D.\n" +
        "Body Block/Ram (flying) - 4D6 M.D.\n",
    },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
  ],
  "rpa combat: battleram": [
    {
      strike: 1,
      parry: 1,
      dodge_flight: 1,
      description:
        "Restrained Punch - 4D6 M.D.\n" +
        "Full Strength Punch - 2D6x10 M.D.\n" +
        "Power Punch - 4D6x10 M.D. (counts as two attacks)\n" +
        "Crush, Pry or Tear - 2D6x10 M.D.\n" +
        "Kick - 3D4x10 M.D.\n" +
        "Leap Kick (only while flying) - 4D6x10 M.D.\n" +
        "Body Flip/Throw - 4D6 M.D.\n" +
        "Body BlocklRam (on the ground ) - 2D4x10 M.D.\n" +
        "Flying Ram - 5D6x10 M.D.\n" +
        "Stomp - 6D6 M.D. against targets 15 feet (4.5 m) tall or smaller.\n",
    },
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
  ],
  "rpa combat: bombard": [
    {
      strike: 2,
      parry: 4,
      dodge: 2,
      roll: 3,
      pull: 4,
      attacks: 2,
      description:
        "Restrained Punch - 1D6 M.D.\n" +
        "Full Strength Punch - 2D6 M.D.\n" +
        "Power Punch - 4D6 M.D. (counts as two attacks) Vibro-blade - 4D6 M.D.\n" +
        "Crush, Pry or Tear - 1D6 M.D.\n" +
        "Kick - 2D6 M.D.\n" +
        "Body Flip/Throw - 1D6 M.D.\n" +
        "Body Block/Ram - 2D4 M.D.\n" +
        "Stomp - 2D4 M.D. against man-sized targets\n",
    },
    {},
    {},
    { attacks: 1 },
    {},
    { attacks: 1 },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
  ],
  "space fighter: basic": [
    {
      attacks: 1,
      strike_range: 2,
      dodge_flight: 3,
      description:
        "+1 to dog-fighting rolls\n" +
        "Critical strike, same as pilot's hand to hand.\n",
    },
    {},
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    {},
  ],
  "space fighter: elite": [
    {
      attacks: 2,
      strike_range: 2,
      dodge_flight: 5,
      description:
        "+3 to dog-fighting rolls\n" +
        "Critical strike, same as pilot's hand to hand.\n",
    },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    {},
    {},
  ],
};

const H2H_KEYS = [
  "name",
  "levelacquired",
  "level",
  "attacks",
  "pull",
  "roll",
  "breakfall",
  "parry",
  "dodge",
  "description",
  "strike",
  "disarm",
  "critical",
  "damage",
  "knockout",
  "deathblow",
  "initiative",
  "entangle",
  "throw",
  "strike_range",
  "horrorfactor",
  "dodge_auto",
  "flipthrow",
  "tackle",
  "leghook",
  "backwardsweepkick",
  "maintainbalance",
  "dodge_flight",
  "dodge_teleport",
  "dodge_motion",
  "mod_spellstrength",
  "mod_me",
  "mod_ma",
  "mod_ps",
  "mod_pp",
  "mod_pe",
  "mod_spd",
];

const WP = {
  "w.p. archery": [
    { strike: 1, parry: 1, rof: 2 },
    { strike: 1, disarm: 1, rof: 1 },
    {},
    { strike: 1, rof: 1 },
    { disarm: 1, rof: 1 },
    { strike: 1 },
    {},
    { strike: 1, rof: 1 },
    {},
    { strike: 1, disarm: 1, rof: 1 },
    {},
    { strike: 1, rof: 1 },
    {},
    { strike: 1, rof: 1 },
    { disarm: 1 },
  ],
  "w.p. axe": [
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
  ],
  "w.p. bayonet": [
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    {},
  ],
  "w.p. blunt": [
    { strike: 1, parry: 1 },
    {},
    { strike: 1, parry: 1 },
    {},
    { throw: 1 },
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    { throw: 1 },
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    { throw: 1 },
  ],
  "w.p. chain": [
    { strike: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    { strike: 1 },
    {},
    { parry: 1 },
    { strike: 1 },
    {},
    {},
  ],
  "w.p. forked": [
    { strike: 1, parry: 1, entangle: 1 },
    {},
    { strike: 1, parry: 1, entangle: 1 },
    { throw: 1 },
    { strike: 1, entangle: 1 },
    { parry: 1 },
    {},
    { strike: 1, entangle: 1 },
    {},
    { parry: 1, throw: 1 },
    { strike: 1, entangle: 1 },
    {},
    { strike: 1, parry: 1, entangle: 1 },
    {},
    { throw: 1 },
  ],
  "w.p. knife": [
    { parry: 1, throw: 1 },
    { strike: 1 },
    { parry: 1, throw: 1 },
    { strike: 1 },
    {},
    { parry: 1, throw: 1 },
    { strike: 1 },
    { throw: 1 },
    { parry: 1 },
    { strike: 1, throw: 1 },
    {},
    { parry: 1 },
    { strike: 1, throw: 1 },
    {},
    {},
  ],
  "w.p. grappling hook": [
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    {},
  ],
  "w.p. pole arm": [
    { strike: 1, parry: 1 },
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    {},
    { throw: 1 },
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    {},
  ],
  "w.p. rope": [
    { strike: 1, entangle: 1, disarm: 1 },
    {},
    {},
    { strike: 1 },
    {},
    {},
    {},
    { strike: 1 },
    {},
    {},
    {},
    { strike: 1 },
    {},
    {},
    { strike: 1 },
  ],
  "w.p. shield": [
    { parry: 1 },
    {},
    { parry: 1 },
    { strike: 1 },
    {},
    {},
    { parry: 1 },
    { strike: 1 },
    {},
    { parry: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    {},
  ],
  "w.p. spear": [
    { strike: 1, parry: 1 },
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    { throw: 1 },
    {},
    { strike: 1, parry: 1 },
    {},
    { throw: 1 },
    {},
  ],
  "w.p. staff": [
    { strike: 1 },
    { parry: 1 },
    { strike: 1 },
    {},
    { parry: 1, throw: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    { strike: 1, throw: 1 },
    { parry: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    { throw: 1 },
  ],
  "w.p. sword": [
    { strike: 1 },
    { parry: 1 },
    { strike: 1 },
    { parry: 1, throw: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    { throw: 1 },
    { strike: 1 },
    { parry: 1 },
    {},
    { strike: 1, throw: 1 },
    { parry: 1 },
    {},
    { strike: 1 },
  ],
  "w.p. targeting": [
    { throw: 1 },
    {},
    { throw: 1 },
    {},
    {},
    {},
    { throw: 1 },
    {},
    {},
    { throw: 1 },
    {},
    {},
    {},
    {},
    {},
  ],
  "w.p. whip": [
    {},
    { strike: 1, entangle: 1, disarm: 1, damage: 1 },
    {},
    { strike: 1, entangle: 1, disarm: 1, damage: 1 },
    {},
    {},
    { strike: 1, entangle: 1, disarm: 1 },
    { damage: 1 },
    {},
    { strike: 1, entangle: 1, disarm: 1 },
    {},
    { damage: 1 },
    { strike: 1, entangle: 1, disarm: 1 },
    {},
    {},
  ],
  "w.p. handguns": [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
  ],
  "w.p. rifles": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    {},
  ],
  "w.p. energy heavy": [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
  ],
  "w.p. energy pistol": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
  ],
  "w.p. energy rifle": [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
  ],
  "w.p. heavy": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    {},
    { strike_range_single: 1 },
    {},
  ],
  "w.p. speargun": [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    {},
    {},
    { strike_range_single: 1 },
  ],
  "w.p. shotgun": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    {},
    { strike_range_single: 1 },
    {},
  ],
  "w.p. submachinegun": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
  ],
  "w.p. flamethrower": [
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
  ],
};

const WP_KEYS = {
  wp: [
    "name",
    "levelacquired",
    "level",
    "strike",
    "parry",
    "disarm",
    "rof",
    "throw",
    "entangle",
  ],
  wpmodern: [
    "name",
    "levelacquired",
    "level",
    "strike_range_single",
    "disarm",
    "strike_range_burst",
  ],
};

const ATTRIBUTE_KEYS = [
  "mod_iq",
  "iq_abs",
  "mod_iq_bonus",
  "mod_perception_bonus",
  "mod_me",
  "mod_me_bonus",
  "me_abs",
  "mod_ma",
  "mod_ma_bonus",
  "ma_abs",
  "mod_ps",
  "mod_ps_bonus",
  "ps_abs",
  "mod_pp",
  "mod_pp_bonus",
  "pp_abs",
  "mod_pe",
  "mod_pe_bonus",
  "mod_pe_coma_bonus",
  "pe_abs",
  "mod_pb",
  "mod_pb_bonus",
  "pb_abs",
  "mod_spd",
  "spd_abs",
  "mod_spdfly",
  "spdfly_abs",
  "mod_character_ps_type",
  "mod_character_ps_type_name",
  "mod_restrained_punch",
  "mod_restrained_punch_unit",
  "mod_punch",
  "mod_punch_unit",
  "mod_power_punch",
  "mod_power_punch_unit",
  "mod_kick",
  "mod_kick_unit",
  "mod_leap_kick",
  "mod_leap_kick_unit",
  "mod_liftcarry_weight_multiplier",
  "mod_liftcarry_duration_multiplier",
  "mod_lift",
  "mod_carry",
  "mod_throw_distance",
  "mod_carry_max",
  "mod_carry_running",
  "mod_hold_max",
  "hp",
  "sdc",
  "ar",
  "mdc",
  "ps_type",
  "ppe",
  "isp",
  "mod_hf",
  "hf_abs",
  "mod_spellstrength",
  "spellstrength_abs",
  "mod_trust",
  "trust_abs",
  "mod_intimidate",
  "intimidate_abs",
  "mod_charmimpress",
  "charmimpress_abs",
  "mod_skillbonus",
];

const COMBAT_KEYS = [
  // "selection_id",
  "name",
  "level",
  "attacks",
  "sdc",
  "mdc",
  "initiative",
  "strike",
  "parry",
  "dodge",
  "throw",
  "disarm",
  "entangle",
  "pull",
  "roll",
  "breakfall",
  "damage",
  "damage_paired",
  "damage_mainhand",
  "damage_offhand",
  "dodge_flight",
  "dodge_auto",
  "dodge_teleport",
  "dodge_motion",
  "dodge_underwater",
  "strike_range",
  "strike_range_single",
  "strike_range_burst",
  "strike_range_aimed",
  "strike_range_aimed_single",
  "strike_range_aimed_pulse",
  "strike_range_called",
  "strike_range_called_single",
  "strike_range_called_pulse",
  "strike_range_aimed_called_single",
  "strike_range_aimed_called_pulse",
  "disarm_range",
  "damage_range",
  "damage_range_single",
  "damage_range_burst",
  "critical",
  "knockout",
  "deathblow",
  "flipthrow",
  "tackle",
  "leghook",
  "backwardsweepkick",
  "description",
];
const SAVE_KEYS_ATTRIBUTE_BONUSES = {
  me_bonus: ["psionics", "insanity"],
  pe_bonus: ["magic", "lethalpoison", "nonlethalpoison", "disease", "drugs"],
  pe_coma_bonus: ["comadeath"],
  perception_bonus: ["perceptioncheck"],
  none: [
    "pain",
    "horrorfactor",
    "mindcontrol",
    "illusions",
    "possession",
    "curses",
    "maintainbalance",
    "fatigue",
    "despair",
    "telepathicprobes",
  ],
};
const SAVE_KEYS = Object.values(SAVE_KEYS_ATTRIBUTE_BONUSES).reduce(
  (acc, cur) => acc.concat(cur),
  []
);
const REPEATING_MOVEMENT_KEYS = [
  "run_mph",
  "run_kmh",
  "fly_mph",
  "fly_kmh",
  "run_ft_melee",
  "run_m_melee",
  "fly_ft_melee",
  "fly_m_melee",
  "run_ft_action",
  "run_m_action",
  "fly_ft_action",
  "fly_m_action",
];
const REPEATING_BONUS_KEYS = COMBAT_KEYS.concat(
  SAVE_KEYS,
  ATTRIBUTE_KEYS,
  REPEATING_MOVEMENT_KEYS
);
const SKILL_KEYS = [
  "name",
  "category",
  "base",
  "bonus",
  "perlevel",
  "levelacquired",
  "level",
  "total",
  "description",
];

const ABILITIES_REPEATERS = ["magic", "psionics", "powersabilities"];

const MAGIC_KEYS = REPEATING_BONUS_KEYS.concat([
  "name",
  "school",
  "spell_level",
  "range",
  "damage",
  "duration",
  "percentage",
  "ppecost",
  "range_starting",
  "range_per_level",
  "range_unit",
  "damage_starting",
  "damage_per_level",
  "damage_unit",
  "dc_starting",
  "dc_per_level",
  "dc_unit",
  "duration_starting",
  "duration_per_level",
  "duration_unit",
  "percentage_starting",
  "percentage_per_level",
  "addtobonuses",
  "description",
]);

const PSIONICS_KEYS = REPEATING_BONUS_KEYS.concat([
  "name",
  "range",
  "damage",
  "duration",
  "percentage",
  "ispcost",
  "range_starting",
  "range_per_level",
  "range_unit",
  "damage_starting",
  "damage_per_level",
  "damage_unit",
  "dc_starting",
  "dc_per_level",
  "dc_unit",
  "duration_starting",
  "duration_per_level",
  "duration_unit",
  "percentage_starting",
  "percentage_per_level",
  "addtobonuses",
  "description",
]);

const ABILITIES_KEYS = REPEATING_BONUS_KEYS.concat([
  "name",
  "range",
  "damage",
  "duration",
  "percentage",
  "range_starting",
  "range_per_level",
  "range_unit",
  "damage_starting",
  "damage_per_level",
  "damage_unit",
  "dc_starting",
  "dc_per_level",
  "dc_unit",
  "duration_starting",
  "duration_per_level",
  "duration_unit",
  "frequency_starting",
  "frequency_per_level",
  "frequency_unit",
  "percentage_starting",
  "percentage_per_level",
  "addtobonuses",
  "description",
]);

const PROFILES_KEYS = REPEATING_BONUS_KEYS.concat(["bonus_ids", "bonus_names"]);

const CORE_KEYS = [
  "character_name",
  "truename_name",
  "character_race",
  "occ",
  "character_ps_type",
  "character_level",
  "experience",
  "alignment",
  "character_age",
  "character_gender",
  "character_height",
  "character_weight",
  "character_familyorigin",
  "character_environment",
  "character_languages",
  "character_insanity",
  "character_disposition",
  "iq",
  "iq_bonus",
  "perception_bonus",
  "me",
  "me_bonus",
  "ma",
  "ma_bonus",
  "ps",
  "ps_bonus",
  "pp",
  "pp_bonus",
  "pe",
  "pe_bonus",
  "pe_coma_bonus",
  "pb",
  "pb_bonus",
  "spd",
  "spdfly",
  "charmimpress",
  "character_hp",
  "character_sdc",
  "character_ar",
  "character_mdc",
  "character_ppe",
  "character_isp",
  "hf",
  "spellstrength",
  "perception",
  "run_mph",
  "run_ft_melee",
  "run_ft_attack",
  "run_cruising",
  "run_at_max",
  "leapup",
  "leapout",
  "equipment",
  "psionic_ability",
  "credits_universal_bearer",
  "credits_universal_marked",
  "credits_blackmarket",
  "credits_ngmi",
  "credits_phaseworld",
  "credits_splugorth",
  "credits_gems",
  "credits_blackmarketmerchandise",
];

const ARMOR_KEYS = ["is_active", "name", "movementpenalty", "mdc", "mdc_max"];

const MOVEMENT_KEYS = ["name", "mph", "ft_melee", "cruising", "dur_at_max"];

const EQUIPMENT_KEYS = ["equipment"];

const SECTIONS = {
  h2h: H2H_KEYS,
  wp: WP_KEYS.wp,
  wpmodern: WP_KEYS.wpmodern,
  skills: SKILL_KEYS,
  modifiers: REPEATING_BONUS_KEYS,
  magic: MAGIC_KEYS,
  psionics: PSIONICS_KEYS,
  movement: MOVEMENT_KEYS,
  powersabilities: ABILITIES_KEYS,
  armor: ARMOR_KEYS,
  // profiles: PROFILES_KEYS, // Tricky to export because IDs that they refer to won't line up
  equipment: EQUIPMENT_KEYS,
};
