const H2H = {
  "hand to hand: basic": [
    { attacks: 4, pull: 2, roll: 2 },
    { parry: 2, dodge: 2 },
    { description: "Kick attack does 1D8 points of damage\n" },
    { attacks: 1 },
    { strike: 1, disarm: 1 },
    { critical: 19 },
    { damage: 2 },
    {
      description:
        "Judo-style body flip/throw; does 1D6 damage, and victim loses initiative and one attack\n",
    },
    { attacks: 1 },
    { pull: 2, roll: 2 },
    { parry: 1, dodge: 1 },
    { strike: 1 },
    { description: "Critical Strike or knockout from behind\n" },
    { damage: 2 },
    { attacks: 1 },
  ],
  "hand to hand: expert": [
    { attacks: 4, pull: 2, roll: 2, description: "kick attack 1D8 damage\n" },
    { parry: 3, dodge: 3, pull: 1 },
    { strike: 2, disarm: 2, description: "can perform a Karate Punch\n" },
    { attacks: 1 },
    { description: "Can perform a Karate Kick, does 2D6 damage\n" },
    { critical: 18 },
    {
      description:
        "W.P. Paired Weapons\nbackhand strike (average, does 1D4 damage)\n",
    },
    {
      description:
        "Body flip/throw; does 1D6 damage, and victim loses initiative and one attack\n",
    },
    { attacks: 1, disarm: 1 },
    { damage: 3 },
    { knockout: 18 },
    { parry: 2, dodge: 2 },
    {
      description: "Critical Strike or knockout from behind (triple damage)\n",
    },
    { attacks: 1 },
    { deathblow: 20 },
  ],
  "hand to hand: martial arts": [
    {
      attacks: 4,
      pull: 3,
      roll: 3,
      description:
        "body flip/throw; does ID6 damage, victim loses initiative and one attack\n",
    },
    {
      parry: 3,
      dodge: 3,
      strike: 2,
      description: "may perform Ka­rate and any hand strike/punch\n",
    },
    {
      initiative: 1,
      description:
        "may perform a Karate-style kick (does 2D6 damage) and any foot strike except Leap Kick\n",
    },
    { attacks: 1 },
    {
      entangle: 2,
      description: "Leap Kick (3D8 damage, but counts as two melee attacks)\n",
    },
    { critical: 18 },
    { disarm: 2, description: "W.P. Paired Weapons\ncan perform Holds\n" },
    { description: "Back flip and back flip escape\n" },
    { attacks: 1 },
    { disarm: 2, description: "Back flip attack\n" },
    { damage: 4, initiative: 1 },
    { parry: 2, dodge: 2 },
    { knockout: 18 },
    { attacks: 1 },
    { deathblow: 20 },
  ],
  "hand to hand: assassin": [
    { attacks: 3, strike: 2, description: "W.P. Paired Weapons\n" },
    { initiative: 1, attacks: 2 },
    { pull: 3, roll: 2, description: "Karate Punch (2D4 damage)\n" },
    { damage: 4, initiative: 1, description: "Karate Kick (2D6 damage)\n" },
    { attacks: 1, throw: 1 },
    {
      parry: 3,
      dodge: 3,
      entangle: 2,
      description: "backhand strike (martial arts 1D6)\n",
    },
    {
      knockout: 17,
      description: "leap kick (3D8 damage, but counts as two melee attacks)\n",
    },
    { attacks: 1, strike_range: 1, initiative: 1 },
    { initiative: 1 },
    { critical: 19 },
    {
      strike: 2,
      throw: 1,
      strike_range: 1,
      description: "can perform back flip attack\n",
    },
    { pull: 2, deathblow: 19 },
    { attacks: 1 },
    { damage: 2, description: "can perform Holds\n" },
    { strike: 2, strike_range: 1 },
  ],
  "hand to hand: commando": [
    {
      attacks: 4,
      horrorfactor: 2,
      description: "W.P. Paired Weapons, body flip/throw, body block/tackle\n",
    },
    {
      initiative: 1,
      strike: 1,
      parry: 2,
      dodge: 2,
      roll: 3,
      pull: 3,
      description:
        "Backward sweep kick, used only against opponents coming up behind the character. Does no damage; it is purely a knockdown attack (same penalties as body flip) but cannot be parried (an opponent can try to dodge it but is -2 to do so)\n",
    },
    {
      initiative: 1,
      disarm: 1,
      description: "Karate punch/strike (does 2D4 damage)\n",
    },
    {
      attacks: 1,
      description:
        "Karate kick (does 2D6). The karate-style kick starts with bringing the knee, folded, up to chest level, then the foot is completely extended\n",
    },
    { dodge_auto: 2, description: "all foot strikes\n" },
    { initiative: 1, strike: 1, parry: 1, dodge: 1, flipthrow: 1 },
    { damage: 2, horrorfactor: 1, disarm: 1, dodge_auto: 1, pull: 2 },
    { attacks: 1, flipthrow: 2, roll: 1 },
    { deathblow: 18, pull: 2 },
    { horrorfactor: 2, initiative: 1, strike: 1 },
    { disarm: 1, pull: 1, flipthrow: 2 },
    { damage: 2, parry: 1, dodge: 1, dodge_auto: 2 },
    { attacks: 1 },
    { initiative: 1, description: "Can perform holds\n" },
    { critical: 17 },
  ],
  "hand to hand: dragon": [
    {
      attacks: 3,
      roll: 2,
      pull: 1,
      description:
        "Instinctively knows the following attack types: Bite, punch, kick, Claw Swipe, and standard use of breath weapon (counts as one melee attack). Dragon metamor­phosis takes one full melee (15 seconds).\n",
    },
    {
      parry: 2,
      dodge: 2,
      description: "Tail Slap, Wing At­tack: Basic, and Crush\n",
    },
    {
      damage: 2,
      description:
        "Dragon metamorphosis takes half a melee round (7 sec­onds), and Tail Slap Power Strike\n",
    },
    { attacks: 1, description: "Bite & Grip, and Tail Sweep\n" },
    { strike: 1, parry: 1, dodge_flight: 2, description: "Tail Parry\n" },
    {
      description:
        "+1 to Spell Strength, gains the Wing Sweep and Grappling Hold.\n",
    },
    { disarm: 2, entangle: 2, pull: 2, description: "Wing Attack: Advanced\n" },
    {
      attacks: 1,
      strike: 1,
      parry: 1,
      dodge_flight: 1,
      description: "Wing Gliding Sweep Attack\n",
    },
    {
      roll: 1,
      pull: 1,
      description:
        "Gains Breath Weapon Concentrated Beam, and an additional +5% to Dimensional Teleport (a natural ability).\n",
    },
    { initiative: 1, critical: 19, description: "Teleport Dodge\n" },
    { damage: 2, dodge_flight: 2, description: "+1 to Spell Strength\n" },
    { attacks: 1, strike: 1, dodge_teleport: 1 },
    { initiative: 1, description: "Breath Weapon Cone\n" },
    { dodge_teleport: 1, pull: 1 },
    { description: "+1 to Spell Strength and + 1D4x10 to M.D.C\n" },
    { attacks: 1, damage: 2 },
    { dodge_teleport: 1, dodge_flight: 1 },
    { strike: 1, parry: 1, description: "+ 1 to Spell Strength\n" },
    {
      dodge_teleport: 1,
      disarm: 1,
      roll: 1,
      description: "+1D4x10 to physical M.D.C.\n",
    },
    { attacks: 1 },
  ],
  "rpa combat: basic": [
    {
      attacks: 1,
      strike: 1,
      parry: 1,
      dodge: 1,
      roll: 1,
      description:
        "Power Armor Body Block/Tackle/Ram: 1D4 M.D. plus a 01-50% chance of knocking an opponent down, causing him to lose initiative and one melee attack/action. Counts as two of the power armor's melee attacks.\n" +
        "Robot Body Block/Tackle/Ram: M.D. equal to Robot Punch M.D. plus a 01-60% chance of knocking down an opponent that is approxi­ mately the same size or larger. Increase the odds of knocking down an opponent that is half the size or smaller than the robot to 0 1 -80%. The victim suffers M.D. and loses initiative and two melee attacks/actions. Counts as two ofthe robot's melee attacks.\n",
    },
  ],
  "rpa combat: flying power armor": [
    {
      attacks: 1,
      initiative: 2,
      strike_range: 2,
      strike: 2,
      parry: 2,
      dodge: 2,
      dodge_flight: 5,
      disarm: 2,
      pull: 3,
      roll: 4,
      description:
        "Punch Damage: As per Robot (or Augmented) P.S.\nPower Punch: Double damage, but counts as two melee attacks. Tear or Pry with Hands: 1D4 M.D.\nKick Damage: As per Robot (or Augmented) P.S.\nBody B1ock/Ram: Equal to the Robot P.S. punch damage.\nFull Speed Running Ram: Double Robot P.S. punch damage, plus 01-60% likelihood of knocking an opponent off his feet if the opponent is the same size or smaller (reduce by half if twice as big). Victim takes M.D. and is knocked off his feet, losing initiative and two melee at­tacks/actions.\n",
    },
    {},
    { attacks: 1 },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
  ],
  "rpa combat: ground-based power armor": [
    {
      attacks: 1,
      initiative: 1,
      strike_range: 2,
      strike: 3,
      parry: 2,
      dodge: 2,
      disarm: 3,
      pull: 3,
      roll: 2,
      description:
        "Punch Damage: As per Robot (or Augmented) P.S.\nPower Punch: Double damage, but counts as two melee attacks.\nTear or Pry with Hands: 1D4 M.D.\nKick Damage: As per Robot (or Augmented) P.S.\nBody B1ock/Ram: Equal to the Robot P.S. punch damage.\nFull Speed Running Ram: Double Robot P.S. punch damage, plus 01-50% likelihood of knocking an opponent off his feet if the opponent is the same size or smaller (reduce by half if twice as big). Victim takes M.D. and is knocked off his feet, losing initiative and two melee at­tacks/actions.\n",
    },
    {},
    { attacks: 1 },
    {},
    { attacks: 1 },
    {},
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    {},
    { attacks: 1 },
  ],
  "rpa combat: heavy vehicular style robots": [
    {
      attacks: 1,
      initiative: 1,
      strike_range: 3,
      strike: 1,
      parry: 1,
      dodge: 1,
      dodge_motion: 2,
      roll: 1,
      description:
        "Punch/Kick Damage: As per Robot P.S.\n" +
        "Power Punch/Kick: Double damage, but counts as two melee attacks.\n" +
        "Kick Damage: As per Robot P.S.\n" +
        "Body Block/Ram: Equal to the Robot P.S. punch damage.\n" +
        "Full Speed Running Ram: Triple the Robot P.S. punch damage, plus 01-80% likelihood of knocking opponent off his feet if the opponent is the same size or smaller. Victim takes M.D. and is knocked off his feet, losing initiative and two melee attacks/actions.\n" +
        "Stomp: 1D6 M.D.; effective only against objects smaller than one third the robot's total height.\n",
    },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
  ],
  "rpa combat: heavy ground robots": [
    {
      attacks: 1,
      initiative: 1,
      strike_range: 1,
      strike: 2,
      parry: 3,
      dodge: 1,
      dodge_motion: 2,
      disarm: 1,
      pull: 2,
      roll: 3,
      description:
        "Punch Damage: As per Robot P.S.\n" +
        "Power Punch: Double damage, but counts as two melee attacks.\n" +
        "Tear or Pry with Hands: 1D6 M.D.\n" +
        "Kick Damage: As per Robot P.S.\n" +
        "Body Block/Ram: Equal to the Robot P.S. punch damage.\n" +
        "Full Speed Running Ram: Double the Robot P.S. punch damage, plus 01-85% likelihood of knocking opponent off his feet if the opponent is the same size or smaller. Victim takes M.D. and is knocked off his feet, losing initiative and two melee attacks/actions.\n" +
        "Stomp: 1D6 M.D.; effective only against objects smaller than one third the robot's total height.\n",
    },
    {},
    { attacks: 1 },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    {},
    { attacks: 1 },
  ],
  "rpa combat: light ground robots": [
    {
      attacks: 1,
      initiative: 2,
      strike_range: 1,
      strike: 3,
      parry: 3,
      dodge: 2,
      dodge_motion: 3,
      disarm: 2,
      pull: 4,
      roll: 4,
      description:
        "Punch Damage: As per Robot P.S.\n" +
        "Power Punch: Double damage, but counts as two melee attacks.\n" +
        "Tear or Pry with Hands: 1D4 M.D.\n" +
        "Kick Damage: As per Robot P.S.\n" +
        "Body Block/Ram: Equal to the Robot P.S. punch damage.\n" +
        "Full Speed Running Ram: Double the Robot P.S. punch damage, plus 01-70% likelihood of knocking opponent off his feet if the opponent is the same size or smaller. Victim takes M.D. and is knocked off his feet, losing initiative and two melee attacks/actions.\n" +
        "Stomp: 1D4 M.D.; effective only against objects smaller than one third the robot's total height.\n",
    },
    {},
    { attacks: 1 },
    {},
    { attacks: 1 },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
  ],
  "rpa combat: glitter boy": [
    {
      attacks: 2,
      initiative: 2,
      strike_range: 2,
      strike: 2,
      parry: 2,
      dodge: 2,
      disarm: 1,
      pull: 4,
      roll: 3,
      description:
        "Punch Damage: 1D4 M.D. on a restrained punch, 1D6 M.D. on a full strength punch.\n" +
        "Power Punch: 2D6 M.D., but counts as two melee attacks.\n" +
        "Kick Damage: 2D4 M.D., Power Kick is not possible.\n" +
        "Running Leap Kick: 4D6 M.D., but counts as three attacks.\n" +
        "Tear or Pry with Hands (Special): 1D6 M.D.\n" +
        "Body BlocklRam: 2D4 M.D.\n" +
        "Full Speed Running Ram: 3D6 M.D., but this attack uses up three melee actions.\n" +
        "Stomp: 1D6 M.D.; effective only against objects smaller than three feet (0.9 m) tall.\n" +
        "Pylon Impalement: 1D6 M.D., not very useful in most combat situa­tions.\n",
    },
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    { attacks: 1 },
    {},
    {},
    {},
    {},
  ],
};

const WP = {
  "w.p. archery": [
    { strike: 1, parry: 1, rof: 2 },
    { strike: 1, disarm: 1, rof: 1 },
    {},
    { strike: 1, rof: 1 },
    { disarm: 1, rof: 1 },
    { strike: 1 },
    {},
    { strike: 1, rof: 1 },
    {},
    { strike: 1, disarm: 1, rof: 1 },
    {},
    { strike: 1, rof: 1 },
    {},
    { strike: 1, rof: 1 },
    { disarm: 1 },
  ],
  "w.p. axe": [
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
  ],
  "w.p. bayonet": [
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    {},
  ],
  "w.p. blunt": [
    { strike: 1, parry: 1 },
    {},
    { strike: 1, parry: 1 },
    {},
    { throw: 1 },
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    { throw: 1 },
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    { throw: 1 },
  ],
  "w.p. chain": [
    { strike: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    { strike: 1 },
    {},
    { parry: 1 },
    { strike: 1 },
    {},
    {},
  ],
  "w.p. forked": [
    { strike: 1, parry: 1, entangle: 1 },
    {},
    { strike: 1, parry: 1, entangle: 1 },
    { throw: 1 },
    { strike: 1, entangle: 1 },
    { parry: 1 },
    {},
    { strike: 1, entangle: 1 },
    {},
    { parry: 1, throw: 1 },
    { strike: 1, entangle: 1 },
    {},
    { strike: 1, parry: 1, entangle: 1 },
    {},
    { throw: 1 },
  ],
  "w.p. knife": [
    { parry: 1, throw: 1 },
    { strike: 1 },
    { parry: 1, throw: 1 },
    { strike: 1 },
    {},
    { parry: 1, throw: 1 },
    { strike: 1 },
    { throw: 1 },
    { parry: 1 },
    { strike: 1, throw: 1 },
    {},
    { parry: 1 },
    { strike: 1, throw: 1 },
    {},
    {},
  ],
  "w.p. grappling hook": [
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    {},
  ],
  "w.p. pole arm": [
    { strike: 1, parry: 1 },
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    {},
    { throw: 1 },
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    {},
  ],
  "w.p. rope": [
    { strike: 1, entangle: 1, disarm: 1 },
    {},
    {},
    { strike: 1 },
    {},
    {},
    {},
    { strike: 1 },
    {},
    {},
    {},
    { strike: 1 },
    {},
    {},
    { strike: 1 },
  ],
  "w.p. shield": [
    { parry: 1 },
    {},
    { parry: 1 },
    { strike: 1 },
    {},
    {},
    { parry: 1 },
    { strike: 1 },
    {},
    { parry: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    {},
  ],
  "w.p. spear": [
    { strike: 1, parry: 1 },
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    { throw: 1 },
    {},
    { strike: 1, parry: 1 },
    {},
    { throw: 1 },
    {},
  ],
  "w.p. staff": [
    { strike: 1 },
    { parry: 1 },
    { strike: 1 },
    {},
    { parry: 1, throw: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    { strike: 1, throw: 1 },
    { parry: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    { throw: 1 },
  ],
  "w.p. sword": [
    { strike: 1 },
    { parry: 1 },
    { strike: 1 },
    { parry: 1, throw: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    { throw: 1 },
    { strike: 1 },
    { parry: 1 },
    {},
    { strike: 1, throw: 1 },
    { parry: 1 },
    {},
    { strike: 1 },
  ],
  "w.p. targeting": [
    { throw: 1 },
    {},
    { throw: 1 },
    {},
    {},
    {},
    { throw: 1 },
    {},
    {},
    { throw: 1 },
    {},
    {},
    {},
    {},
    {},
  ],
  "w.p. whip": [
    {},
    { strike: 1, entangle: 1, disarm: 1, damage: 1 },
    {},
    { strike: 1, entangle: 1, disarm: 1, damage: 1 },
    {},
    {},
    { strike: 1, entangle: 1, disarm: 1 },
    { damage: 1 },
    {},
    { strike: 1, entangle: 1, disarm: 1 },
    {},
    { damage: 1 },
    { strike: 1, entangle: 1, disarm: 1 },
    {},
    {},
  ],
  "w.p. handguns": [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
  ],
  "w.p. rifles": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    {},
  ],
  "w.p. energy heavy": [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
  ],
  "w.p. energy pistol": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
  ],
  "w.p. energy rifle": [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
  ],
  "w.p. heavy": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    {},
    { strike_range_single: 1 },
    {},
  ],
  "w.p. speargun": [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    {},
    {},
    { strike_range_single: 1 },
  ],
  "w.p. shotgun": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    {},
    { strike_range_single: 1 },
    {},
  ],
  "w.p. submachinegun": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
  ],
  "w.p. flamethrower": [
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
  ],
};

const WP_KEYS = {
  wp: [
    "name",
    "level",
    "strike",
    "parry",
    "disarm",
    "rof",
    "throw",
    "entangle",
  ],
  wpmodern: [
    "name",
    "level",
    "strike_range_single",
    "disarm",
    "strike_range_burst",
  ],
};

const ATTRIBUTE_KEYS = [
  "mod_iq",
  "iq_abs",
  "mod_iq_bonus",
  "mod_perception_bonus",
  "mod_me",
  "mod_me_bonus",
  "me_abs",
  "mod_ma",
  "mod_ma_bonus",
  "ma_abs",
  "mod_ps",
  "mod_ps_bonus",
  "ps_abs",
  "mod_pp",
  "mod_pp_bonus",
  "pp_abs",
  "mod_pe",
  "mod_pe_bonus",
  "mod_pe_coma_bonus",
  "pe_abs",
  "mod_pb",
  "mod_pb_bonus",
  "pb_abs",
  "mod_spd",
  "spd_abs",
  "mod_spdfly",
  "spdfly_abs",
  "mod_character_ps_type",
  "mod_restrained_punch",
  "mod_restrained_punch_unit",
  "mod_punch",
  "mod_punch_unit",
  "mod_power_punch",
  "mod_power_punch_unit",
  "mod_kick",
  "mod_kick_unit",
  "mod_leap_kick",
  "mod_leap_kick_unit",
  "mod_liftcarry_weight_multiplier",
  "mod_liftcarry_duration_multiplier",
  "mod_lift",
  "mod_carry",
  "mod_throw_distance",
  "mod_carry_max",
  "mod_carry_running",
  "mod_hold_max",
  "hp",
  "sdc",
  "ar",
  "mdc",
  "ps_type",
  "ppe",
  "isp",
  "mod_hf",
  "hf_abs",
  "mod_spellstrength",
  "spellstrength_abs",
  "mod_trust",
  "trust_abs",
  "mod_intimidate",
  "intimidate_abs",
  "mod_charmimpress",
  "charmimpress_abs",
  "mod_skillbonus",
];

const COMBAT_KEYS = [
  // "selection_id",
  "name",
  "level",
  "attacks",
  "sdc",
  "mdc",
  "initiative",
  "strike",
  "parry",
  "dodge",
  "throw",
  "disarm",
  "entangle",
  "pull",
  "roll",
  "damage",
  "damage_paired",
  "damage_mainhand",
  "damage_offhand",
  "dodge_flight",
  "dodge_auto",
  "dodge_teleport",
  "dodge_motion",
  "dodge_underwater",
  "strike_range",
  "strike_range_single",
  "strike_range_burst",
  "strike_range_aimed",
  "strike_range_aimed_single",
  "strike_range_aimed_pulse",
  "strike_range_called",
  "strike_range_called_single",
  "strike_range_called_pulse",
  "strike_range_aimed_called_single",
  "strike_range_aimed_called_pulse",
  "disarm_range",
  "damage_range",
  "damage_range_single",
  "damage_range_burst",
  "critical",
  "knockout",
  "deathblow",
  "flipthrow",
  "description",
];
const SAVE_KEYS_ATTRIBUTE_BONUSES = {
  me_bonus: ["psionics", "insanity"],
  pe_bonus: ["magic", "lethalpoison", "nonlethalpoison", "disease", "drugs"],
  pe_coma_bonus: ["comadeath"],
  perception_bonus: ["perceptioncheck"],
  none: [
    "pain",
    "horrorfactor",
    "mindcontrol",
    "illusions",
    "possession",
    "curses",
    "maintainbalance",
    "fatigue",
    "despair",
    "telepathicprobes",
  ],
};
const SAVE_KEYS = Object.values(SAVE_KEYS_ATTRIBUTE_BONUSES).reduce(
  (acc, cur) => acc.concat(cur),
  []
);
const REPEATING_BONUS_KEYS = COMBAT_KEYS.concat(SAVE_KEYS, ATTRIBUTE_KEYS);
const SKILL_KEYS = [
  "name",
  "category",
  "base",
  "bonus",
  "perlevel",
  "level",
  "total",
];

const ABILITIES_REPEATERS = ["magic", "psionics", "powersabilities"];

const MAGIC_KEYS = REPEATING_BONUS_KEYS.concat([
  "name",
  "school",
  "spell_level",
  "range",
  "damage",
  "duration",
  "percentage",
  "ppecost",
  "range_starting",
  "range_per_level",
  "range_units",
  "damage_starting",
  "damage_per_level",
  "damage_units",
  "dc_starting",
  "dc_per_level",
  "dc_units",
  "duration_starting",
  "duration_per_level",
  "duration_units",
  "percentage_starting",
  "percentage_per_level",
  "addtobonuses",
]);

const PSIONICS_KEYS = REPEATING_BONUS_KEYS.concat([
  "name",
  "range",
  "damage",
  "duration",
  "percentage",
  "ispcost",
  "range_starting",
  "range_per_level",
  "range_units",
  "damage_starting",
  "damage_per_level",
  "damage_units",
  "dc_starting",
  "dc_per_level",
  "dc_units",
  "duration_starting",
  "duration_per_level",
  "duration_units",
  "percentage_starting",
  "percentage_per_level",
  "addtobonuses",
]);

const ABILITIES_KEYS = REPEATING_BONUS_KEYS.concat([
  "name",
  "range",
  "damage",
  "duration",
  "percentage",
  "range_starting",
  "range_per_level",
  "range_units",
  "damage_starting",
  "damage_per_level",
  "damage_units",
  "dc_starting",
  "dc_per_level",
  "dc_units",
  "duration_starting",
  "duration_per_level",
  "duration_units",
  "frequency_starting",
  "frequency_per_level",
  "frequency_units",
  "percentage_starting",
  "percentage_per_level",
  "addtobonuses",
]);

const PROFILES_KEYS = REPEATING_BONUS_KEYS.concat(["bonus_ids", "bonus_names"]);

const CORE_KEYS = [
  "character_name",
  "truename_name",
  "character_race",
  "occ",
  "character_ps_type",
  "character_level",
  "experience",
  "alignment",
  "character_age",
  "character_gender",
  "character_height",
  "character_weight",
  "character_familyorigin",
  "character_environment",
  "character_languages",
  "character_insanity",
  "character_disposition",
  "iq",
  "iq_bonus",
  "perception_bonus",
  "me",
  "me_bonus",
  "ma",
  "ma_bonus",
  "ps",
  "ps_bonus",
  "pp",
  "pp_bonus",
  "pe",
  "pe_bonus",
  "pe_coma_bonus",
  "pb",
  "pb_bonus",
  "spd",
  "spdfly",
  "charmimpress",
  "character_hp",
  "character_sdc",
  "character_ar",
  "character_mdc",
  "character_ppe",
  "character_isp",
  "hf",
  "spellstrength",
  "perception",
  "run_mph",
  "run_ft_melee",
  "run_ft_attack",
  "run_cruising",
  "run_at_max",
  "leapup",
  "leapout",
  "equipment",
  "psionic_ability",
  "credits_universal_bearer",
  "credits_universal_marked",
  "credits_blackmarket",
  "credits_ngmi",
  "credits_phaseworld",
  "credits_splugorth",
  "credits_gems",
  "credits_blackmarketmerchandise",
];

const ARMOR_KEYS = [
  "is_active",
  "name",
  "movementpenalty",
  "basemdc",
  "currentmdc",
];

const MOVEMENT_KEYS = ["name", "mph", "ft_melee", "cruising", "dur_at_max"];

const EQUIPMENT_KEYS = ["equipment"];

const SECTIONS = {
  // h2h: REPEATING_BONUS_KEYS, // this will be inefficient. need to specify the exact keys required
  wp: WP_KEYS.wp,
  wpmodern: WP_KEYS.wpmodern,
  skills: SKILL_KEYS,
  modifiers: REPEATING_BONUS_KEYS,
  magic: MAGIC_KEYS,
  psionics: PSIONICS_KEYS,
  movement: MOVEMENT_KEYS,
  powersabilities: ABILITIES_KEYS,
  armor: ARMOR_KEYS,
  // profiles: PROFILES_KEYS, // Tricky to export because IDs that they refer to won't line up
  equipment: EQUIPMENT_KEYS,
};
