const WP = {
  "w.p. archery": [
    { strike: 1, parry: 1, rof: 2 },
    { strike: 1, disarm: 1, rof: 1 },
    {},
    { strike: 1, rof: 1 },
    { disarm: 1, rof: 1 },
    { strike: 1 },
    {},
    { strike: 1, rof: 1 },
    {},
    { strike: 1, disarm: 1, rof: 1 },
    {},
    { strike: 1, rof: 1 },
    {},
    { strike: 1, rof: 1 },
    { disarm: 1 },
  ],
  "w.p. axe": [
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
  ],
  "w.p. bayonet": [
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    {},
  ],
  "w.p. blunt": [
    { strike: 1, parry: 1 },
    {},
    { strike: 1, parry: 1 },
    {},
    { throw: 1 },
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    { throw: 1 },
    {},
    { strike: 1, parry: 1 },
    {},
    {},
    { throw: 1 },
  ],
  "w.p. chain": [
    { strike: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    { strike: 1 },
    {},
    { parry: 1 },
    { strike: 1 },
    {},
    {},
  ],
  "w.p. forked": [
    { strike: 1, parry: 1, entangle: 1 },
    {},
    { strike: 1, parry: 1, entangle: 1 },
    { throw: 1 },
    { strike: 1, entangle: 1 },
    { parry: 1 },
    {},
    { strike: 1, entangle: 1 },
    {},
    { parry: 1, throw: 1 },
    { strike: 1, entangle: 1 },
    {},
    { strike: 1, parry: 1, entangle: 1 },
    {},
    { throw: 1 },
  ],
  "w.p. knife": [
    { parry: 1, throw: 1 },
    { strike: 1 },
    { parry: 1, throw: 1 },
    { strike: 1 },
    {},
    { parry: 1, throw: 1 },
    { strike: 1 },
    { throw: 1 },
    { parry: 1 },
    { strike: 1, throw: 1 },
    {},
    { parry: 1 },
    { strike: 1, throw: 1 },
    {},
    {},
  ],
  "w.p. grappling hook": [
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    { strike: 1, entangle: 1 },
    {},
    {},
    {},
  ],
  "w.p. pole arm": [
    { strike: 1, parry: 1 },
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    {},
    { throw: 1 },
    { strike: 1, parry: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    {},
  ],
  "w.p. rope": [
    { strike: 1, entangle: 1, disarm: 1 },
    {},
    {},
    { strike: 1 },
    {},
    {},
    {},
    { strike: 1 },
    {},
    {},
    {},
    { strike: 1 },
    {},
    {},
    { strike: 1 },
  ],
  "w.p. shield": [
    { parry: 1 },
    {},
    { parry: 1 },
    { strike: 1 },
    {},
    {},
    { parry: 1 },
    { strike: 1 },
    {},
    { parry: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    {},
  ],
  "w.p. spear": [
    { strike: 1, parry: 1 },
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1, throw: 1 },
    {},
    {},
    { strike: 1, parry: 1 },
    { throw: 1 },
    {},
    { strike: 1, parry: 1 },
    {},
    { throw: 1 },
    {},
  ],
  "w.p. staff": [
    { strike: 1 },
    { parry: 1 },
    { strike: 1 },
    {},
    { parry: 1, throw: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    {},
    { strike: 1, throw: 1 },
    { parry: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    { throw: 1 },
  ],
  "w.p. sword": [
    { strike: 1 },
    { parry: 1 },
    { strike: 1 },
    { parry: 1, throw: 1 },
    {},
    { strike: 1 },
    { parry: 1 },
    { throw: 1 },
    { strike: 1 },
    { parry: 1 },
    {},
    { strike: 1, throw: 1 },
    { parry: 1 },
    {},
    { strike: 1 },
  ],
  "w.p. targeting": [
    { throw: 1 },
    {},
    { throw: 1 },
    {},
    {},
    {},
    { throw: 1 },
    {},
    {},
    { throw: 1 },
    {},
    {},
    {},
    {},
    {},
  ],
  "w.p. whip": [
    {},
    { strike: 1, entangle: 1, disarm: 1, damage: 1 },
    {},
    { strike: 1, entangle: 1, disarm: 1, damage: 1 },
    {},
    {},
    { strike: 1, entangle: 1, disarm: 1 },
    { damage: 1 },
    {},
    { strike: 1, entangle: 1, disarm: 1 },
    {},
    { damage: 1 },
    { strike: 1, entangle: 1, disarm: 1 },
    {},
    {},
  ],
  "w.p. handguns": [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
  ],
  "w.p. rifles": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    {},
  ],
  "w.p. energy heavy": [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
  ],
  "w.p. energy pistol": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
  ],
  "w.p. energy rifle": [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    { strike_range_single: 1 },
    {},
  ],
  "w.p. heavy": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    {},
    { strike_range_single: 1 },
    {},
  ],
  "w.p. speargun": [
    {},
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    {},
    {},
    { strike_range_single: 1 },
  ],
  "w.p. shotgun": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    {},
    { strike_range_single: 1 },
    {},
  ],
  "w.p. submachinegun": [
    { strike_range_single: 1 },
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
  ],
  "w.p. flamethrower": [
    {},
    { strike_range_single: 1 },
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
    {},
    {},
    {},
    {},
    { strike_range_single: 1 },
    {},
    {},
    {},
    {},
    { strike_range_single: 1, strike_range_burst: 1 },
  ],
};

const WP_KEYS = {
  wp: [
    "name",
    "level",
    "strike",
    "parry",
    "disarm",
    "rof",
    "throw",
    "entangle",
  ],
  wpmodern: [
    "name",
    "level",
    "strike_range_single",
    "disarm",
    "strike_range_burst",
  ],
};

const ATTRIBUTE_KEYS = [
  "mod_iq",
  "iq_abs",
  "mod_iq_bonus",
  "mod_perception_bonus",
  "mod_me",
  "mod_me_bonus",
  "me_abs",
  "mod_ma",
  "mod_ma_bonus",
  "ma_abs",
  "mod_ps",
  "mod_ps_bonus",
  "ps_abs",
  "mod_pp",
  "mod_pp_bonus",
  "pp_abs",
  "mod_pe",
  "mod_pe_bonus",
  "mod_pe_coma_bonus",
  "pe_abs",
  "mod_pb",
  "mod_pb_bonus",
  "pb_abs",
  "mod_spd",
  "spd_abs",
  "mod_spdfly",
  "spdfly_abs",
  "mod_character_ps_type",
  "mod_restrained_punch",
  "mod_restrained_punch_unit",
  "mod_punch",
  "mod_punch_unit",
  "mod_power_punch",
  "mod_power_punch_unit",
  "mod_kick",
  "mod_kick_unit",
  "mod_leap_kick",
  "mod_leap_kick_unit",
  "mod_liftcarry_weight_multiplier",
  "mod_liftcarry_duration_multiplier",
  "mod_lift",
  "mod_carry",
  "mod_throw_distance",
  "mod_carry_max",
  "mod_carry_running",
  "mod_hold_max",
  "hp",
  "sdc",
  "ar",
  "mdc",
  "ps_type",
  "ppe",
  "isp",
  "mod_hf",
  "hf_abs",
  "mod_spellstrength",
  "spellstrength_abs",
  "mod_trust",
  "trust_abs",
  "mod_intimidate",
  "intimidate_abs",
  "mod_charmimpress",
  "charmimpress_abs",
  "mod_skillbonus",
];

const COMBAT_KEYS = [
  // "selection_id",
  "name",
  "level",
  "attacks",
  "sdc",
  "mdc",
  "initiative",
  "strike",
  "parry",
  "dodge",
  "throw",
  "disarm",
  "entangle",
  "pull",
  "roll",
  "damage",
  "damage_paired",
  "damage_mainhand",
  "damage_offhand",
  "dodge_flight",
  "dodge_auto",
  "dodge_teleport",
  "dodge_motion",
  "dodge_underwater",
  "strike_range",
  "strike_range_single",
  "strike_range_burst",
  "strike_range_aimed",
  "strike_range_aimed_single",
  "strike_range_aimed_pulse",
  "strike_range_called",
  "strike_range_called_single",
  "strike_range_called_pulse",
  "strike_range_aimed_called_single",
  "strike_range_aimed_called_pulse",
  "disarm_range",
  "damage_range",
  "damage_range_single",
  "damage_range_burst",
  "critical",
  "knockout",
  "deathblow",
  "flipthrow",
  "description",
];
const SAVE_KEYS_ATTRIBUTE_BONUSES = {
  me_bonus: ["psionics", "insanity"],
  pe_bonus: ["magic", "lethalpoison", "nonlethalpoison", "disease", "drugs"],
  pe_coma_bonus: ["comadeath"],
  perception_bonus: ["perceptioncheck"],
  none: [
    "pain",
    "horrorfactor",
    "mindcontrol",
    "illusions",
    "possession",
    "curses",
    "maintainbalance",
    "fatigue",
    "despair",
    "telepathicprobes",
  ],
};
const SAVE_KEYS = Object.values(SAVE_KEYS_ATTRIBUTE_BONUSES).reduce(
  (acc, cur) => acc.concat(cur),
  []
);
const REPEATING_BONUS_KEYS = COMBAT_KEYS.concat(SAVE_KEYS, ATTRIBUTE_KEYS);
const SKILL_KEYS = [
  "name",
  "category",
  "base",
  "bonus",
  "perlevel",
  "level",
  "total",
];

const ABILITIES_REPEATERS = ["magic", "psionics", "powersabilities"];

const MAGIC_KEYS = REPEATING_BONUS_KEYS.concat([
  "name",
  "school",
  "spell_level",
  "range",
  "damage",
  "duration",
  "percentage",
  "ppecost",
  "range_starting",
  "range_per_level",
  "range_units",
  "damage_starting",
  "damage_per_level",
  "damage_units",
  "dc_starting",
  "dc_per_level",
  "dc_units",
  "duration_starting",
  "duration_per_level",
  "duration_units",
  "percentage_starting",
  "percentage_per_level",
  "addtobonuses",
]);

const PSIONICS_KEYS = REPEATING_BONUS_KEYS.concat([
  "name",
  "range",
  "damage",
  "duration",
  "percentage",
  "ispcost",
  "range_starting",
  "range_per_level",
  "range_units",
  "damage_starting",
  "damage_per_level",
  "damage_units",
  "dc_starting",
  "dc_per_level",
  "dc_units",
  "duration_starting",
  "duration_per_level",
  "duration_units",
  "percentage_starting",
  "percentage_per_level",
  "addtobonuses",
]);

const ABILITIES_KEYS = REPEATING_BONUS_KEYS.concat([
  "name",
  "range",
  "damage",
  "duration",
  "percentage",
  "range_starting",
  "range_per_level",
  "range_units",
  "damage_starting",
  "damage_per_level",
  "damage_units",
  "dc_starting",
  "dc_per_level",
  "dc_units",
  "duration_starting",
  "duration_per_level",
  "duration_units",
  "frequency_starting",
  "frequency_per_level",
  "frequency_units",
  "percentage_starting",
  "percentage_per_level",
  "addtobonuses",
]);

const PROFILES_KEYS = REPEATING_BONUS_KEYS.concat(["bonus_ids", "bonus_names"]);

const CORE_KEYS = [
  "character_name",
  "truename_name",
  "character_race",
  "occ",
  "character_ps_type",
  "character_level",
  "experience",
  "alignment",
  "character_age",
  "character_gender",
  "character_height",
  "character_weight",
  "character_familyorigin",
  "character_environment",
  "character_languages",
  "character_insanity",
  "character_disposition",
  "iq",
  "iq_bonus",
  "perception_bonus",
  "me",
  "me_bonus",
  "ma",
  "ma_bonus",
  "ps",
  "ps_bonus",
  "pp",
  "pp_bonus",
  "pe",
  "pe_bonus",
  "pe_coma_bonus",
  "pb",
  "pb_bonus",
  "spd",
  "spdfly",
  "charmimpress",
  "character_hp",
  "character_sdc",
  "character_ar",
  "character_mdc",
  "character_ppe",
  "character_isp",
  "hf",
  "spellstrength",
  "perception",
  "run_mph",
  "run_ft_melee",
  "run_ft_attack",
  "run_cruising",
  "run_at_max",
  "leapup",
  "leapout",
  "equipment",
  "psionic_ability",
  "credits_universal_bearer",
  "credits_universal_marked",
  "credits_blackmarket",
  "credits_ngmi",
  "credits_phaseworld",
  "credits_splugorth",
  "credits_gems",
  "credits_blackmarketmerchandise",
];

const ARMOR_KEYS = [
  "is_active",
  "name",
  "movementpenalty",
  "basemdc",
  "currentmdc",
];

const MOVEMENT_KEYS = ["name", "mph", "ft_melee", "cruising", "dur_at_max"];

const EQUIPMENT_KEYS = ["equipment"];

const SECTIONS = {
  wp: WP_KEYS.wp,
  wpmodern: WP_KEYS.wpmodern,
  skills: SKILL_KEYS,
  modifiers: REPEATING_BONUS_KEYS,
  magic: MAGIC_KEYS,
  psionics: PSIONICS_KEYS,
  movement: MOVEMENT_KEYS,
  powersabilities: ABILITIES_KEYS,
  armor: ARMOR_KEYS,
  // profiles: PROFILES_KEYS, // Tricky to export because IDs that they refer to won't line up
  equipment: EQUIPMENT_KEYS,
};
