
const GENOS = [
    { name : 'Human',
        stats : {
            WS  : 20,
            BS  : 20,
            STR : 20,
            TOU : 20,
            AGI : 20,
            INT : 20,
            PER : 20,
            WP  : 20,
            FEL : 20,
            INF : 20
        },
        traits : ['Size (4)'],
        bonus : [
            { name : 'Pure of Form', desc : 'Pure of form and undiluted, there is no greater perfection than that of humanity. After applying Genos Characteristic Modifiers (see Page X) but before applying Home-World Characteristic Modifiers, a Human may distribute up to five 1-point increases across their characteristics. No Characteristic may be raised above 40 with these points.'}
        ],
        aptitudes : [],
        wounds : 7
    }, 
    { name : 'Ogryn',
        stats : {
            WS  : 15,
            BS  : 15,
            STR : 30,
            TOU : 30,
            AGI : 10,
            INT : 05,
            PER : 15,
            WP  : 15,
            FEL : 10,
            INF : 15
        },
        traits : ['Auto-Stabilised', ' Blatant', ' Clumsy', ' Size (5)', ' Unnatural Strength (3)', ' Unnatural Toughness (2)', ' Moderate Phobia Disorder (Claustrophobia)'],
        bonus : [
            { name: 'Giant’s Fortitude', desc: 'Though mighty and durable, the Orgyn lack natural abilities in many other areas. Thankfully, their fortitude allows them to easily maintain what little faculties they have. An Orgyn treats their Characteristic Bonuses as 2 higher for the purposes of determining when their Characteristics are reduced by Fatigue.'}
        ],
        aptitudes : ['Strength', 'Toughness'],
        wounds : 15
    },
    { name : 'Ratling',
        stats : {
            WS  : 20,
            BS  : 20,
            STR : 15,
            TOU : 10,
            AGI : 25,
            INT : 20,
            PER : 30,
            WP  : 20,
            FEL : 25,
            INF : 15
        },
        traits : ['Size (3)'],
        bonus : [
            { name : 'Masterfully Duplicitous', desc: 'When conventional methods fail, one can always trust a Ratling to get their hands on what is needed. Whenever a Ratling character attempts an Acquisition Test, they may reduce their warband’s Subtlety Score by 1 to gain a +20 Untyped Bonus on the Test. This Subtlety Loss cannot be negated or reduced by abilities that reduce Subtlety Loss. This ability can only be used once per Acquisition Test.'}
        ],
        aptitudes : ['Fellowship', 'Perception'],
        wounds : 5
    },
    { name : 'Squat',
        stats : {
            WS : 20,
            BS : 20,
            STR : 20,
            TOU : 30,
            AGI : 10,
            INT : 20,
            PER : 15,
            WP : 25,
            FEL : 10,
            INF : 20
        },
        traits : ['Size (4)', ' Sturdy'],
        bonus : [{name :'Everlasting Grudge', desc: 'Hate comes easy to the Squat people. They have suffered at the hands of many enemies before, and they are more than ready to return the favour. Whenever a Squat Character or a member of their Warband suffers Critical Damage from or has Righteous Fury inflicted against them by an opponent, the Squat gains the Hatred Talent against that individual. If the Squat already possesses the Hatred Talent against that opponent, increase the Talent\'s Attack Bonus against that opponent by 5. This Genos Bonus can only apply once against any given Opponent. Additionally, its effects only last until either the individual’s death or the end of the Encounter. Additionally, Squat Characters also begin with the Hatred (Orks) and the Hatred (Tyranids) Talents.'}],
        aptitudes : ['Toughness', 'Willpower'],
        wounds : 8
    },
    { name : 'Ghul',
        stats : {
            WS : 25,
            BS : 20,
            STR : 20,
            TOU : 10,
            AGI : 30,
            INT : 20,
            PER : 25,
            WP : 20,
            FEL : 10,
            INF : 15
        },
        traits : ['Size (4)', ' Blatant', 'Dark-Sight', 'Natural Weapons'],
        bonus : [
            {name : 'The Huntsman', desc : 'Expert trackers capable of moving across treacherous terrain with ease, Ghuls are the bane of all enemies of Mankind who hope to flee the Imperium’s retribution through Flight. Ghul Acolytes ignore all Treacherous Environments with a Penalty of -20 or less except Zero Gravity and gain a +20 Bonus on Athletics Tests made to Climb. Additionally, Ghul Acolytes do not halve their Movement Speed when performing the Tracking Use of the Survival Skill.'},
            {name : 'Twisted Form', desc : 'Made from unblessed bones and accursed flesh, the Ghul may manipulate themselves in ways others might deem unnatural. Ghul’s Character’s count as Size (3) for the purposes of Squeezing. Additionally, a Ghul Acolyte may suffer 1d5 Toughness Damage in order to increase their Degrees of Success on a Successful Dodge or Parry Test by 2.'}
        ],
        aptitudes : ['Agility', 'Perception'],
        wounds : 6
    }
]

const HOMEWORLDS = [
    { name : "Agri-World", 
        aptitudes : ["Strength","Toughness"], 
        bonus : { name : "Strength from the Land", desc : "An Agri-World character starts with either the Brutal Charge (2) or Sturdy Trait, decided by the character upon selecting this homeworld." }, 
        characteristics : { STR : +3, TOU : +3, AGI : -3 }, 
        fate : 2, 
        empBlessing : 7, 
        wounds : +2
    },
    { name : "Daemon World", 
        aptitudes : ["Willpower","Perception"], 
        bonus : { name : "Touched by the Warp", desc : "A character from a Daemon World is attuned to the nature of the Warp. As such, they begin with one Rank in the Psyniscience Skill. Should they gain this Skill again in a later step of character creation, they instead gain one additional Rank in the Skill. Additionally, a Daemon Worlder may take ranks in the Psyniscience Skill even if they do not possess the Psyker Trait. This character also begins with 1d10+5 Corruption Points. Finally, a Daemon World Acolyte gains a +10 Bonus to Resist Fear Effects caused by Psychic Powers, Psychic Phenomena, Perils of the Warp, or the Fear Trait of creatures with the Daemonic Trait." }, 
        characteristics : { WP : +3, PER : +3, FEL : -3}, 
        fate : 3, 
        empBlessing : 8, 
        wounds : +1
    },
    { name : "Death World", 
        aptitudes : ["Agility","Perception"], 
        bonus : { name : "Inured to Death", desc : "Whenever a Death World Acolyte would suffer a Critical Effect, they reduce the Severity of that Critical Effect by 1. Additionally, Death World Acolytes gain a +10 Bonus on all Tests made to resist the effects of Critical Effects." }, 
        characteristics : { AGI : +3, PER : +3, FEL : -3}, 
        fate : 2, 
        empBlessing : 5, 
        wounds : +2
    },
    { name : "Feral World", 
        aptitudes : ["Strength","Weapon Skill"], 
        bonus : { name : "The Old Ways", desc : "A Feral World Acolyte Removes the Primitive Quality from and adds the Proven (3) Quality to all Melee and Low-Tech weapons that they wield." }, 
        characteristics : {STR : +3, WS : +3, INF : -3}, 
        fate : 2, 
        empBlessing : 6, 
        wounds : +2
    },
    { name : "Feudal World", 
        aptitudes : ["Strength","Weapon Skill"], 
        bonus : { name : "Live by the Sword", desc : "Feudal World Acolytes increase the Agility Maximum of all Armours by 20. Additionally, a Feudal World Character gains one additional Degree of Success on all Successful Attacks with Melee and Low-Tech weapons." }, 
        characteristics : { STR:+3, WS:+3, INT:-3}, 
        fate : 3, 
        empBlessing : 7, 
        wounds : +2
    },
    { name : "Forge World", 
        aptitudes : ["Intelligence","Toughness"], 
        bonus : { name : "Omnissiah’s Chosen", desc : "A forge world character gains a +20 Bonus on to apply weapon modifications. Additionally, they gain a +10 Bonus when repairing damaged items." }, 
        characteristics : { INT: +3, TOU: +3, FEL: -3}, 
        fate : 3, 
        empBlessing : 8, 
        wounds : +1
    },
    { name : "Fortress World", 
        aptitudes : ["Ballistic Skill","Weapon Skill"], 
        bonus : { name : "The Fortress Stands", desc : "While a fortress world character is Critically Wounded, they gain the Unnatural Toughness (X) Trait, where the number in parentheses (X) is equal to half of their Willpower Bonus. If they already possess this Trait, they increase their Unnatural Toughness Trait’s value by this value instead." }, 
        characteristics : { BS: +3, WS: +3, AGI: -3}, 
        fate : 2, 
        empBlessing : 6, 
        wounds : +2
    },
    { name : "Frontier World", 
        aptitudes : ["Ballistic Skill","Toughness"], 
        bonus : { name : "It’s a Strange World out Here", desc : "Frontier World Acolytes gain a +20 Bonus on Mundane Fear Tests. Additionally, a Frontier World Character reduces their Degrees of Failure on Mundane Fear Tests by 2 (Minimum 1)." }, 
        characteristics : { BS: +3, TOU: +3, FEL: -3}, 
        fate : 3, 
        empBlessing : 8, 
        wounds : +1
    },
    { name : "Garden World", 
        aptitudes : ["Willpower","Fellowship"], 
        bonus : { name : "Green Serenity: Whenever a garden world character rolls on Table X-X: Shock or Table X-X", desc : "Mental Traumas (See Page X and X), they may roll twice and take the result of their choice. Additionally, whenever a Garden World Character would gain Insanity Points, they gain 1 less Insanity Point (to a minimum of 0). Additionally, a Garden World Acolyte gains a +20 Bonus on Tests to resist the effects of Mental Disorders" }, 
        characteristics : { WP: +3, FEL: +3, WS: -3}, 
        fate : 3, 
        empBlessing : 4, 
        wounds : 0
    },
    { name : "Highborn", 
        aptitudes : ["Fellowship","Leadership"], 
        bonus : { name : "Breeding Counts", desc : "Any time a highborn character fails an Influence Test, they may re-roll the Test at a -10 Penalty, keeping the result of the re-roll." }, 
        characteristics : { FEL: +3, INF: +3, TOU: -3}, 
        fate : 4, 
        empBlessing : 10, 
        wounds : 0
    },
    { name : "Hive World", 
        aptitudes : ["Agility","Perception"], 
        bonus : { name : "Teeming Masses in Metal Mountains", desc : "A hive world character ignores crowds for the purposes of movement, treating them as open terrain. Hive Worlders also gain a +20 Bonus on Acrobatics Tests made to Disengage or Move Through Occupied Spaces. Additionally, When in enclosed spaces, they also gain +20 Bonus to Navigate (Surface) Tests. HiveWorld Acolytes also gain a +20 Bonus on Athletics Tests made to Climb buildings and synthetic structures." }, 
        characteristics : { AGI: +3, PER: +3, WP: -3}, 
        fate : 2, 
        empBlessing : 6, 
        wounds : +2
    },
    { name : "Penal Colony", 
        aptitudes : ["Toughness","Perception"], 
        bonus : { name : "Finger on the Pulse", desc : "One survives a penal colony by instinctively knowing when to act, when to engage in fight or flight. A penal colony character starts with the Constant Vigilance Talent. Additionally they gain a +2 Bonus to Initiative Rolls." }, 
        characteristics : { TOU: +3, PER: +3, INF: -3}, 
        fate : 2, 
        empBlessing : 7, 
        wounds : +2
    },
    { name : "Quarantine World", 
        aptitudes : ["Agility","Perception"], 
        bonus : { name : "Secretive by Nature", desc : "Those who manage to leave a quarantine world learn how to keep secrets. Whenever the warband’s Subtlety would decrease, it decreases by 2 less (to a minimum reduction of 1). Additionally, whenever the warband’s Subtlety would increase, they gain 1 additional Subtlety." }, 
        characteristics : { AGI: +3, PER: +3,INF: -3}, 
        fate : 3, 
        empBlessing : 9, 
        wounds : +1
    },
    { name : "Research Station", 
        aptitudes : ["Intelligence","Perception"], 
        bonus : { name : "Pursuit of Data", desc : "Whenever a research station character fails a Common Lore, Scholastic Lore, or Forbidden Lore Test, they may re-roll the Test at no Penalty." }, 
        characteristics : { INT: +3, PER: +3,FEL: -3}, 
        fate : 3, 
        empBlessing : 5, 
        wounds : 0
    },
    { name : "Shrine World", 
        aptitudes : ["Willpower","Fellowship"], 
        bonus : { name : "Faith in the Creed", desc : "Whenever a shrine world character makes a Salvation roll, they save their Fate Point on a result of either 1 or 10, rather than just 10." }, 
        characteristics : { WP: +3, FEL: +3, PER: -3}, 
        fate : 3, 
        empBlessing : 5, 
        wounds : 0
    },
    { name : "Voidborn", 
        aptitudes : ["Intelligence","Ballistic Skill"], 
        bonus : { name : "Child of the Void", desc : "A voidborn character may re-roll any failed Willpower Test to resist any Psychic Powers at no Penalty. Additionally, they may re-roll any failed Tests made to move in zero gravity environments at no Penalty." }, 
        characteristics : { INT: +3, BS: +3, STR: -3}, 
        fate : 3, 
        empBlessing : 4, 
        wounds : 0
    }
]

const BACKGROUNDS = [
    { name : "Adepta Sororitas", 
        aptitudes : ["Offence","Conviction"], 
        talents: [['Weapon Training (Flame)','Weapon Training (Low-Tech)'],'Weapon Training (Chain)'], 
        skills : [[' Charm', 'Intimidate'], 'Athletics', 'Common Lore (Adepta Sororitas)', 'Common Lore (Imperial Creed)', 'Linguistics (Low Gothic)', 'Linguistics (High Gothic)', ['Medicae', 'Parry'], 'Scrutiny'], 
        traits : [], 
        malignancies : [], 
        bonus : { name : "Incorruptible Devotion", desc : "Whenever an Adepta Sororitas character would gain 1 or more Corruption points, she gains that many Insanity Points minus 1 (to a minimum of 0) instead." }, 
        equipment : [['Hand flamer',['Repeating Crossbow', '4 clips of Mono-Bolts']], 'Chain-Sword with Sacred Inscriptions Weapon Modification', 'Armoured Body-Glove', 'Sanctified Idol'], 
        restrictions : ['Human'], 
        wounds: 0
    },
    { name : "Adeptus Administratum", 
        aptitudes : ["Knowledge","Social"], 
        talents: [['Weapon Training (Las)', 'Weapon Training (Solid Projectile)'],'Peer (Adeptus Administratum)'],
        skills : [['Commerce','Logic'],'Linguistics (Low Gothic)', 'Linguistics (High Gothic)',['Common Lore (Adeptus Administratum)','Common Lore (Imperium)'], 'Scholastic Lore (Bureaucracy)', 'Trade (Any One)'], 
        traits : [], 
        malignancies : [], 
        bonus : { name : "Master of Paperwork", desc : "Whenever an Adeptus Administratum Acolyte succeeds on an Acquisition Test, they increase their Degrees of Success by half of their Influence Bonus." }, 
        equipment : [['Las-Pistol','Stub Automatic'], 'Imperial Robes', 'Auto- Quill', 'Chrono', 'Data-Slate', 'Scraps of Knowledge'], 
        restrictions : [], 
        wounds: 0
    },
    { name : "Adeptus Arbites", 
        aptitudes : ["Offence","Defence"], 
        talents: [['Weapon Training (Low-Tech)', 'Weapon Training (Shock)'], 'Weapon Training (Solid Projectile)'], 
        skills : ['Common Lore (Adeptus Arbites, Underworld)', ['Inquiry', 'Interrogation'], 'Intimidate', 'Linguistics (Low Gothic)', 'Scholastic Lore (Judgement)', ['Scrutiny', 'Scrutiny']], 
        traits : [], 
        malignancies : [], 
        bonus : { name : "The Face of the Law", desc : "A character with the Adeptus Arbites background can re-roll any Intimidation or Interrogation Test, and can substitute their their Willpower Bonus for their Degrees of Success on Successful Tests with these Skills." }, 
        equipment : ['Shotgun', '4 Clips of Standard Ammo', '2 Clips of Shotgun Submission Shells', ['Man-Catcher', 'Shock Maul'], 'Light Carapace Armour', '6 Manacles'], 
        restrictions : [], 
        wounds: 1
    },
    { name : "Adeptus Astra Telepathica", 
        aptitudes : ["Defence","Conviction"], 
        talents: ['Weapon Training (Las)', 'Weapon Training (Low-Tech)'], 
        skills : [['Awareness', 'Inquiry'], 'Common Lore (Adeptus Astra Telepathica)', 'Forbidden Lore (The Warp)', 'Linguistics (Low Gothic)', 'Psyniscience', ['Scrutiny', 'Intimidation'], 'Scholastic Lore (Psykers)'], 
        traits : [], 
        malignancies : [], 
        bonus : [
            { name : "The Constant Threat", desc : "When this character or an ally within a number of metres equal to half of this character’s Perception Characteristic Score triggers a roll on Table X-X: Psychic Phenomenon (see Page X), the Adeptus Astra Telepathica character can increase or decrease the result by an amount equal to their Willpower Bonus."},
            { name : "Sanctioned by Rite", desc : "If a character with the Adeptus Astra Telepathica background takes the Psyker Novice Advance during character creation, they also gain the Sanctioned Trait (see Page X). Note that this will result in them starting play as a Gamma Rank Psyker (see Page X)."}
        ], 
        equipment : ['Las-Pistol', 'Staff with Mono Weapon Modification', 'Flak Cloak', ['Warding Idol', 'Psy Focus']], 
        restrictions : ['Human'], 
        wounds: 0
    },
    { name : "Adeptus Mechanicus", 
        aptitudes : ["Knowledge","Tech"], 
        talents: ['Mechadendrite Use (Utility)', 'Weapon Training (Solid Projectile)'], 
        skills : [['Awareness', 'Operate (Pick One)'], 'Common Lore (Adeptus Mechanicus)','Common Lore (Tech)', 'Linguistics (Techna-Lingua)', 'Linguistics (Low Gothic)', 'Logic', ['Security', 'Trade (Any One)'], 'Tech-Use'], 
        traits : ['Mechanicus Implants'], 
        malignancies : [], 
        bonus : { name : "Replace the Weak Flesh", desc : "An Adeptus Mechanicus character gains a +20 Bonus all Tests to Craft (see Page X) or Install (see Page X) Cybernetics." }, 
        equipment : [['Autogun', 'Hand-Cannon'], 'Combi-Tool', ['Monotask Servo-Skull', 'Optical Mechadendrite'], 'Imperial Robes', '2 Vials of Sacred Unguents', 'Scraps of Knowledge'], 
        restrictions : [], 
        wounds: 0
    },
    { name : "Adeptus Ministorum", 
        aptitudes : ["Leadership","Conviction "], 
        talents: [['Weapon Training (Flame)', 'Weapon Training (Solid Projectile)'], 'Weapon Training (Low-Tech)'], 
        skills : [['Charm', 'Interrogation'], ['Command', 'Intimidate'], 'Common Lore (Ecclesiarchy)', 'Common Lore (Imperial Creed)', 'Inquiry', 'Scrutiny', 'Linguistics (Low Gothic)', 'Linguistics (High Gothic)'], 
        traits : [], 
        malignancies : [], 
        bonus : { name : "Faith is All", desc : "When spending a Fate Point to Augment a Test, an Adeptus Ministorum character gains a +30 Bonus instead of a +20 Bonus. Additionally, when spending a Fate Point to Re-Roll a Test, an Adeptus Ministorum character gains a +15 Bonus instead of a +10 Bonus." }, 
        equipment : [[['Hand Flamer', 'Sword'], ['Warhammer', 'Stub Revolver']], ['Imperial Robes', 'Flak Vest'], 'Glow-Globe', 'Monotask Servo-Skull (Laud Hailer)', 'Sanctified Idol'], 
        restrictions : [], 
        wounds: 0
    },
    { name : "Commissariat", 
        aptitudes : ["Social","Leadership "], 
        talents: ['Weapon Training (Chain)', 'Weapon Training (Solid Projectile)'], 
        skills : [['Charm', 'Intimidate'], 'Command', ['Common Lore (Imperial Guard)', 'Common Lore (Imperial Navy)', 'Common Lore (Planetary Defence Force)'], ['Inquiry', 'Interrogation'], 'Linguistics (Imperial Codes)', 'Linguistics (High Gothic)', 'Linguistics (Low Gothic)', 'Scholastic Lore (Tactica)', 'Scrutiny'], 
        traits : [], 
        malignancies : [], 
        bonus : { name : "Stand and Fight!", desc : "Whenever a Commissariat Character successfully uses the Terrify Reaction Use of the Command Skill, they may Immediately use the Inspire use of the Command Skill as a Free Action, even if it is not their Turn. For the purposes of determining Modifiers to the Terrify Action’s Opposed Test, the Commissariat Acolyte is considered to have the Mundane Fear (2) Trait." }, 
        equipment : ['Hand-Cannon', 'Chainsword', 'Great-Cloak', 'Chrono', ['Laud Hailer', 'Microbead'], 'Magnoculars'], 
        restrictions : 'Human', 
        wounds: 0
    },
    { name : "Exorcised", 
        aptitudes : ["Defence","Knowledge"], 
        talents: ['Weapon Training (Solid Projectile)', 'Weapon Training (Chain)'], 
        skills : ['Awareness', ['Deceive', 'Inquiry'], 'Dodge', 'Forbidden Lore (Daemonology)', ['Intimidate', 'Scrutiny'], 'Linguistics (Low Gothic)', 'Scholastic Lore (Occult)'], 
        traits : [], 
        malignancies : ['An Exorcised character starts with one Malignancy or their choice, chosen from Table X-X: Malignancies (see page X).'], 
        bonus : { name : "Touched by a Daemon", desc : "An Exorcised character counts their Insanity Bonus as 2 higher for the purposes of avoiding Fear Tests (see Page X). They also gain a +30 Bonus on all Tests to resist Possession." }, 
        equipment : [['Auto-Pistol', 'Stub Revolver'], 'Shotgun', 'Chainblade', 'Imperial Robes', 'Nails of Benediction', 'Sanctified Idol'], 
        restrictions : [], 
        wounds: 0
    },
    { name : "Heretek", 
        aptitudes : ["Finesse","Tech"], 
        talents: ['Weapon Training (Solid Projectile)', 'Mechadendrite Use (Any One)'], 
        skills : [['Deceive', 'Inquiry'], 'Common Lore (Tech)', ['Forbidden Lore (Archeotech)', 'Forbidden Lore (Mutants)', 'Forbidden Lore (The Warp)', 'Forbidden Lore (Any One Xenos)'], 'Linguistics (Low Gothic)', 'Linguistics (Techna-Lingua)', ['Medicae', 'Security'], ['Scholastic Lore (Any One)', 'Trade (Any One)'], 'Tech-Use'], 
        traits : ['Mechanicus Implants'], 
        malignancies : ['An Exorcised character starts with one Malignancy or their choice, chosen from Table X-X: Malignancies (see page X).'], 
        bonus : { name : "Adept of Innovation", desc : "For the purpose of Trade Skill Tests made to Craft, a Heretek Acolyte increases their Degrees of Success by 1 on Successful Tests and reduces their Degrees of Failure on Failed Tests by 1 (Minimum 1)" }, 
        equipment : ['Stub Revolver', '4 Standard Clips', '2 Clips of Expander Rounds', '3 Photon Flash Grenades', 'Flak Cloak', 'Combi-Tool', 'Data-Slate'], 
        restrictions : ['Human', 'Ratling', 'Squat', 'Ghul'], 
        wounds: 0
    },
    { name : "Imperial Guard", 
        aptitudes : ["Fieldcraft","Leadership"], 
        talents: ['Weapon Training (Las)', 'Weapon Training (Low-Tech)'], 
        skills : ['Acrobatics', 'Athletics', ['Command', 'Intimidate'], 'Common Lore (Imperial Guard)', 'Linguistics (Imperial Codes)', 'Linguistics (Low Gothic)', ['Medicae', 'Operate (Surface)'], 'Navigate (Surface)'], 
        traits : [], 
        malignancies : [], 
        bonus : { name : "Hammer of the Emperor", desc : "When a Guardsman character is attacking a target that an ally has attacked since the end of the Guardsman’s last Turn, the Guardsman can re-roll any natural die results of 1 or 2 on Damage rolls." }, 
        equipment : [['Lasgun', ['Las-Pistol', 'Sword']], 'Combat Vest', 'Flak Armour', 'Grapnel and Line', ['12 Lho Sticks', '3 Doses of Recaff'], 'Micro-Bead'], 
        restrictions : [], 
        wounds: 1
    },
    { name : "Imperial Navy", 
        aptitudes : ["Offence","Tech "], 
        talents: [['Weapon Training (Chain)', 'Weapon Training (Shock)'], 'Weapon Training (Solid Projectile)'], 
        skills : [['Acrobatics', 'Athletics'], 'Command', 'Common Lore (Imperial Navy)', 'Common Lore (Imperium)', 'Linguistics (Imperial Codes)', 'Linguistics (Low Gothic)', ['Operate (Aeronautica)', 'Trade (Any One)'], 'Tech-Use'], 
        traits : [], 
        malignancies : [], 
        bonus : { name : "Close Quarter Discipline", desc : "An Imperial Navy character scores one additional degree of success on Successful Ballistic Skill Tests they make against targets at Point- Blank Range, at Short Range, and with whom they are engaged in melee." }, 
        equipment : [['Shotgun', 'Hand Cannon'], ['Chain-Sword', 'Shock Maul'], 'Flak Coat', 'Micro-Bead', ['3 Doses of Recaff', '6 Doses of Swill'], 'Respirator'], 
        restrictions : [], 
        wounds: 0
    },
    { name : "Legiones Skitarii", 
        aptitudes : ["Offence","Fieldcraft"], 
        talents: ['Weapon Training (Shock)', 'Weapon Training (Solid Projectile)'], 
        skills : ['Athletics', 'Awareness', 'Common Lore (Adeptus Mechanicus)', ['Common Lore (Tech)', 'Security'], ['Dodge', 'Parry'], 'Linguistics (Low Gothic)', 'Linguistics (Techna-Lingua)', 'Tech- Use'], 
        traits : [], 
        malignancies : [], 
        bonus : { name : "Strength of Steel", desc : "For the purposes of determining when their Characteristics are reduces by Fatigue (See Page X), a Skitarii Acolyte treats all of their Characteristic Bonuses as 1 higher. Also, Skitarii Characters do not suffer a -20 Penalty on Ballistic Skill Tests while Pinned, and gain a +20 Bonus on Tests to escape Pinning. Additionally, if the Skitarii Acolyte is Immune to Pinning for any reason, this +20 Bonus to escape Pinning becomes a +10 Bonus against on all Fear Tests." }, 
        equipment : ['Autogun', '4 Magazines', 'Shock Maul', 'Flak Cloak', 'Bionic Legs', 'Magnoculars', 'Respirator'], 
        restrictions : ['Human'], 
        wounds: 1
    },
    { name : "Merchant Guild", 
        aptitudes : ["Social","Knowledge"], 
        talents: ['Weapon Training (Shock)', 'Weapon Training (Solid Projectile)'], 
        skills : ['Charm', 'Commerce', 'Common Lore (Chartist Captains)', ['Deceive', 'Sleight of Hand'], ['Inquiry', 'Security'], 'Linguistics (Low Gothic)', 'Scrutiny'], 
        traits : [], 
        malignancies : [], 
        bonus : { name : "Born to Barter", desc : "A character with the Merchant Guild background can re-roll any Commerce or Acquisition Test, and can substitute their their Intelligence or Fellowship (character’s choice) Bonus for their Degrees of Success on Successful Commerce or Acquisition Tests." }, 
        equipment : ['Auto-Gun', 'Shock Maul', 'Flak Coat', 'Auto-Quill', 'Chrono', 'Data-Slate'], 
        restrictions : [], 
        wounds: 0
    },
    { name : "Mutant", 
        aptitudes : ["Fieldcraft","Offence"], 
        talents: ['Weapon Training (Low-Tech)', 'Weapon Training (Solid Projectile)'], 
        skills : [['Acrobatics', 'Athletics'], 'Awareness', 'Common Lore (Mutants)', ['Deceive', 'Intimidate'], 'Linguistics (Low Gothic)', 'Stealth', 'Survival'], 
        traits : [['Amphibious', 'Dark-Sight', 'Natural Weapons', 'Sonar Sense', 'Sturdy', 'Toxic (0)', 'Unnatural Agility (1)', 'Unnatural Strength (1)', 'Unnatural Toughness (1)']], 
        malignancies : ['A Mutant character gins with 10 Corruption Points. Instead of rolling as normal for a Malignancy or Mutation, the character starts with a mutation of their choice that would result from anywhere between a roll of 1 and 50 on Table X-X: Mutations (see Page X).'], 
        bonus : { name : "Twisted Flesh", desc : "A Mutant character may always choose to fail any Test associated with gaining Malignancy or Mutation. Whenever they would gain a Malignancy, they may instead roll on Table X-X : Mutations to gain a Mutation." }, 
        equipment : [[['Shotgun', 'Truncheon'], ['Stub Revolver', 'Great Weapon']], 'Heavy Leathers', 'Injector/Inhaler', '2 Doses of Stimm'], 
        restrictions : ['Human'], 
        wounds: 1
    },
    { name : "Outcast", 
        aptitudes : ["Fieldcraft","Social"], 
        talents: ['Weapon Training (Chain)', 'Weapon Training (Solid Projectile)'], 
        skills : [['Acrobatics', 'Sleight of Hand'], 'Common Lore (Underworld)', 'Deceive', 'Dodge', 'Linguistics (Low Gothic)', ['Security', 'Survival'], 'Stealth'], 
        traits : [], 
        malignancies : [], 
        bonus : { name : "Rugged Defiance", desc : "Unwilling to bend to any control other than their own, an Outcast may re-roll any failed Toughness or Willpower Test against any Mind-Affecting Ability, Psychic Power, or Drug at a -10 Penalty. This ability cannot be used to avoid re-roll Tests made to resist Psychic Bolts, Barrages, Beams, Blasts, or Storms." }, 
        equipment : [['Auto-Pistol', 'Hunting Rifle'], 'Chameleoline Cloak', 'Chain-Blade', 'Concealed Holster', 'Flak Coat', 'Security Kit'], 
        restrictions : [], 
        wounds: 1
    },
    { name : "Rogue Trader Fleet", 
        aptitudes : ["Finesse","Social"], 
        talents: [['Weapon Training (Las)', 'Weapon Training (Solid Projectile)'], 'Weapon Training (Shock)'], 
        skills : ['Awareness', ['Charm', 'Scrutiny'], ['Commerce', 'Command'], 'Common Lore (The Crimson Gulf)', 'Common Lore (Rogue Traders)', 'Deceive', 'Linguistics (Low Gothic)', 'Linguistics (One Xenos Language)'], 
        traits : [], 
        malignancies : [], 
        bonus : { name : "Face to the Unknown", desc : "A character from a Rogue Trader Fleet gains a +10 Bonus to Fear Tests. Additionally, they treat all Supernatural Fears caused by a Supernatural Fear Trait of Fear (2) or below as Mundane Fears." }, 
        equipment : ['1 Bottle of Amasec', 'Auspex', 'Chrono', 'Mesh Cloak', ['Las-Gun', 'Hunting Rifle'], 'Shock Maul'], 
        restrictions : [], 
        wounds: 0
        },
    { name : "Savage", 
        aptitudes : ["Offence","Fieldcraft"], 
        talents: ['Resistance (Any One)', 'Weapon Training (Low-Tech)'], 
        skills : ['Acrobatics', 'Athletics', 'Awareness', ['Dodge', 'Parry'], ['Intimidate', 'Stealth'], 'Linguistics (Low Gothic)', 'Survival'], 
        traits : [], 
        malignancies : [], 
        bonus : { name : "The Beast Beneath", desc : "At the start of their Turn, a Savage character may grant themselves the Unnatural Strength (2) or Unnatural Agility (2) Traits for one Round. If they already possess the Trait they wish to gain, they instead increase that Trait’s value by 2. At the start of their next Turn after using this ability, the Savage character gains one Level of Fatigue." }, 
        equipment : ['2 Bolas', '2 Doses of Dusk-Leaf', ['Great Weapon', ['Hunting Bow with Mono-Arrows', 'Sword']], 'Xenos Hide Vest'], 
        restrictions : [], 
        wounds: 1
    }
]

const ROLES = [
    { name : "Ace",
        aptitudes : ['Agility', 'Ballistic Skill', 'Finesse', 'Perception', ['Fieldcraft', 'Tech']],
        talents : [['Hard Target', 'Hotshot Pilot']],
        bonus : [{ name: "Right Stuff", desc: "An Ace Character may spend a Fate Point when failing an Operate Test or a Survival Test to control a Steed to reduce their Degrees of Failure by an amount equal to 1 plus half of their Base Agility Bonus. If this would reduce the Degrees of Failure to 0 or below, the Ace Instead succeeds on the Test with a number of degrees of success equal to half their Agility Bonus. This ability cannot be used on Tests with targets of 0 or below."}],
        restrictions : []
    },
    { name : "Assassin",
        aptitudes : ['Agility', ['Ballistic Skill', 'Weapon Skill'], 'Fieldcraft', 'Finesse', 'Perception'],
        talents : [['Ambush', 'Jaded']],
        bonus : [{ name: "Sure Kill", desc: "When an assassin successfully hits with an Attack, they may spend a Fate Point to inflict additional damage Equal to their Degrees of Success on the Attack roll (Maximum +10 Damage). This additional damage only applies to the first hit the attack inflicts."}],
        restrictions : []
    },
    { name : "Chirurgeon",
        aptitudes : ['Fieldcraft', 'Intelligence', 'Knowledge', 'Perception', 'Willpower'],
        talents : [['Aspiring Healer', 'Cease the Flow']],
        bonus : [{ name: "Dedicated Healer", desc: "A Chirurgeon Character may spend a Fate Point when failing Medicae or Trade (Chymist) Test to reduce their Degrees of Failure by an amount equal to 1 plus half of their Intelligence Bonus. If this would reduce the Degrees of Failure to 0 or below, the Ace Instead succeeds on the Test with a number of degrees of success equal to half their Intelligence Bonus. This ability cannot be used on Tests with targets of 0 or below."}],
        restrictions : []
    },
    { name : "Crusader",
        aptitudes : ['Conviction', 'Defence', 'Toughness', 'Weapon Skill', 'Willpower'],
        talents : [['Bodyguard', 'Vanguard']],
        bonus : [{ name: "Smite the Unholy", desc: "A Crusader Character may spend a Fate Point when failing a Fear Test to reduce their Degrees of Failure by an amount equal to 1 plus half of their Willpower Bonus. If this would reduce the Degrees of Failure to 0 or below, the Crusader Instead succeeds on the Test with a number of degrees of success equal to half their Willpower Bonus. This ability cannot be used on Tests with targets of 0 or below. In addition, whenever a Crusader hits with a melee attack against a target with the Fear (X) Trait, they inflict additional damage on each hit equal to the number in Parentheses (X)."}],
        restrictions : []
    },
    { name : "Desperado",
        aptitudes : ['Agility', 'Ballistic Skill', 'Defence', 'Fellowship', 'Finesse'],
        talents : [['Hammer Blast', 'Quick Draw']],
        bonus : [{ name: "The Quick and the Dead", desc: "Knowing when the time to act is upon them, a Desperado makes their move before any other. Whenever a Desperado Acolyte rolls for Initiative, if they roll a natural 7 or higher on their Initiative die, they may immediately take a Half Action of their choice before the first Round Begins. If a Desperado Acolyte instead rolls a natural 10 or chooses to spend a Fate Point to treat their Initiative as if they rolled a 10, they may instead make a Full Action or two Half Actions of their choice before the first Round begins instead. Note that these two Half Actions are considered to occur in the same turn, and as such are subject to Action Type restrictions, such as not being able to take two Attack Type Actions in the same Turn. A Desperado Character cannot use this Ability if they are Surprised, and this Ability does not confer any form of Surprise beyond that which a character already possesses."}],
        restrictions : []
    },
    { name : "Fanatic",
        aptitudes : ['Conviction', 'Offence', 'Toughness', 'Weapon Skill', 'Willpower'],
        talents : [['Resistance (Psychic Powers)', 'Jaded']],
        bonus : [{ name: "Death to All Who Opposed Me!", desc: "In their mission to destroy the God-Emperor’s enemies, a Fanatic can summon powers other warriors could only dream of. Whenever a Fanatic Acolyte successfully deals damage on an Attack (after accounting for reductions from Armour and Toughness), they may spend a Fate Point to treat the damaging hit as if it inflicted Righteous Fury. If the Fanatic uses this ability, they increase the Severity of the resulting Critical Effect by 1. Alternatively, a Fanatic may spend a Fate Point whenever they inflict Righteous Fury as the result of a Natural 10 to increase the Severity of the resulting Critical Effect by 2."}],
        restrictions : []
    },
    { name : "Hierophant",
        aptitudes : ['Fellowship', 'Offence', 'Social', 'Toughness', 'Willpower'],
        talents : [['Cunning Orator', 'Hatred (any)']],
        bonus : [{ name: "Sway the Masses", desc: "A Hierophant Character may spend a Fate Point when failing a Charm, Deceive, or Intimidate Test to reduce their Degrees of Failure by an amount equal to 1 plus half of their Willpower Bonus. If this would reduce the Degrees of Failure to 0 or below, the Hierophant Instead succeeds on the Test with a number of Degrees of Success equal to half their Willpower Bonus. This ability cannot be used on Tests with targets of 0 or below."}],
        restrictions : []
    },
    { name : "Infiltrator",
        aptitudes : ['Agility', 'Finesse', 'Fieldcraft', 'Intelligence', 'Perception'],
        talents : [['Leap Up', 'Fleet-Feet']],
        bonus : [{ name: "Shadow in the Night", desc: "An Infiltrator Character may spend a Fate Point when failing a Security or Stealth Test to reduce their Degrees of Failure by an amount equal to 1 plus half of their Agility Bonus. If this would reduce the Degrees of Failure to 0 or below, the Infiltrator Instead succeeds on the Test with a number of degrees of success equal to half their Agility Bonus. This ability cannot be used on Tests with targets of 0 or below."}],
        restrictions : []
    },
    { name : "Mystic",
        aptitudes : ['Conviction', 'Intelligence', 'Knowledge', 'Perception', 'Willpower'],
        talents : [['Resistance (Psychic Powers)', 'Warp Sensees']],
        bonus : [{ name: "Stare into the Warp", desc: "A Mystic character starts the game with the Psyker Beginner Advance. Practiced in the Dark Arts: Whenever a Mystic Character rolls on Table X-X: Perils of the Warp, they may spend a Fate Point to roll 6d10 instead of 1d100."}],
        restrictions : ['Humans', 'Squats']
    },
    { name : "Penitent",
        aptitudes : ['Conviction', 'Offence', 'Strength', 'Toughness', 'Willpower'],
        talents : [['Inner Rage', 'Flagellant']],
        bonus : [{ name: "Cleansing Pain", desc: "Whenever a Penitent character suffers 1 or more points of Damage (after reductions for Toughness and Armour), they gain a +10 Bonus to the first Test they make before the end of their next turn. If the Penitent Character spends a Fate Point upon the Activation of this Ability, they instead gain a +20 Bonus on all Tests they make until the end of their Next Turn."}],
        restrictions : []
    },
    { name : "Sage",
        aptitudes : ['Intelligence', 'Knowledge', 'Perception', 'Tech', 'Willpower'],
        talents : [['Spark of Knowledge', 'Logical Deduction']],
        bonus : [{ name: "Quest for Knowledge", desc: "A Sage Character may spend a Fate Point when failing a Logic or Lore Test to reduce their Degrees of Failure by an amount equal to 1 plus half of their Intelligence Bonus. If this would reduce the Degrees of Failure to 0 or below, the Sage Instead succeeds on the Test with a number of degrees of success equal to half their Intelligence Bonus. This ability cannot be used on Tests with targets of 0 or below."}],
        restrictions : []
    },
    { name : "Seeker",
        aptitudes : ['Fellowship', 'Intelligence', 'Perception', 'Social', 'Tech'],
        talents : [['Charming Demeanour', 'Keen Intuition']],
        bonus : [{ name: "Right Stuff", desc: "A Seeker Character may spend a Fate Point when failing an Awareness or Inquiry Test to reduce their Degrees of Failure by an amount equal to 1 plus half of their Perception Bonus. If this would reduce the Degrees of Failure to 0 or below, the Seeker Instead succeeds on the Test with a number of degrees of success equal to half their Perception Bonus. This ability cannot be used on Tests with targets of 0 or below."}],
        restrictions : []
    },
    { name : "Tactician",
        aptitudes : ['Fellowship', 'Intelligence', 'Knowledge', 'Leadership', 'Perception'],
        talents : [['Commanding Presence', 'Shared Destiny']],
        bonus : [{ name: "Tactical Expertise", desc: "A Tactician Character may spend a Fate Point when failing a Command Test or Test to activate a Stratagem to reduce their Degrees of Failure by an amount equal to 1 plus half of their Intelligence Bonus. If this would reduce the Degrees of Failure to 0 or below, the Tactician Instead succeeds on the Test with a number of degrees of success equal to half their Intelligence Bonus. This ability cannot be used on Tests with targets of 0 or below."}],
        restrictions : []
    },
    { name : "Warrior",
        aptitudes : ['Ballistic Skill', 'Defence', 'Offence', 'Strength', 'Weapon Skill'],
        talents : [['Iron Jaw', 'Rapid Reload']],
        bonus : [{ name: "Expert at Violence", desc: "After making a successful Attack Test, but before determining hits, a Warrior character may spend a Fate Point to substitute their Weapon Skill (for melee) or Ballistic Skill (for ranged) Bonus for the Degrees of Success scored on the Attack Test."}],
        restrictions : []
    }
]



var regex_genos = /(.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)/
var regex_homeworld = /(.*)\t(.*) or (.*)\t(.*): (.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*)/
var regex_background = /(.*)\t(.*) or (.*)\t(.*)\t(.*)\t(.*)\t(.*)\t(.*): (.*)\t(.*)\t(.*)\t(.*)/

var homeworld_replace = '{ name : "$1", aptitudes : ["$2","$3"], bonus : { name : "$4", desc : "$5" }, characteristics : {$6 $7}, fate : $8, empBlessing : $9, wounds : $10}'
var background_replace = '{ name : "$1", aptitudes : ["$2","$3"], talents: [$4], skills : [$5], traits : [$6], malignancies : [$7], bonus : { name : "$8", desc : "$9" }, equipment : [$10], restrictions : $11, wounds: $12}'

