const CHARACTERISTICS = [
    {name: "Weapon Skill", aptitudes : ["Weapon Skill", "Offence"]},
    {name: "Ballistic Skill", aptitudes : ["Ballistic Skill", "Finesse"]},
    {name: "Strength", aptitudes : ["Strength", "Offence"]},
    {name: "Toughness", aptitudes : ["Toughness", "Defence"]},
    {name: "Agility", aptitudes : ["Agility", "Finesse"]},
    {name: "Intelligence", aptitudes : ["Intelligence", "Knowledge"]},
    {name: "Perception", aptitudes : ["Perception", "Fieldcraft"]},
    {name: "Willpower", aptitudes : ["Willpower", "Psyker"]},
    {name: "Fellowship", aptitudes : ["Fellowship", "Social"]}
]
const SKILLS = [
    {name: "Acrobatics", aptitudes : ["Agility", "General"]},
    {name: "Athletics", aptitudes : ["Strength", "General"]},
    {name: "Awareness", aptitudes : ["Perception", "Fieldcraft"]},
    {name: "Charm", aptitudes : ["Fellowship", "Social"]},
    {name: "Command", aptitudes : ["Fellowship", "Leadership"]},
    {name: "Commerce", aptitudes : ["Intelligence", "Knowledge"]},
    {name: "Common Lore X", aptitudes : ["Intelligence", "General"]},
    {name: "Deceive", aptitudes : ["Fellowship", "Social"]},
    {name: "Dodge", aptitudes : ["Agility", "Defence"]},
    {name: "Forbidden Lore X", aptitudes : ["Intelligence", "Knowledge"]},
    {name: "Inquiry", aptitudes : ["Fellowship", "Social"]},
    {name: "Interrogation", aptitudes : ["Willpower", "Social"]},
    {name: "Intimidate", aptitudes : ["Strength", "Social"]},
    {name: "Linguistics X", aptitudes : ["Intelligence", "General"]},
    {name: "Logic", aptitudes : ["Intelligence", "Knowledge"]},
    {name: "Medicae", aptitudes : ["Intelligence", "Fieldcraft"]},
    {name: "Navigate X", aptitudes : ["Intelligence", "Fieldcraft"]},
    {name: "Operate X", aptitudes : ["Agility", "Fieldcraft"]},
    {name: "Parry", aptitudes : ["Weapon Skill", "Defence"]},
    {name: "Psyniscience", aptitudes : ["Perception", "Psyker"]},
    {name: "Scholastic Lore X", aptitudes : ["Intelligence", "Knowledge"]},
    {name: "Scrutiny", aptitudes : ["Perception", "General"]},
    {name: "Security", aptitudes : ["Intelligence", "Tech"]},
    {name: "Sleight of Hand", aptitudes : ["Agility", "Knowledge"]},
    {name: "Stealth", aptitudes : ["Agility", "Fieldcraft"]},
    {name: "Survival", aptitudes : ["Perception", "Fieldcraft"]},
    {name: "Tech-Use", aptitudes : ["Intelligence", "Tech"]},
    {name: "Trade X", aptitudes : ["Intelligence", "General"]}
]
const TIER_1_TALENTS = [
    {name: "Ambidextrous", aptitudes : ["Weapon Skill", "Ballistic Skill"]},
    {name: "Blind Fighting", aptitudes : ["Perception", "Fieldcraft"]},
    {name: "Bodyguard", aptitudes : ["Agility", "Defence"]},
    {name: "Catfall", aptitudes : ["Agility", "Fieldcraft"]},
    {name: "Clues from the Crowds", aptitudes : ["General", "Social"]},
    {name: "Die Hard", aptitudes : ["Willpower", "Defence"]},
    {name: "Disarm", aptitudes : ["Weapon Skill", "Defence"]},
    {name: "Double Team", aptitudes : ["General", "Offence"]},
    {name: "Enemy X", aptitudes : ["General", "Social"]},
    {name: "Ferric Summons", aptitudes : ["Willpower", "Tech"]},
    {name: "Flagellant", aptitudes : ["Offence", "Toughness"]},
    {name: "Frenzy", aptitudes : ["Strength", "Offence"]},
    {name: "Grenadier", aptitudes : ["Ballistic Skill", "Finesse"]},
    {name: "Iron Jaw", aptitudes : ["Toughness", "Defence"]},
    {name: "Jaded", aptitudes : ["Willpower", "Defence"]},
    {name: "Keen Intuition", aptitudes : ["Perception", "Social"]},
    {name: "Leap Up", aptitudes : ["Agility", "General"]},
    {name: "Leaping Dodge", aptitudes : ["Agility", "Defence"]},
    {name: "Mounted Warrior Melee", aptitudes : ["Weapon Skill", "Offence"]},
    {name: "Mounted Warrior Ranged", aptitudes : ["Ballistic Skill", "Offence"]},
    {name: "Nowhere to Hide", aptitudes : ["Perception", "Offence"]},
    {name: "Peer X", aptitudes : ["Fellowship", "Social"]},
    {name: "Quick Draw", aptitudes : ["Agility", "Finesse"]},
    {name: "Rapid Reload", aptitudes : ["Agility", "Fieldcraft"]},
    {name: "Resistance X", aptitudes : ["Toughness", "Defence"]},
    {name: "Skilled Rider", aptitudes : ["Agility", "Fieldcraft"]},
    {name: "Sound Constitution", aptitudes : ["Toughness", "General"]},
    {name: "Takedown", aptitudes : ["Weapon Skill", "Offence"]},
    {name: "Technical Knock", aptitudes : ["Intelligence", "Tech"]},
    {name: "Warp Sense", aptitudes : ["Perception", "Psyker"]},
    {name: "Weapon Training X", aptitudes : ["General", "General"]},
    {name: "Weapon-Tech", aptitudes : ["Intelligence", "Tech"]}
]
const TIER_2_TALENTS = [
    {name: "Ambassador Imperialis", aptitudes : ["Perception", "Social"]},
    {name: "Archivator", aptitudes : ["Knowledge", "Social"]},
    {name: "Armor-Monger", aptitudes : ["Intelligence", "Tech"]},
    {name: "Battle Rage", aptitudes : ["Strength", "Defence"]},
    {name: "Bulging Biceps", aptitudes : ["Strength", "Offence"]},
    {name: "Bulwark of Faith", aptitudes : ["Defence", "Willpower"]},
    {name: "Combat Master", aptitudes : ["Weapon Skill", "Defence"]},
    {name: "Constant Vigilance X", aptitudes : ["Perception", "Defence"]},
    {name: "Contact Network", aptitudes : ["Fellowship", "Leadership"]},
    {name: "Coordinated Interrogation", aptitudes : ["Intelligence", "Social"]},
    {name: "Counter Attack", aptitudes : ["Weapon Skill", "Defence"]},
    {name: "Cover-Up", aptitudes : ["Intelligence", "Knowledge"]},
    {name: "Daemonhunter", aptitudes : ["Offence", "Willpower"]},
    {name: "Daemonologist", aptitudes : ["Psyker", "Willpower"]},
    {name: "Deny the Witch", aptitudes : ["Willpower", "Defence"]},
    {name: "Devastating Assault", aptitudes : ["Weapon Skill", "Offence"]},
    {name: "Double Tap", aptitudes : ["Finesse", "Offence"]},
    {name: "Exotic Weapon Training", aptitudes : ["Intelligence", "Finesse"]},
    {name: "Face in a Crowd", aptitudes : ["Fellowship", "Social"]},
    {name: "Field Vivisection Melee", aptitudes : ["Weapon Skill", "Knowledge"]},
    {name: "Field Vivisection Ranged", aptitudes : ["Ballistic Skill", "Knowledge"]},
    {name: "Hard Target", aptitudes : ["Agility", "Defence"]},
    {name: "Harden Soul", aptitudes : ["Defence", "Willpower"]},
    {name: "Hardy", aptitudes : ["Toughness", "Defence"]},
    {name: "Hatred X", aptitudes : ["Weapon Skill", "Social"]},
    {name: "Hip Shooting", aptitudes : ["Ballistic Skill", "Finesse"]},
    {name: "Hotshot Pilot", aptitudes : ["Agility", "Tech"]},
    {name: "Independent Targeting", aptitudes : ["Ballistic Skill", "Finesse"]},
    {name: "Inescapable Attack Melee", aptitudes : ["Weapon Skill", "Finesse"]},
    {name: "Inescapable Attack Ranged", aptitudes : ["Ballistic Skill", "Finesse"]},
    {name: "Inspiring Aura", aptitudes : ["Leadership", "Willpower"]},
    {name: "Iron Resolve", aptitudes : ["Defence", "Willpower"]},
    {name: "Killing Strike", aptitudes : ["Weapon Skill", "Offence"]},
    {name: "Lexographer", aptitudes : ["Intelligence", "Knowledge"]},
    {name: "Luminen Shock", aptitudes : ["Weapon Skill", "Tech"]},
    {name: "Maglev Transcendence", aptitudes : ["Intelligence", "Tech"]},
    {name: "Marksman", aptitudes : ["Ballistic Skill", "Finesse"]},
    {name: "Mechadendrite Use X", aptitudes : ["Intelligence", "Tech"]},
    {name: "One-on-One", aptitudes : ["Finesse", "Weapon Skill"]},
    {name: "Penitent Psyker", aptitudes : ["Psyker", "Defence"]},
    {name: "Precision Killer Melee", aptitudes : ["Weapon Skill", "Finesse"]},
    {name: "Precision Killer Ranged", aptitudes : ["Ballistic Skill", "Finesse"]},
    {name: "Prosanguine", aptitudes : ["Toughness", "Tech"]},
    {name: "Purity of Hatred", aptitudes : ["Offence", "Willpower"]},
    {name: "Rites of Banishment", aptitudes : ["Offence", "Willpower"]},
    {name: "Strong Minded", aptitudes : ["Willpower", "Defence"]},
    {name: "Swift Attack", aptitudes : ["Weapon Skill", "Finesse"]},
    {name: "Tainted Psyker", aptitudes : ["Knowledge", "Psyker"]},
    {name: "Two-Weapon Wielder Melee", aptitudes : ["Weapon Skill", "Finesse"]},
    {name: "Two-Weapon Wielder Ranged", aptitudes : ["Ballistic Skill", "Finesse"]},
    {name: "Unarmed Specialist", aptitudes : ["Strength", "Offence"]},
    {name: "Warp Conduit", aptitudes : ["Willpower", "Psyker"]},
    {name: "Whirlwind of Death", aptitudes : ["Weapon Skill", "Finesse"]},
    {name: "Witch Finder", aptitudes : ["Knowledge", "Perception"]},
    {name: "Xenosavant", aptitudes : ["Intelligence", "Knowledge"]}
]
const TIER_3_TALENTS = [
    {name: "Adamantium Faith", aptitudes : ["Willpower", "Defence"]},
    {name: "Aegis of Contempt", aptitudes : ["Defence", "Leadership"]},
    {name: "Assassin Strike", aptitudes : ["Weapon Skill", "Fieldcraft"]},
    {name: "Bastion of Iron Will", aptitudes : ["Willpower", "Psyker"]},
    {name: "Blademaster", aptitudes : ["Weapon Skill", "Finesse"]},
    {name: "Crushing Blow", aptitudes : ["Weapon Skill", "Offence"]},
    {name: "Daemonic Disruption", aptitudes : ["Willpower", "General"]},
    {name: "Dark Soul", aptitudes : ["Toughness", "Willpower"]},
    {name: "Deathdealer", aptitudes : ["Perception", "Finesse"]},
    {name: "Delicate Interrogation", aptitudes : ["Intelligence", "Finesse"]},
    {name: "Divine Protection", aptitudes : ["General", "Finesse"]},
    {name: "Eye of Vengeance", aptitudes : ["Ballistic Skill", "Offence"]},
    {name: "Favored by the Warp", aptitudes : ["Willpower", "Psyker"]},
    {name: "Flash of Insight", aptitudes : ["Perception", "Knowledge"]},
    {name: "Halo of Command", aptitudes : ["Fellowship", "Leadership"]},
    {name: "Hammer Blow", aptitudes : ["Strength", "Offence"]},
    {name: "Hull Down", aptitudes : ["Agility", "Fieldcraft"]},
    {name: "Indomitable Conviction", aptitudes : ["Leadership", "Willpower"]},
    {name: "Infused Knowledge", aptitudes : ["Intelligence", "Knowledge"]},
    {name: "Instrument of His Will", aptitudes : ["Offence", "Willpower"]},
    {name: "Into the Jaws of Hell", aptitudes : ["Leadership", "Willpower"]},
    {name: "Iron Faith", aptitudes : ["Defence", "Willpower"]},
    {name: "Lightning Attack", aptitudes : ["Weapon Skill", "Finesse"]},
    {name: "Luminen Blast", aptitudes : ["Ballistic Skill", "Tech"]},
    {name: "Mastery X", aptitudes : ["Intelligence", "Knowledge"]},
    {name: "Mighty Shot", aptitudes : ["Ballistic Skill", "Offence"]},
    {name: "Never Die", aptitudes : ["Toughness", "Defence"]},
    {name: "Preternatural Speed", aptitudes : ["Agility", "Offence"]},
    {name: "Push the Limit", aptitudes : ["Perception", "Tech"]},
    {name: "Sanctic Purity", aptitudes : ["Psyker", "Willpower"]},
    {name: "Shield Wall", aptitudes : ["Defence", "Weapon Skill"]},
    {name: "Sprint", aptitudes : ["Agility", "Fieldcraft"]},
    {name: "Step Aside", aptitudes : ["Agility", "Defence"]},
    {name: "Superior Chirurgeon", aptitudes : ["Intelligence", "Fieldcraft"]},
    {name: "Target Selection", aptitudes : ["Ballistic Skill", "Finesse"]},
    {name: "Thunder Charge", aptitudes : ["Strength", "Offence"]},
    {name: "True Grit", aptitudes : ["Toughness", "Defence"]},
    {name: "Two-Weapon Master", aptitudes : ["Finesse", "Offence"]},
    {name: "Warp Lock", aptitudes : ["Willpower", "Psyker"]},
    {name: "Weapon Intuition", aptitudes : ["Intelligence", "Finesse"]}
]