var ShapedSpellbookDefaults = {
  "hash": "05f980a318ca8ba28aa465d5fb34caac",
  "values": {
    "spellbaselevel": "{{num}}",
    "higher_level_query": "{{higherLevelQuery}}",
    "spellname": "",
    "spellisprepared": 0,
    "spellritual": 0,
    "spellconcentration": 0,
    "spellcomponents_material_var": "{{spell_components_material=@{spellcomponents}}}",
    "spellcomponents_verbal": 0,
    "spellcomponents_somatic": 0,
    "spellcomponents_material": 0,
    "spell_casting_time_longer_var": "@{spellcasttime}",
    "spell_casting_time": "@{spell_casting_time_action_var}",
    "spellcasttime": "",
    "spellrange": "",
    "spellduration": "",
    "spellschool": "",
    "spellcomponents": "",
    "spelltarget": "",
    "spellaoe": "",
    "spell_var_description": "{{spelldescription=@{spelldescription}}}",
    "spell_var_higher_lvl": "{{spellhigherlevel=@{spellhighersloteffect}}}",
    "spell_var_output_higher_lvl_query": "{{spell_cast_as_level=?{Spell Level}}}",
    "spell_attack_higher_level_formula": "((@{spell_toggle_higher_lvl_query} - @{spellbaselevel}) * @{spell_attack_higher_level_dmg_dice})@{spell_attack_higher_level_dmg_die}[higher lvl]",
    "spell_attack_higher_level_formula_second": "((@{spell_toggle_higher_lvl_query} - @{spellbaselevel}) * @{spell_attack_second_higher_level_dmg_dice})@{spell_attack_second_higher_level_dmg_die}[higher lvl]",
    "spell_var_emote": "{{emote=@{spellemote}}}",
    "spell_var_attack": "{{attack=[[d20cs>@{spell_attack_crit_range}@{d20_mod} + @{spell_to_hit} + (@{global_spell_attack_bonus})]]}} {{attackadv=[[d20cs>@{spell_attack_crit_range}@{d20_mod} + @{spell_to_hit} + (@{global_spell_attack_bonus})]]}} {{targetAC=@{attacks_vs_target_ac}}} {{targetName=@{attacks_vs_target_name}}}",
    "spell_var_attack_damage": "{{action_damage=[[0d0 + @{spell_attack_dmg}[dmg] + @{spell_attack_dmg_total}[bonus dmg] + (@{global_spell_damage_bonus})[global spell dmg bonus] + @{spell_attack_higher_level_formula}]]}} {{action_damage_type=@{spell_attack_dmg_type}}}",
    "spell_var_attack_second_damage": "{{action_second_damage=[[0d0 + @{spell_attack_second_dmg}[dmg] + @{spell_attack_second_dmg_total}[bonus dmg] + (@{global_spell_damage_bonus})[global spell dmg bonus] + @{spell_attack_higher_level_formula_second}]]}} {{action_second_damage_type=@{spell_attack_second_dmg_type}}}",
    "spell_var_attack_crit": "{{can_crit=1}} {{action_crit_damage=[[0d0 + @{spell_attack_dmg} + @{spell_attack_higher_level_formula}]]}} {{action_second_crit_damage=[[0d0 + @{spell_attack_second_dmg} + @{spell_attack_higher_level_formula_second}]]}}",
    "spell_var_save": "{{action_save=1}} {{save_dc=[[@{spell_save_dc_total}]]}} {{action_save_stat=@{savestat}}} {{save_condition=@{save_condition}}} {{save_failure=@{savefailure}}} {{save_success=@{savesuccess}}} {{targetName=@{attacks_vs_target_name}}}",
    "spell_var_save_damage": "{{save_damage=[[0d0 + @{spell_save_dmg}[dmg] + @{spell_save_dmg_total}[bonus dmg] + (@{global_spell_damage_bonus})[global spell dmg bonus] + ((@{spell_toggle_higher_lvl_query} - @{spellbaselevel}) * @{spell_save_higher_level_dmg_dice})@{spell_save_higher_level_dmg_die}[higher lvl] ]]}} {{save_damage_type=@{spell_save_dmg_type}}}",
    "spell_var_save_second_damage": "{{save_second_damage=[[0d0 + @{spell_save_second_dmg}[dmg] + @{spell_save_second_dmg_total}[bonus dmg] + (@{global_spell_damage_bonus})[global spell dmg bonus] + ((@{spell_toggle_higher_lvl_query} - @{spellbaselevel}) * @{spell_save_second_higher_level_dmg_dice})@{spell_save_second_higher_level_dmg_die}[higher lvl] ]]}} {{save_second_damage_type=@{spell_save_second_dmg_type}}}",
    "spell_var_healing": "{{spellhealing=[[0d0 + @{spellhealamount}[amount] + @{healstatbonus}[stat bonus] + @{healbonus}[bonus] + (@{global_spell_heal_bonus})[global spell heal bonus] + ((@{spell_toggle_higher_lvl_query} - @{spellbaselevel}) * @{spell_heal_higher_level_amount}) + ((@{spell_toggle_higher_lvl_query} - @{spellbaselevel}) * @{spell_heal_higher_level_dmg_dice})@{spell_heal_higher_level_dmg_die}[higher lvl] ]]}}",
    "spell_var_effects": "{{effects=@{spelleffect}}}",
    "spell_var_source": "{{spellsource=@{spellsource}}}",
    "spell_var_gained_from": "{{spellgainedfrom=@{spellgainedfrom}}}",
    "spell_var_bonuses": "1",
    "spell_toggle_description": 0,
    "spell_toggle_higher_lvl": 0,
    "spell_toggle_higher_lvl_query": 0,
    "spell_toggle_output_higher_lvl_query": 0,
    "spell_toggle_emote": 0,
    "spell_toggle_attack": 0,
    "spell_toggle_attack_damage": 0,
    "spell_toggle_attack_crit": 0,
    "spell_toggle_attack_second_damage": 0,
    "spell_toggle_save": 0,
    "spell_toggle_save_damage": 0,
    "spell_toggle_save_second_damage": 0,
    "spell_toggle_bonuses": 0,
    "spell_toggle_healing": 0,
    "spell_toggle_effects": 0,
    "spell_toggle_source": 0,
    "spell_toggle_gained_from": 0,
    "spelldescription": "",
    "spellhighersloteffect": "",
    "spellemote": "",
    "spellgainedfrom": "Not Set",
    "spellsource": "",
    "attackstat": "@{casting_stat}",
    "spell_attack_bonus": "0",
    "spell_to_hit": "@{PB} + @{attackstat} + (@{spell_attack_bonus} * @{spell_toggle_bonuses})",
    "spell_attack_dmg": "",
    "spell_attack_dmg_stat": "0",
    "spell_attack_dmg_bonus": "0",
    "spell_attack_dmg_total": "@{spell_attack_dmg_stat} + (@{spell_attack_dmg_bonus} * @{spell_toggle_bonuses})",
    "spell_attack_dmg_type": "",
    "spell_attack_higher_level_dmg_dice": "0",
    "spell_attack_higher_level_dmg_die": "",
    "spell_attack_second_dmg": "",
    "spell_attack_second_dmg_stat": "0",
    "spell_attack_second_dmg_bonus": "0",
    "spell_attack_second_dmg_total": "@{spell_attack_second_dmg_stat} + (@{spell_attack_second_dmg_bonus} * @{spell_toggle_bonuses})",
    "spell_attack_second_dmg_type": "",
    "spell_attack_second_higher_level_dmg_dice": "0",
    "spell_attack_second_higher_level_dmg_die": "",
    "spell_attack_crit_range": "20",
    "save_condition": "",
    "savestat": "Str",
    "spellsavedc": "@{casting_stat_dc}",
    "spell_save_dc_bonus": "0",
    "spell_save_dc_total": "@{spellsavedc}[dc] + (@{spell_save_dc_bonus} * @{spell_toggle_bonuses})[bonus]",
    "savefailure": "",
    "savesuccess": "",
    "spell_save_dmg": "",
    "spell_save_dmg_stat": "0",
    "spell_save_dmg_bonus": "0",
    "spell_save_dmg_total": "@{spell_save_dmg_stat} + (@{spell_save_dmg_bonus} * @{spell_toggle_bonuses})",
    "spell_save_dmg_type": "",
    "spell_save_higher_level_dmg_dice": "0",
    "spell_save_higher_level_dmg_die": "",
    "spell_save_second_dmg": "",
    "spell_save_second_dmg_stat": "0",
    "spell_save_second_dmg_bonus": "0",
    "spell_save_second_dmg_total": "@{spell_save_second_dmg_stat} + (@{spell_save_second_dmg_bonus} * @{spell_toggle_bonuses})",
    "spell_save_second_dmg_type": "",
    "spell_save_second_higher_level_dmg_dice": "0",
    "spell_save_second_higher_level_dmg_die": "",
    "spellhealamount": "",
    "healbonus": "",
    "healstatbonus": "0",
    "spell_heal_higher_level_amount": "",
    "spell_heal_higher_level_dmg_dice": "0",
    "spell_heal_higher_level_dmg_die": "",
    "spelleffect": ""
  }
};