name: Sheet HTTP Action Simulate All

on: workflow_dispatch
jobs:
  update-sheet-http:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: ./.actions/sheet-http
        with:
          file-list: ${{ needs.get-list.outputs.file-list }}
          separator: "::"
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          run-all: true
          simulate: true
        env:
          TAVERN_API_KEY: ${{ secrets.TAVERN_API_KEY }}
          TAVERN_TOKEN: ${{ secrets.TAVERN_TOKEN }}
          STAGING_API_KEY: ${{ secrets.STAGING_API_KEY }}
          PRODUCTION_API_KEY: ${{ secrets.PRODUCTION_API_KEY }}
